"""
Datos de la matriz de desplazamientos del Oriente Antioqueño
23 municipios, 506 rutas
"""

# Lista de municipios del Oriente Antioqueño
MUNICIPIOS = [
    {"nombre": "Abejorral", "departamento": "Antioquia"},
    {"nombre": "Alejandría", "departamento": "Antioquia"},
    {"nombre": "Argelia", "departamento": "Antioquia"},
    {"nombre": "Cocorná", "departamento": "Antioquia"},
    {"nombre": "Concepción", "departamento": "Antioquia"},
    {"nombre": "El Carmen de Viboral", "departamento": "Antioquia"},
    {"nombre": "El Peñol", "departamento": "Antioquia"},
    {"nombre": "El Retiro", "departamento": "Antioquia"},
    {"nombre": "Granada", "departamento": "Antioquia"},
    {"nombre": "Guarne", "departamento": "Antioquia"},
    {"nombre": "Guatapé", "departamento": "Antioquia"},
    {"nombre": "La Ceja", "departamento": "Antioquia"},
    {"nombre": "La Unión", "departamento": "Antioquia"},
    {"nombre": "Marinilla", "departamento": "Antioquia"},
    {"nombre": "Nariño", "departamento": "Antioquia"},
    {"nombre": "Rionegro", "departamento": "Antioquia"},
    {"nombre": "San Carlos", "departamento": "Antioquia"},
    {"nombre": "San Francisco", "departamento": "Antioquia"},
    {"nombre": "San Luis", "departamento": "Antioquia"},
    {"nombre": "San Rafael", "departamento": "Antioquia"},
    {"nombre": "San Vicente Ferrer", "departamento": "Antioquia"},
    {"nombre": "Santuario", "departamento": "Antioquia"},
    {"nombre": "Sonsón", "departamento": "Antioquia"},
]


# Rutas entre municipios (origen, destino, distancia_km, tiempo_minutos)
RUTAS = [
    {"origen": "El Carmen de Viboral", "destino": "El Retiro", "distancia_km": 32.0, "tiempo_minutos": 55},
    {"origen": "El Carmen de Viboral", "destino": "Santuario", "distancia_km": 15.2, "tiempo_minutos": 29},
    {"origen": "El Carmen de Viboral", "destino": "Guarne", "distancia_km": 29.2, "tiempo_minutos": 44},
    {"origen": "El Carmen de Viboral", "destino": "La Ceja", "distancia_km": 15.3, "tiempo_minutos": 30},
    {"origen": "El Carmen de Viboral", "destino": "Marinilla", "distancia_km": 15.2, "tiempo_minutos": 32},
    {"origen": "El Carmen de Viboral", "destino": "La Unión", "distancia_km": 27.2, "tiempo_minutos": 47},
    {"origen": "El Carmen de Viboral", "destino": "Rionegro", "distancia_km": 11.7, "tiempo_minutos": 29},
    {"origen": "El Carmen de Viboral", "destino": "San Vicente Ferrer", "distancia_km": 33.1, "tiempo_minutos": 59},
    {"origen": "El Carmen de Viboral", "destino": "Alejandría", "distancia_km": 73.6, "tiempo_minutos": 127},
    {"origen": "El Carmen de Viboral", "destino": "Concepción", "distancia_km": 56.4, "tiempo_minutos": 97},
    {"origen": "El Carmen de Viboral", "destino": "El Peñol", "distancia_km": 33.9, "tiempo_minutos": 64},
    {"origen": "El Carmen de Viboral", "destino": "Granada", "distancia_km": 28.8, "tiempo_minutos": 50},
    {"origen": "El Carmen de Viboral", "destino": "Guatapé", "distancia_km": 48.2, "tiempo_minutos": 91},
    {"origen": "El Carmen de Viboral", "destino": "San Carlos", "distancia_km": 69.5, "tiempo_minutos": 123},
    {"origen": "El Carmen de Viboral", "destino": "San Rafael", "distancia_km": 75.5, "tiempo_minutos": 134},
    {"origen": "El Carmen de Viboral", "destino": "Sonsón", "distancia_km": 80.7, "tiempo_minutos": 131},
    {"origen": "El Carmen de Viboral", "destino": "Nariño", "distancia_km": 115.0, "tiempo_minutos": 187},
    {"origen": "El Carmen de Viboral", "destino": "Argelia", "distancia_km": 114.0, "tiempo_minutos": 188},
    {"origen": "El Carmen de Viboral", "destino": "Abejorral", "distancia_km": 59.2, "tiempo_minutos": 110},
    {"origen": "El Carmen de Viboral", "destino": "Cocorná", "distancia_km": 36.5, "tiempo_minutos": 63},
    {"origen": "El Carmen de Viboral", "destino": "San Francisco", "distancia_km": 57.2, "tiempo_minutos": 92},
    {"origen": "El Carmen de Viboral", "destino": "San Luis", "distancia_km": 88.5, "tiempo_minutos": 128},
    {"origen": "El Retiro", "destino": "El Carmen de Viboral", "distancia_km": 31.5, "tiempo_minutos": 56},
    {"origen": "El Retiro", "destino": "Santuario", "distancia_km": 39.9, "tiempo_minutos": 59},
    {"origen": "El Retiro", "destino": "Guarne", "distancia_km": 33.2, "tiempo_minutos": 49},
    {"origen": "El Retiro", "destino": "La Ceja", "distancia_km": 17.3, "tiempo_minutos": 32},
    {"origen": "El Retiro", "destino": "Marinilla", "distancia_km": 28.1, "tiempo_minutos": 49},
    {"origen": "El Retiro", "destino": "La Unión", "distancia_km": 34.4, "tiempo_minutos": 58},
    {"origen": "El Retiro", "destino": "Rionegro", "distancia_km": 20.2, "tiempo_minutos": 32},
    {"origen": "El Retiro", "destino": "San Vicente Ferrer", "distancia_km": 45.5, "tiempo_minutos": 75},
    {"origen": "El Retiro", "destino": "Alejandría", "distancia_km": 85.9, "tiempo_minutos": 144},
    {"origen": "El Retiro", "destino": "Concepción", "distancia_km": 68.8, "tiempo_minutos": 113},
    {"origen": "El Retiro", "destino": "El Peñol", "distancia_km": 47.3, "tiempo_minutos": 81},
    {"origen": "El Retiro", "destino": "Granada", "distancia_km": 53.5, "tiempo_minutos": 80},
    {"origen": "El Retiro", "destino": "Guatapé", "distancia_km": 61.6, "tiempo_minutos": 108},
    {"origen": "El Retiro", "destino": "San Carlos", "distancia_km": 94.2, "tiempo_minutos": 152},
    {"origen": "El Retiro", "destino": "San Rafael", "distancia_km": 88.8, "tiempo_minutos": 150},
    {"origen": "El Retiro", "destino": "Sonsón", "distancia_km": 87.8, "tiempo_minutos": 143},
    {"origen": "El Retiro", "destino": "Nariño", "distancia_km": 122.0, "tiempo_minutos": 199},
    {"origen": "El Retiro", "destino": "Argelia", "distancia_km": 121.0, "tiempo_minutos": 200},
    {"origen": "El Retiro", "destino": "Abejorral", "distancia_km": 58.7, "tiempo_minutos": 109},
    {"origen": "El Retiro", "destino": "Cocorná", "distancia_km": 61.2, "tiempo_minutos": 93},
    {"origen": "El Retiro", "destino": "San Francisco", "distancia_km": 81.8, "tiempo_minutos": 122},
    {"origen": "El Retiro", "destino": "San Luis", "distancia_km": 113.0, "tiempo_minutos": 158},
    {"origen": "Santuario", "destino": "El Carmen de Viboral", "distancia_km": 16.7, "tiempo_minutos": 31},
    {"origen": "Santuario", "destino": "El Retiro", "distancia_km": 39.9, "tiempo_minutos": 64},
    {"origen": "Santuario", "destino": "Guarne", "distancia_km": 30.9, "tiempo_minutos": 37},
    {"origen": "Santuario", "destino": "La Ceja", "distancia_km": 37.8, "tiempo_minutos": 64},
    {"origen": "Santuario", "destino": "Marinilla", "distancia_km": 12.0, "tiempo_minutos": 18},
    {"origen": "Santuario", "destino": "La Unión", "distancia_km": 49.7, "tiempo_minutos": 81},
    {"origen": "Santuario", "destino": "Rionegro", "distancia_km": 19.8, "tiempo_minutos": 32},
    {"origen": "Santuario", "destino": "San Vicente Ferrer", "distancia_km": 34.8, "tiempo_minutos": 51},
    {"origen": "Santuario", "destino": "Alejandría", "distancia_km": 75.3, "tiempo_minutos": 119},
    {"origen": "Santuario", "destino": "Concepción", "distancia_km": 58.1, "tiempo_minutos": 89},
    {"origen": "Santuario", "destino": "El Peñol", "distancia_km": 28.7, "tiempo_minutos": 47},
    {"origen": "Santuario", "destino": "Granada", "distancia_km": 14.8, "tiempo_minutos": 25},
    {"origen": "Santuario", "destino": "Guatapé", "distancia_km": 43.0, "tiempo_minutos": 75},
    {"origen": "Santuario", "destino": "San Carlos", "distancia_km": 55.5, "tiempo_minutos": 98},
    {"origen": "Santuario", "destino": "San Rafael", "distancia_km": 70.2, "tiempo_minutos": 117},
    {"origen": "Santuario", "destino": "Sonsón", "distancia_km": 103.0, "tiempo_minutos": 165},
    {"origen": "Santuario", "destino": "Nariño", "distancia_km": 137.0, "tiempo_minutos": 221},
    {"origen": "Santuario", "destino": "Argelia", "distancia_km": 136.0, "tiempo_minutos": 222},
    {"origen": "Santuario", "destino": "Abejorral", "distancia_km": 74.5, "tiempo_minutos": 139},
    {"origen": "Santuario", "destino": "Cocorná", "distancia_km": 22.5, "tiempo_minutos": 38},
    {"origen": "Santuario", "destino": "San Francisco", "distancia_km": 43.2, "tiempo_minutos": 68},
    {"origen": "Santuario", "destino": "San Luis", "distancia_km": 74.4, "tiempo_minutos": 103},
    {"origen": "Guarne", "destino": "El Carmen de Viboral", "distancia_km": 28.7, "tiempo_minutos": 43},
    {"origen": "Guarne", "destino": "El Retiro", "distancia_km": 32.9, "tiempo_minutos": 45},
    {"origen": "Guarne", "destino": "Santuario", "distancia_km": 31.0, "tiempo_minutos": 34},
    {"origen": "Guarne", "destino": "La Ceja", "distancia_km": 38.9, "tiempo_minutos": 56},
    {"origen": "Guarne", "destino": "Marinilla", "distancia_km": 19.7, "tiempo_minutos": 24},
    {"origen": "Guarne", "destino": "La Unión", "distancia_km": 50.3, "tiempo_minutos": 78},
    {"origen": "Guarne", "destino": "Rionegro", "distancia_km": 20.4, "tiempo_minutos": 28},
    {"origen": "Guarne", "destino": "San Vicente Ferrer", "distancia_km": 23.1, "tiempo_minutos": 37},
    {"origen": "Guarne", "destino": "Alejandría", "distancia_km": 63.6, "tiempo_minutos": 105},
    {"origen": "Guarne", "destino": "Concepción", "distancia_km": 46.4, "tiempo_minutos": 74},
    {"origen": "Guarne", "destino": "El Peñol", "distancia_km": 38.4, "tiempo_minutos": 56},
    {"origen": "Guarne", "destino": "Granada", "distancia_km": 44.6, "tiempo_minutos": 55},
    {"origen": "Guarne", "destino": "Guatapé", "distancia_km": 52.6, "tiempo_minutos": 83},
    {"origen": "Guarne", "destino": "San Carlos", "distancia_km": 85.2, "tiempo_minutos": 128},
    {"origen": "Guarne", "destino": "San Rafael", "distancia_km": 79.9, "tiempo_minutos": 127},
    {"origen": "Guarne", "destino": "Sonsón", "distancia_km": 104.0, "tiempo_minutos": 162},
    {"origen": "Guarne", "destino": "Nariño", "distancia_km": 139.0, "tiempo_minutos": 219},
    {"origen": "Guarne", "destino": "Argelia", "distancia_km": 137.0, "tiempo_minutos": 220},
    {"origen": "Guarne", "destino": "Abejorral", "distancia_km": 82.3, "tiempo_minutos": 136},
    {"origen": "Guarne", "destino": "Cocorná", "distancia_km": 52.3, "tiempo_minutos": 69},
    {"origen": "Guarne", "destino": "San Francisco", "distancia_km": 73.0, "tiempo_minutos": 97},
    {"origen": "Guarne", "destino": "San Luis", "distancia_km": 104.0, "tiempo_minutos": 134},
    {"origen": "La Ceja", "destino": "El Carmen de Viboral", "distancia_km": 15.9, "tiempo_minutos": 31},
    {"origen": "La Ceja", "destino": "El Retiro", "distancia_km": 17.3, "tiempo_minutos": 31},
    {"origen": "La Ceja", "destino": "Santuario", "distancia_km": 29.7, "tiempo_minutos": 53},
    {"origen": "La Ceja", "destino": "Guarne", "distancia_km": 33.5, "tiempo_minutos": 55},
    {"origen": "La Ceja", "destino": "Marinilla", "distancia_km": 26.2, "tiempo_minutos": 51},
    {"origen": "La Ceja", "destino": "La Unión", "distancia_km": 14.6, "tiempo_minutos": 28},
    {"origen": "La Ceja", "destino": "Rionegro", "distancia_km": 20.2, "tiempo_minutos": 35},
    {"origen": "La Ceja", "destino": "San Vicente Ferrer", "distancia_km": 43.6, "tiempo_minutos": 77},
    {"origen": "La Ceja", "destino": "Alejandría", "distancia_km": 84.2, "tiempo_minutos": 145},
    {"origen": "La Ceja", "destino": "Concepción", "distancia_km": 66.9, "tiempo_minutos": 114},
    {"origen": "La Ceja", "destino": "El Peñol", "distancia_km": 45.4, "tiempo_minutos": 83},
    {"origen": "La Ceja", "destino": "Granada", "distancia_km": 43.3, "tiempo_minutos": 75},
    {"origen": "La Ceja", "destino": "Guatapé", "distancia_km": 59.7, "tiempo_minutos": 110},
    {"origen": "La Ceja", "destino": "San Carlos", "distancia_km": 83.9, "tiempo_minutos": 147},
    {"origen": "La Ceja", "destino": "San Rafael", "distancia_km": 87.0, "tiempo_minutos": 152},
    {"origen": "La Ceja", "destino": "Sonsón", "distancia_km": 68.0, "tiempo_minutos": 112},
    {"origen": "La Ceja", "destino": "Nariño", "distancia_km": 102.0, "tiempo_minutos": 169},
    {"origen": "La Ceja", "destino": "Argelia", "distancia_km": 101.0, "tiempo_minutos": 170},
    {"origen": "La Ceja", "destino": "Abejorral", "distancia_km": 43.8, "tiempo_minutos": 83},
    {"origen": "La Ceja", "destino": "Cocorná", "distancia_km": 51.0, "tiempo_minutos": 88},
    {"origen": "La Ceja", "destino": "San Francisco", "distancia_km": 71.6, "tiempo_minutos": 119},
    {"origen": "La Ceja", "destino": "San Luis", "distancia_km": 103.0, "tiempo_minutos": 155},
    {"origen": "Marinilla", "destino": "El Carmen de Viboral", "distancia_km": 14.7, "tiempo_minutos": 31},
    {"origen": "Marinilla", "destino": "El Retiro", "distancia_km": 27.9, "tiempo_minutos": 49},
    {"origen": "Marinilla", "destino": "Santuario", "distancia_km": 13.1, "tiempo_minutos": 17},
    {"origen": "Marinilla", "destino": "Guarne", "distancia_km": 19.1, "tiempo_minutos": 22},
    {"origen": "Marinilla", "destino": "La Ceja", "distancia_km": 25.9, "tiempo_minutos": 52},
    {"origen": "Marinilla", "destino": "La Unión", "distancia_km": 37.9, "tiempo_minutos": 69},
    {"origen": "Marinilla", "destino": "Rionegro", "distancia_km": 8.0, "tiempo_minutos": 18},
    {"origen": "Marinilla", "destino": "San Vicente Ferrer", "distancia_km": 23.0, "tiempo_minutos": 37},
    {"origen": "Marinilla", "destino": "Alejandría", "distancia_km": 63.5, "tiempo_minutos": 105},
    {"origen": "Marinilla", "destino": "Concepción", "distancia_km": 46.3, "tiempo_minutos": 75},
    {"origen": "Marinilla", "destino": "El Peñol", "distancia_km": 18.2, "tiempo_minutos": 36},
    {"origen": "Marinilla", "destino": "Granada", "distancia_km": 26.7, "tiempo_minutos": 38},
    {"origen": "Marinilla", "destino": "Guatapé", "distancia_km": 32.5, "tiempo_minutos": 62},
    {"origen": "Marinilla", "destino": "San Carlos", "distancia_km": 67.4, "tiempo_minutos": 111},
    {"origen": "Marinilla", "destino": "San Rafael", "distancia_km": 59.8, "tiempo_minutos": 106},
    {"origen": "Marinilla", "destino": "Sonsón", "distancia_km": 91.3, "tiempo_minutos": 153},
    {"origen": "Marinilla", "destino": "Nariño", "distancia_km": 125.0, "tiempo_minutos": 209},
    {"origen": "Marinilla", "destino": "Argelia", "distancia_km": 124.0, "tiempo_minutos": 210},
    {"origen": "Marinilla", "destino": "Abejorral", "distancia_km": 69.8, "tiempo_minutos": 132},
    {"origen": "Marinilla", "destino": "Cocorná", "distancia_km": 34.5, "tiempo_minutos": 51},
    {"origen": "Marinilla", "destino": "San Francisco", "distancia_km": 55.1, "tiempo_minutos": 82},
    {"origen": "Marinilla", "destino": "San Luis", "distancia_km": 86.4, "tiempo_minutos": 117},
    {"origen": "La Unión", "destino": "El Carmen de Viboral", "distancia_km": 27.2, "tiempo_minutos": 47},
    {"origen": "La Unión", "destino": "El Retiro", "distancia_km": 33.8, "tiempo_minutos": 55},
    {"origen": "La Unión", "destino": "Santuario", "distancia_km": 40.9, "tiempo_minutos": 70},
    {"origen": "La Unión", "destino": "Guarne", "distancia_km": 51.0, "tiempo_minutos": 78},
    {"origen": "La Unión", "destino": "La Ceja", "distancia_km": 14.9, "tiempo_minutos": 29},
    {"origen": "La Unión", "destino": "Marinilla", "distancia_km": 38.0, "tiempo_minutos": 66},
    {"origen": "La Unión", "destino": "Rionegro", "distancia_km": 31.4, "tiempo_minutos": 51},
    {"origen": "La Unión", "destino": "San Vicente Ferrer", "distancia_km": 54.9, "tiempo_minutos": 93},
    {"origen": "La Unión", "destino": "Alejandría", "distancia_km": 95.4, "tiempo_minutos": 160},
    {"origen": "La Unión", "destino": "Concepción", "distancia_km": 78.2, "tiempo_minutos": 130},
    {"origen": "La Unión", "destino": "El Peñol", "distancia_km": 56.7, "tiempo_minutos": 99},
    {"origen": "La Unión", "destino": "Granada", "distancia_km": 54.5, "tiempo_minutos": 91},
    {"origen": "La Unión", "destino": "Guatapé", "distancia_km": 71.0, "tiempo_minutos": 126},
    {"origen": "La Unión", "destino": "San Carlos", "distancia_km": 104.0, "tiempo_minutos": 169},
    {"origen": "La Unión", "destino": "San Rafael", "distancia_km": 98.2, "tiempo_minutos": 167},
    {"origen": "La Unión", "destino": "Sonsón", "distancia_km": 53.6, "tiempo_minutos": 87},
    {"origen": "La Unión", "destino": "Nariño", "distancia_km": 87.6, "tiempo_minutos": 143},
    {"origen": "La Unión", "destino": "Argelia", "distancia_km": 86.4, "tiempo_minutos": 144},
    {"origen": "La Unión", "destino": "Abejorral", "distancia_km": 57.9, "tiempo_minutos": 107},
    {"origen": "La Unión", "destino": "Cocorná", "distancia_km": 62.2, "tiempo_minutos": 105},
    {"origen": "La Unión", "destino": "San Francisco", "distancia_km": 91.3, "tiempo_minutos": 140},
    {"origen": "La Unión", "destino": "San Luis", "distancia_km": 123.0, "tiempo_minutos": 175},
    {"origen": "Rionegro", "destino": "El Carmen de Viboral", "distancia_km": 11.3, "tiempo_minutos": 24},
    {"origen": "Rionegro", "destino": "El Retiro", "distancia_km": 19.9, "tiempo_minutos": 32},
    {"origen": "Rionegro", "destino": "Santuario", "distancia_km": 19.7, "tiempo_minutos": 27},
    {"origen": "Rionegro", "destino": "Guarne", "distancia_km": 21.4, "tiempo_minutos": 28},
    {"origen": "Rionegro", "destino": "La Ceja", "distancia_km": 18.6, "tiempo_minutos": 33},
    {"origen": "Rionegro", "destino": "Marinilla", "distancia_km": 8.4, "tiempo_minutos": 17},
    {"origen": "Rionegro", "destino": "La Unión", "distancia_km": 30.5, "tiempo_minutos": 51},
    {"origen": "Rionegro", "destino": "San Vicente Ferrer", "distancia_km": 25.3, "tiempo_minutos": 43},
    {"origen": "Rionegro", "destino": "Alejandría", "distancia_km": 65.8, "tiempo_minutos": 112},
    {"origen": "Rionegro", "destino": "Concepción", "distancia_km": 48.6, "tiempo_minutos": 81},
    {"origen": "Rionegro", "destino": "El Peñol", "distancia_km": 27.1, "tiempo_minutos": 49},
    {"origen": "Rionegro", "destino": "Granada", "distancia_km": 33.3, "tiempo_minutos": 48},
    {"origen": "Rionegro", "destino": "Guatapé", "distancia_km": 41.4, "tiempo_minutos": 76},
    {"origen": "Rionegro", "destino": "San Carlos", "distancia_km": 74.0, "tiempo_minutos": 121},
    {"origen": "Rionegro", "destino": "San Rafael", "distancia_km": 68.6, "tiempo_minutos": 119},
    {"origen": "Rionegro", "destino": "Sonsón", "distancia_km": 84.0, "tiempo_minutos": 135},
    {"origen": "Rionegro", "destino": "Nariño", "distancia_km": 118.0, "tiempo_minutos": 191},
    {"origen": "Rionegro", "destino": "Argelia", "distancia_km": 117.0, "tiempo_minutos": 192},
    {"origen": "Rionegro", "destino": "Abejorral", "distancia_km": 62.5, "tiempo_minutos": 113},
    {"origen": "Rionegro", "destino": "Cocorná", "distancia_km": 41.0, "tiempo_minutos": 60},
    {"origen": "Rionegro", "destino": "San Francisco", "distancia_km": 61.6, "tiempo_minutos": 91},
    {"origen": "Rionegro", "destino": "San Luis", "distancia_km": 93.0, "tiempo_minutos": 126},
    {"origen": "San Vicente Ferrer", "destino": "El Carmen de Viboral", "distancia_km": 35.4, "tiempo_minutos": 61},
    {"origen": "San Vicente Ferrer", "destino": "El Retiro", "distancia_km": 47.7, "tiempo_minutos": 70},
    {"origen": "San Vicente Ferrer", "destino": "Santuario", "distancia_km": 37.7, "tiempo_minutos": 52},
    {"origen": "San Vicente Ferrer", "destino": "Guarne", "distancia_km": 22.2, "tiempo_minutos": 36},
    {"origen": "San Vicente Ferrer", "destino": "La Ceja", "distancia_km": 45.0, "tiempo_minutos": 78},
    {"origen": "San Vicente Ferrer", "destino": "Marinilla", "distancia_km": 26.4, "tiempo_minutos": 42},
    {"origen": "San Vicente Ferrer", "destino": "La Unión", "distancia_km": 57.8, "tiempo_minutos": 97},
    {"origen": "San Vicente Ferrer", "destino": "Rionegro", "distancia_km": 27.8, "tiempo_minutos": 46},
    {"origen": "San Vicente Ferrer", "destino": "Alejandría", "distancia_km": 40.7, "tiempo_minutos": 70},
    {"origen": "San Vicente Ferrer", "destino": "Concepción", "distancia_km": 23.5, "tiempo_minutos": 39},
    {"origen": "San Vicente Ferrer", "destino": "El Peñol", "distancia_km": 45.1, "tiempo_minutos": 74},
    {"origen": "San Vicente Ferrer", "destino": "Granada", "distancia_km": 51.3, "tiempo_minutos": 73},
    {"origen": "San Vicente Ferrer", "destino": "Guatapé", "distancia_km": 33.4, "tiempo_minutos": 76},
    {"origen": "San Vicente Ferrer", "destino": "San Carlos", "distancia_km": 91.9, "tiempo_minutos": 146},
    {"origen": "San Vicente Ferrer", "destino": "San Rafael", "distancia_km": 60.7, "tiempo_minutos": 121},
    {"origen": "San Vicente Ferrer", "destino": "Sonsón", "distancia_km": 111.0, "tiempo_minutos": 182},
    {"origen": "San Vicente Ferrer", "destino": "Nariño", "distancia_km": 144.0, "tiempo_minutos": 237},
    {"origen": "San Vicente Ferrer", "destino": "Argelia", "distancia_km": 143.0, "tiempo_minutos": 238},
    {"origen": "San Vicente Ferrer", "destino": "Abejorral", "distancia_km": 88.4, "tiempo_minutos": 159},
    {"origen": "San Vicente Ferrer", "destino": "Cocorná", "distancia_km": 59.0, "tiempo_minutos": 86},
    {"origen": "San Vicente Ferrer", "destino": "San Francisco", "distancia_km": 79.7, "tiempo_minutos": 115},
    {"origen": "San Vicente Ferrer", "destino": "San Luis", "distancia_km": 111.0, "tiempo_minutos": 152},
    {"origen": "Alejandría", "destino": "El Carmen de Viboral", "distancia_km": 76.0, "tiempo_minutos": 127},
    {"origen": "Alejandría", "destino": "El Retiro", "distancia_km": 88.4, "tiempo_minutos": 138},
    {"origen": "Alejandría", "destino": "Santuario", "distancia_km": 78.3, "tiempo_minutos": 119},
    {"origen": "Alejandría", "destino": "Guarne", "distancia_km": 62.8, "tiempo_minutos": 104},
    {"origen": "Alejandría", "destino": "La Ceja", "distancia_km": 86.4, "tiempo_minutos": 148},
    {"origen": "Alejandría", "destino": "Marinilla", "distancia_km": 67.0, "tiempo_minutos": 109},
    {"origen": "Alejandría", "destino": "La Unión", "distancia_km": 98.4, "tiempo_minutos": 166},
    {"origen": "Alejandría", "destino": "Rionegro", "distancia_km": 68.5, "tiempo_minutos": 114},
    {"origen": "Alejandría", "destino": "San Vicente Ferrer", "distancia_km": 40.7, "tiempo_minutos": 67},
    {"origen": "Alejandría", "destino": "Concepción", "distancia_km": 17.4, "tiempo_minutos": 31},
    {"origen": "Alejandría", "destino": "El Peñol", "distancia_km": 55.0, "tiempo_minutos": 110},
    {"origen": "Alejandría", "destino": "Granada", "distancia_km": 91.9, "tiempo_minutos": 141},
    {"origen": "Alejandría", "destino": "Guatapé", "distancia_km": 27.0, "tiempo_minutos": 63},
    {"origen": "Alejandría", "destino": "San Carlos", "distancia_km": 68.1, "tiempo_minutos": 121},
    {"origen": "Alejandría", "destino": "San Rafael", "distancia_km": 24.4, "tiempo_minutos": 58},
    {"origen": "Alejandría", "destino": "Sonsón", "distancia_km": 152.0, "tiempo_minutos": 251},
    {"origen": "Alejandría", "destino": "Nariño", "distancia_km": 186.0, "tiempo_minutos": 307},
    {"origen": "Alejandría", "destino": "Argelia", "distancia_km": 185.0, "tiempo_minutos": 308},
    {"origen": "Alejandría", "destino": "Abejorral", "distancia_km": 130.0, "tiempo_minutos": 227},
    {"origen": "Alejandría", "destino": "Cocorná", "distancia_km": 99.6, "tiempo_minutos": 152},
    {"origen": "Alejandría", "destino": "San Francisco", "distancia_km": 120.0, "tiempo_minutos": 184},
    {"origen": "Alejandría", "destino": "San Luis", "distancia_km": 98.5, "tiempo_minutos": 213},
    {"origen": "Concepción", "destino": "El Carmen de Viboral", "distancia_km": 58.8, "tiempo_minutos": 99},
    {"origen": "Concepción", "destino": "El Retiro", "distancia_km": 71.1, "tiempo_minutos": 109},
    {"origen": "Concepción", "destino": "Santuario", "distancia_km": 61.1, "tiempo_minutos": 91},
    {"origen": "Concepción", "destino": "Guarne", "distancia_km": 45.6, "tiempo_minutos": 75},
    {"origen": "Concepción", "destino": "La Ceja", "distancia_km": 69.2, "tiempo_minutos": 120},
    {"origen": "Concepción", "destino": "Marinilla", "distancia_km": 49.8, "tiempo_minutos": 80},
    {"origen": "Concepción", "destino": "La Unión", "distancia_km": 81.2, "tiempo_minutos": 137},
    {"origen": "Concepción", "destino": "Rionegro", "distancia_km": 51.2, "tiempo_minutos": 85},
    {"origen": "Concepción", "destino": "San Vicente Ferrer", "distancia_km": 23.5, "tiempo_minutos": 39},
    {"origen": "Concepción", "destino": "Alejandría", "distancia_km": 17.4, "tiempo_minutos": 33},
    {"origen": "Concepción", "destino": "El Peñol", "distancia_km": 68.5, "tiempo_minutos": 113},
    {"origen": "Concepción", "destino": "Granada", "distancia_km": 74.7, "tiempo_minutos": 112},
    {"origen": "Concepción", "destino": "Guatapé", "distancia_km": 82.8, "tiempo_minutos": 140},
    {"origen": "Concepción", "destino": "San Carlos", "distancia_km": 85.4, "tiempo_minutos": 154},
    {"origen": "Concepción", "destino": "San Rafael", "distancia_km": 41.8, "tiempo_minutos": 92},
    {"origen": "Concepción", "destino": "Sonsón", "distancia_km": 135.0, "tiempo_minutos": 223},
    {"origen": "Concepción", "destino": "Nariño", "distancia_km": 169.0, "tiempo_minutos": 279},
    {"origen": "Concepción", "destino": "Argelia", "distancia_km": 167.0, "tiempo_minutos": 280},
    {"origen": "Concepción", "destino": "Abejorral", "distancia_km": 121.0, "tiempo_minutos": 198},
    {"origen": "Concepción", "destino": "Cocorná", "distancia_km": 82.4, "tiempo_minutos": 125},
    {"origen": "Concepción", "destino": "San Francisco", "distancia_km": 103.0, "tiempo_minutos": 154},
    {"origen": "Concepción", "destino": "San Luis", "distancia_km": 134.0, "tiempo_minutos": 189},
    {"origen": "El Peñol", "destino": "El Carmen de Viboral", "distancia_km": 33.3, "tiempo_minutos": 63},
    {"origen": "El Peñol", "destino": "El Retiro", "distancia_km": 46.4, "tiempo_minutos": 83},
    {"origen": "El Peñol", "destino": "Santuario", "distancia_km": 29.4, "tiempo_minutos": 47},
    {"origen": "El Peñol", "destino": "Guarne", "distancia_km": 37.6, "tiempo_minutos": 55},
    {"origen": "El Peñol", "destino": "La Ceja", "distancia_km": 44.5, "tiempo_minutos": 84},
    {"origen": "El Peñol", "destino": "Marinilla", "distancia_km": 18.3, "tiempo_minutos": 35},
    {"origen": "El Peñol", "destino": "La Unión", "distancia_km": 56.4, "tiempo_minutos": 102},
    {"origen": "El Peñol", "destino": "Rionegro", "distancia_km": 26.5, "tiempo_minutos": 51},
    {"origen": "El Peñol", "destino": "San Vicente Ferrer", "distancia_km": 41.5, "tiempo_minutos": 70},
    {"origen": "El Peñol", "destino": "Alejandría", "distancia_km": 55.2, "tiempo_minutos": 110},
    {"origen": "El Peñol", "destino": "Concepción", "distancia_km": 64.8, "tiempo_minutos": 108},
    {"origen": "El Peñol", "destino": "Granada", "distancia_km": 30.5, "tiempo_minutos": 67},
    {"origen": "El Peñol", "destino": "Guatapé", "distancia_km": 14.8, "tiempo_minutos": 29},
    {"origen": "El Peñol", "destino": "San Carlos", "distancia_km": 57.0, "tiempo_minutos": 107},
    {"origen": "El Peñol", "destino": "San Rafael", "distancia_km": 42.1, "tiempo_minutos": 73},
    {"origen": "El Peñol", "destino": "Sonsón", "distancia_km": 110.0, "tiempo_minutos": 187},
    {"origen": "El Peñol", "destino": "Nariño", "distancia_km": 144.0, "tiempo_minutos": 243},
    {"origen": "El Peñol", "destino": "Argelia", "distancia_km": 143.0, "tiempo_minutos": 244},
    {"origen": "El Peñol", "destino": "Abejorral", "distancia_km": 87.9, "tiempo_minutos": 165},
    {"origen": "El Peñol", "destino": "Cocorná", "distancia_km": 50.7, "tiempo_minutos": 81},
    {"origen": "El Peñol", "destino": "San Francisco", "distancia_km": 71.3, "tiempo_minutos": 112},
    {"origen": "El Peñol", "destino": "San Luis", "distancia_km": 103.0, "tiempo_minutos": 149},
    {"origen": "Granada", "destino": "El Carmen de Viboral", "distancia_km": 30.3, "tiempo_minutos": 51},
    {"origen": "Granada", "destino": "El Retiro", "distancia_km": 53.4, "tiempo_minutos": 83},
    {"origen": "Granada", "destino": "Santuario", "distancia_km": 14.8, "tiempo_minutos": 24},
    {"origen": "Granada", "destino": "Guarne", "distancia_km": 44.5, "tiempo_minutos": 56},
    {"origen": "Granada", "destino": "La Ceja", "distancia_km": 51.4, "tiempo_minutos": 85},
    {"origen": "Granada", "destino": "Marinilla", "distancia_km": 25.7, "tiempo_minutos": 38},
    {"origen": "Granada", "destino": "La Unión", "distancia_km": 63.4, "tiempo_minutos": 102},
    {"origen": "Granada", "destino": "Rionegro", "distancia_km": 33.4, "tiempo_minutos": 51},
    {"origen": "Granada", "destino": "San Vicente Ferrer", "distancia_km": 48.4, "tiempo_minutos": 71},
    {"origen": "Granada", "destino": "Alejandría", "distancia_km": 88.9, "tiempo_minutos": 139},
    {"origen": "Granada", "destino": "Concepción", "distancia_km": 71.7, "tiempo_minutos": 108},
    {"origen": "Granada", "destino": "El Peñol", "distancia_km": 42.3, "tiempo_minutos": 67},
    {"origen": "Granada", "destino": "Guatapé", "distancia_km": 22.7, "tiempo_minutos": 57},
    {"origen": "Granada", "destino": "San Carlos", "distancia_km": 40.8, "tiempo_minutos": 75},
    {"origen": "Granada", "destino": "San Rafael", "distancia_km": 50.0, "tiempo_minutos": 101},
    {"origen": "Granada", "destino": "Sonsón", "distancia_km": 117.0, "tiempo_minutos": 188},
    {"origen": "Granada", "destino": "Nariño", "distancia_km": 151.0, "tiempo_minutos": 243},
    {"origen": "Granada", "destino": "Argelia", "distancia_km": 150.0, "tiempo_minutos": 245},
    {"origen": "Granada", "destino": "Abejorral", "distancia_km": 94.8, "tiempo_minutos": 166},
    {"origen": "Granada", "destino": "Cocorná", "distancia_km": 33.1, "tiempo_minutos": 55},
    {"origen": "Granada", "destino": "San Francisco", "distancia_km": 53.7, "tiempo_minutos": 87},
    {"origen": "Granada", "destino": "San Luis", "distancia_km": 49.7, "tiempo_minutos": 119},
    {"origen": "Guatapé", "destino": "El Carmen de Viboral", "distancia_km": 47.4, "tiempo_minutos": 91},
    {"origen": "Guatapé", "destino": "El Retiro", "distancia_km": 60.7, "tiempo_minutos": 114},
    {"origen": "Guatapé", "destino": "Santuario", "distancia_km": 43.5, "tiempo_minutos": 75},
    {"origen": "Guatapé", "destino": "Guarne", "distancia_km": 51.7, "tiempo_minutos": 83},
    {"origen": "Guatapé", "destino": "La Ceja", "distancia_km": 58.6, "tiempo_minutos": 114},
    {"origen": "Guatapé", "destino": "Marinilla", "distancia_km": 32.4, "tiempo_minutos": 64},
    {"origen": "Guatapé", "destino": "La Unión", "distancia_km": 70.5, "tiempo_minutos": 131},
    {"origen": "Guatapé", "destino": "Rionegro", "distancia_km": 40.6, "tiempo_minutos": 79},
    {"origen": "Guatapé", "destino": "San Vicente Ferrer", "distancia_km": 55.6, "tiempo_minutos": 98},
    {"origen": "Guatapé", "destino": "Alejandría", "distancia_km": 40.6, "tiempo_minutos": 82},
    {"origen": "Guatapé", "destino": "Concepción", "distancia_km": 78.9, "tiempo_minutos": 135},
    {"origen": "Guatapé", "destino": "El Peñol", "distancia_km": 14.4, "tiempo_minutos": 29},
    {"origen": "Guatapé", "destino": "Granada", "distancia_km": 22.6, "tiempo_minutos": 56},
    {"origen": "Guatapé", "destino": "San Carlos", "distancia_km": 71.1, "tiempo_minutos": 108},
    {"origen": "Guatapé", "destino": "San Rafael", "distancia_km": 27.5, "tiempo_minutos": 45},
    {"origen": "Guatapé", "destino": "Sonsón", "distancia_km": 124.0, "tiempo_minutos": 216},
    {"origen": "Guatapé", "destino": "Nariño", "distancia_km": 158.0, "tiempo_minutos": 272},
    {"origen": "Guatapé", "destino": "Argelia", "distancia_km": 157.0, "tiempo_minutos": 273},
    {"origen": "Guatapé", "destino": "Abejorral", "distancia_km": 102.0, "tiempo_minutos": 193},
    {"origen": "Guatapé", "destino": "Cocorná", "distancia_km": 64.8, "tiempo_minutos": 109},
    {"origen": "Guatapé", "destino": "San Francisco", "distancia_km": 85.5, "tiempo_minutos": 138},
    {"origen": "Guatapé", "destino": "San Luis", "distancia_km": 57.9, "tiempo_minutos": 143},
    {"origen": "San Carlos", "destino": "El Carmen de Viboral", "distancia_km": 71.1, "tiempo_minutos": 124},
    {"origen": "San Carlos", "destino": "El Retiro", "distancia_km": 94.3, "tiempo_minutos": 158},
    {"origen": "San Carlos", "destino": "Santuario", "distancia_km": 55.6, "tiempo_minutos": 97},
    {"origen": "San Carlos", "destino": "Guarne", "distancia_km": 85.3, "tiempo_minutos": 129},
    {"origen": "San Carlos", "destino": "La Ceja", "distancia_km": 92.2, "tiempo_minutos": 159},
    {"origen": "San Carlos", "destino": "Marinilla", "distancia_km": 66.5, "tiempo_minutos": 112},
    {"origen": "San Carlos", "destino": "La Unión", "distancia_km": 104.0, "tiempo_minutos": 176},
    {"origen": "San Carlos", "destino": "Rionegro", "distancia_km": 74.3, "tiempo_minutos": 124},
    {"origen": "San Carlos", "destino": "San Vicente Ferrer", "distancia_km": 89.2, "tiempo_minutos": 144},
    {"origen": "San Carlos", "destino": "Alejandría", "distancia_km": 68.2, "tiempo_minutos": 122},
    {"origen": "San Carlos", "destino": "Concepción", "distancia_km": 85.6, "tiempo_minutos": 153},
    {"origen": "San Carlos", "destino": "El Peñol", "distancia_km": 56.9, "tiempo_minutos": 108},
    {"origen": "San Carlos", "destino": "Granada", "distancia_km": 41.0, "tiempo_minutos": 74},
    {"origen": "San Carlos", "destino": "Guatapé", "distancia_km": 49.4, "tiempo_minutos": 97},
    {"origen": "San Carlos", "destino": "San Rafael", "distancia_km": 43.8, "tiempo_minutos": 64},
    {"origen": "San Carlos", "destino": "Sonsón", "distancia_km": 158.0, "tiempo_minutos": 261},
    {"origen": "San Carlos", "destino": "Nariño", "distancia_km": 192.0, "tiempo_minutos": 317},
    {"origen": "San Carlos", "destino": "Argelia", "distancia_km": 190.0, "tiempo_minutos": 318},
    {"origen": "San Carlos", "destino": "Abejorral", "distancia_km": 136.0, "tiempo_minutos": 238},
    {"origen": "San Carlos", "destino": "Cocorná", "distancia_km": 74.0, "tiempo_minutos": 128},
    {"origen": "San Carlos", "destino": "San Francisco", "distancia_km": 94.6, "tiempo_minutos": 160},
    {"origen": "San Carlos", "destino": "San Luis", "distancia_km": 33.5, "tiempo_minutos": 91},
    {"origen": "San Rafael", "destino": "El Carmen de Viboral", "distancia_km": 75.0, "tiempo_minutos": 135},
    {"origen": "San Rafael", "destino": "El Retiro", "distancia_km": 88.2, "tiempo_minutos": 157},
    {"origen": "San Rafael", "destino": "Santuario", "distancia_km": 71.1, "tiempo_minutos": 119},
    {"origen": "San Rafael", "destino": "Guarne", "distancia_km": 79.3, "tiempo_minutos": 128},
    {"origen": "San Rafael", "destino": "La Ceja", "distancia_km": 86.2, "tiempo_minutos": 157},
    {"origen": "San Rafael", "destino": "Marinilla", "distancia_km": 59.9, "tiempo_minutos": 109},
    {"origen": "San Rafael", "destino": "La Unión", "distancia_km": 98.1, "tiempo_minutos": 174},
    {"origen": "San Rafael", "destino": "Rionegro", "distancia_km": 68.2, "tiempo_minutos": 123},
    {"origen": "San Rafael", "destino": "San Vicente Ferrer", "distancia_km": 60.9, "tiempo_minutos": 121},
    {"origen": "San Rafael", "destino": "Alejandría", "distancia_km": 24.6, "tiempo_minutos": 59},
    {"origen": "San Rafael", "destino": "Concepción", "distancia_km": 41.9, "tiempo_minutos": 89},
    {"origen": "San Rafael", "destino": "El Peñol", "distancia_km": 42.0, "tiempo_minutos": 74},
    {"origen": "San Rafael", "destino": "Granada", "distancia_km": 50.1, "tiempo_minutos": 100},
    {"origen": "San Rafael", "destino": "Guatapé", "distancia_km": 27.6, "tiempo_minutos": 45},
    {"origen": "San Rafael", "destino": "San Carlos", "distancia_km": 43.6, "tiempo_minutos": 63},
    {"origen": "San Rafael", "destino": "Sonsón", "distancia_km": 152.0, "tiempo_minutos": 260},
    {"origen": "San Rafael", "destino": "Nariño", "distancia_km": 186.0, "tiempo_minutos": 316},
    {"origen": "San Rafael", "destino": "Argelia", "distancia_km": 184.0, "tiempo_minutos": 317},
    {"origen": "San Rafael", "destino": "Abejorral", "distancia_km": 130.0, "tiempo_minutos": 236},
    {"origen": "San Rafael", "destino": "Cocorná", "distancia_km": 92.4, "tiempo_minutos": 152},
    {"origen": "San Rafael", "destino": "San Francisco", "distancia_km": 113.0, "tiempo_minutos": 182},
    {"origen": "San Rafael", "destino": "San Luis", "distancia_km": 76.7, "tiempo_minutos": 151},
    {"origen": "Sonsón", "destino": "El Carmen de Viboral", "distancia_km": 81.0, "tiempo_minutos": 134},
    {"origen": "Sonsón", "destino": "El Retiro", "distancia_km": 87.7, "tiempo_minutos": 142},
    {"origen": "Sonsón", "destino": "Santuario", "distancia_km": 103.0, "tiempo_minutos": 163},
    {"origen": "Sonsón", "destino": "Guarne", "distancia_km": 105.0, "tiempo_minutos": 165},
    {"origen": "Sonsón", "destino": "La Ceja", "distancia_km": 68.8, "tiempo_minutos": 116},
    {"origen": "Sonsón", "destino": "Marinilla", "distancia_km": 91.8, "tiempo_minutos": 152},
    {"origen": "Sonsón", "destino": "La Unión", "distancia_km": 53.9, "tiempo_minutos": 87},
    {"origen": "Sonsón", "destino": "Rionegro", "distancia_km": 84.0, "tiempo_minutos": 140},
    {"origen": "Sonsón", "destino": "San Vicente Ferrer", "distancia_km": 109.0, "tiempo_minutos": 178},
    {"origen": "Sonsón", "destino": "Alejandría", "distancia_km": 149.0, "tiempo_minutos": 247},
    {"origen": "Sonsón", "destino": "Concepción", "distancia_km": 132.0, "tiempo_minutos": 217},
    {"origen": "Sonsón", "destino": "El Peñol", "distancia_km": 111.0, "tiempo_minutos": 183},
    {"origen": "Sonsón", "destino": "Granada", "distancia_km": 117.0, "tiempo_minutos": 184},
    {"origen": "Sonsón", "destino": "Guatapé", "distancia_km": 125.0, "tiempo_minutos": 208},
    {"origen": "Sonsón", "destino": "San Carlos", "distancia_km": 157.0, "tiempo_minutos": 256},
    {"origen": "Sonsón", "destino": "San Rafael", "distancia_km": 152.0, "tiempo_minutos": 249},
    {"origen": "Sonsón", "destino": "Nariño", "distancia_km": 34.4, "tiempo_minutos": 59},
    {"origen": "Sonsón", "destino": "Argelia", "distancia_km": 33.2, "tiempo_minutos": 59},
    {"origen": "Sonsón", "destino": "Abejorral", "distancia_km": 47.8, "tiempo_minutos": 112},
    {"origen": "Sonsón", "destino": "Cocorná", "distancia_km": 124.0, "tiempo_minutos": 195},
    {"origen": "Sonsón", "destino": "San Francisco", "distancia_km": 145.0, "tiempo_minutos": 226},
    {"origen": "Sonsón", "destino": "San Luis", "distancia_km": 176.0, "tiempo_minutos": 263},
    {"origen": "Nariño", "destino": "El Carmen de Viboral", "distancia_km": 115.0, "tiempo_minutos": 192},
    {"origen": "Nariño", "destino": "El Retiro", "distancia_km": 122.0, "tiempo_minutos": 201},
    {"origen": "Nariño", "destino": "Santuario", "distancia_km": 137.0, "tiempo_minutos": 222},
    {"origen": "Nariño", "destino": "Guarne", "distancia_km": 139.0, "tiempo_minutos": 224},
    {"origen": "Nariño", "destino": "La Ceja", "distancia_km": 103.0, "tiempo_minutos": 174},
    {"origen": "Nariño", "destino": "Marinilla", "distancia_km": 126.0, "tiempo_minutos": 211},
    {"origen": "Nariño", "destino": "La Unión", "distancia_km": 88.1, "tiempo_minutos": 145},
    {"origen": "Nariño", "destino": "Rionegro", "distancia_km": 118.0, "tiempo_minutos": 197},
    {"origen": "Nariño", "destino": "San Vicente Ferrer", "distancia_km": 143.0, "tiempo_minutos": 237},
    {"origen": "Nariño", "destino": "Alejandría", "distancia_km": 183.0, "tiempo_minutos": 305},
    {"origen": "Nariño", "destino": "Concepción", "distancia_km": 166.0, "tiempo_minutos": 275},
    {"origen": "Nariño", "destino": "El Peñol", "distancia_km": 145.0, "tiempo_minutos": 243},
    {"origen": "Nariño", "destino": "Granada", "distancia_km": 151.0, "tiempo_minutos": 242},
    {"origen": "Nariño", "destino": "Guatapé", "distancia_km": 159.0, "tiempo_minutos": 269},
    {"origen": "Nariño", "destino": "San Carlos", "distancia_km": 192.0, "tiempo_minutos": 314},
    {"origen": "Nariño", "destino": "San Rafael", "distancia_km": 186.0, "tiempo_minutos": 311},
    {"origen": "Nariño", "destino": "Sonsón", "distancia_km": 34.4, "tiempo_minutos": 59},
    {"origen": "Nariño", "destino": "Argelia", "distancia_km": 37.6, "tiempo_minutos": 67},
    {"origen": "Nariño", "destino": "Abejorral", "distancia_km": 82.0, "tiempo_minutos": 170},
    {"origen": "Nariño", "destino": "Cocorná", "distancia_km": 159.0, "tiempo_minutos": 254},
    {"origen": "Nariño", "destino": "San Francisco", "distancia_km": 179.0, "tiempo_minutos": 285},
    {"origen": "Nariño", "destino": "San Luis", "distancia_km": 211.0, "tiempo_minutos": 324},
    {"origen": "Argelia", "destino": "El Carmen de Viboral", "distancia_km": 114.0, "tiempo_minutos": 194},
    {"origen": "Argelia", "destino": "El Retiro", "distancia_km": 121.0, "tiempo_minutos": 203},
    {"origen": "Argelia", "destino": "Santuario", "distancia_km": 136.0, "tiempo_minutos": 223},
    {"origen": "Argelia", "destino": "Guarne", "distancia_km": 138.0, "tiempo_minutos": 225},
    {"origen": "Argelia", "destino": "La Ceja", "distancia_km": 102.0, "tiempo_minutos": 176},
    {"origen": "Argelia", "destino": "Marinilla", "distancia_km": 125.0, "tiempo_minutos": 213},
    {"origen": "Argelia", "destino": "La Unión", "distancia_km": 87.2, "tiempo_minutos": 147},
    {"origen": "Argelia", "destino": "Rionegro", "distancia_km": 117.0, "tiempo_minutos": 199},
    {"origen": "Argelia", "destino": "San Vicente Ferrer", "distancia_km": 142.0, "tiempo_minutos": 239},
    {"origen": "Argelia", "destino": "Alejandría", "distancia_km": 183.0, "tiempo_minutos": 307},
    {"origen": "Argelia", "destino": "Concepción", "distancia_km": 165.0, "tiempo_minutos": 277},
    {"origen": "Argelia", "destino": "El Peñol", "distancia_km": 144.0, "tiempo_minutos": 244},
    {"origen": "Argelia", "destino": "Granada", "distancia_km": 150.0, "tiempo_minutos": 244},
    {"origen": "Argelia", "destino": "Guatapé", "distancia_km": 158.0, "tiempo_minutos": 270},
    {"origen": "Argelia", "destino": "San Carlos", "distancia_km": 191.0, "tiempo_minutos": 316},
    {"origen": "Argelia", "destino": "San Rafael", "distancia_km": 185.0, "tiempo_minutos": 313},
    {"origen": "Argelia", "destino": "Sonsón", "distancia_km": 33.5, "tiempo_minutos": 60},
    {"origen": "Argelia", "destino": "Nariño", "distancia_km": 37.9, "tiempo_minutos": 68},
    {"origen": "Argelia", "destino": "Abejorral", "distancia_km": 81.1, "tiempo_minutos": 172},
    {"origen": "Argelia", "destino": "Cocorná", "distancia_km": 158.0, "tiempo_minutos": 255},
    {"origen": "Argelia", "destino": "San Francisco", "distancia_km": 178.0, "tiempo_minutos": 288},
    {"origen": "Argelia", "destino": "San Luis", "distancia_km": 210.0, "tiempo_minutos": 326},
    {"origen": "Abejorral", "destino": "El Carmen de Viboral", "distancia_km": 59.3, "tiempo_minutos": 112},
    {"origen": "Abejorral", "destino": "El Retiro", "distancia_km": 58.5, "tiempo_minutos": 107},
    {"origen": "Abejorral", "destino": "Santuario", "distancia_km": 72.5, "tiempo_minutos": 135},
    {"origen": "Abejorral", "destino": "Guarne", "distancia_km": 76.9, "tiempo_minutos": 139},
    {"origen": "Abejorral", "destino": "La Ceja", "distancia_km": 43.5, "tiempo_minutos": 83},
    {"origen": "Abejorral", "destino": "Marinilla", "distancia_km": 70.2, "tiempo_minutos": 130},
    {"origen": "Abejorral", "destino": "La Unión", "distancia_km": 58.0, "tiempo_minutos": 108},
    {"origen": "Abejorral", "destino": "Rionegro", "distancia_km": 62.4, "tiempo_minutos": 118},
    {"origen": "Abejorral", "destino": "San Vicente Ferrer", "distancia_km": 87.1, "tiempo_minutos": 156},
    {"origen": "Abejorral", "destino": "Alejandría", "distancia_km": 127.0, "tiempo_minutos": 225},
    {"origen": "Abejorral", "destino": "Concepción", "distancia_km": 110.0, "tiempo_minutos": 195},
    {"origen": "Abejorral", "destino": "El Peñol", "distancia_km": 88.8, "tiempo_minutos": 161},
    {"origen": "Abejorral", "destino": "Granada", "distancia_km": 95.1, "tiempo_minutos": 162},
    {"origen": "Abejorral", "destino": "Guatapé", "distancia_km": 103.0, "tiempo_minutos": 187},
    {"origen": "Abejorral", "destino": "San Carlos", "distancia_km": 136.0, "tiempo_minutos": 232},
    {"origen": "Abejorral", "destino": "San Rafael", "distancia_km": 130.0, "tiempo_minutos": 228},
    {"origen": "Abejorral", "destino": "Sonsón", "distancia_km": 47.5, "tiempo_minutos": 112},
    {"origen": "Abejorral", "destino": "Nariño", "distancia_km": 81.6, "tiempo_minutos": 168},
    {"origen": "Abejorral", "destino": "Argelia", "distancia_km": 80.4, "tiempo_minutos": 169},
    {"origen": "Abejorral", "destino": "Cocorná", "distancia_km": 103.0, "tiempo_minutos": 173},
    {"origen": "Abejorral", "destino": "San Francisco", "distancia_km": 123.0, "tiempo_minutos": 204},
    {"origen": "Abejorral", "destino": "San Luis", "distancia_km": 154.0, "tiempo_minutos": 241},
    {"origen": "Cocorná", "destino": "El Carmen de Viboral", "distancia_km": 38.1, "tiempo_minutos": 69},
    {"origen": "Cocorná", "destino": "El Retiro", "distancia_km": 61.3, "tiempo_minutos": 104},
    {"origen": "Cocorná", "destino": "Santuario", "distancia_km": 22.7, "tiempo_minutos": 42},
    {"origen": "Cocorná", "destino": "Guarne", "distancia_km": 52.3, "tiempo_minutos": 74},
    {"origen": "Cocorná", "destino": "La Ceja", "distancia_km": 59.2, "tiempo_minutos": 103},
    {"origen": "Cocorná", "destino": "Marinilla", "distancia_km": 33.5, "tiempo_minutos": 56},
    {"origen": "Cocorná", "destino": "La Unión", "distancia_km": 71.2, "tiempo_minutos": 121},
    {"origen": "Cocorná", "destino": "Rionegro", "distancia_km": 41.3, "tiempo_minutos": 70},
    {"origen": "Cocorná", "destino": "San Vicente Ferrer", "distancia_km": 56.2, "tiempo_minutos": 89},
    {"origen": "Cocorná", "destino": "Alejandría", "distancia_km": 96.8, "tiempo_minutos": 156},
    {"origen": "Cocorná", "destino": "Concepción", "distancia_km": 79.5, "tiempo_minutos": 126},
    {"origen": "Cocorná", "destino": "El Peñol", "distancia_km": 50.1, "tiempo_minutos": 85},
    {"origen": "Cocorná", "destino": "Granada", "distancia_km": 33.3, "tiempo_minutos": 60},
    {"origen": "Cocorná", "destino": "Guatapé", "distancia_km": 64.4, "tiempo_minutos": 113},
    {"origen": "Cocorná", "destino": "San Carlos", "distancia_km": 73.9, "tiempo_minutos": 133},
    {"origen": "Cocorná", "destino": "San Rafael", "distancia_km": 91.7, "tiempo_minutos": 154},
    {"origen": "Cocorná", "destino": "Sonsón", "distancia_km": 125.0, "tiempo_minutos": 205},
    {"origen": "Cocorná", "destino": "Nariño", "distancia_km": 159.0, "tiempo_minutos": 261},
    {"origen": "Cocorná", "destino": "Argelia", "distancia_km": 158.0, "tiempo_minutos": 262},
    {"origen": "Cocorná", "destino": "Abejorral", "distancia_km": 103.0, "tiempo_minutos": 183},
    {"origen": "Cocorná", "destino": "San Francisco", "distancia_km": 35.0, "tiempo_minutos": 62},
    {"origen": "Cocorná", "destino": "San Luis", "distancia_km": 66.3, "tiempo_minutos": 98},
    {"origen": "San Francisco", "destino": "El Carmen de Viboral", "distancia_km": 58.6, "tiempo_minutos": 100},
    {"origen": "San Francisco", "destino": "El Retiro", "distancia_km": 81.8, "tiempo_minutos": 135},
    {"origen": "San Francisco", "destino": "Santuario", "distancia_km": 43.1, "tiempo_minutos": 74},
    {"origen": "San Francisco", "destino": "Guarne", "distancia_km": 72.8, "tiempo_minutos": 106},
    {"origen": "San Francisco", "destino": "La Ceja", "distancia_km": 79.7, "tiempo_minutos": 135},
    {"origen": "San Francisco", "destino": "Marinilla", "distancia_km": 54.0, "tiempo_minutos": 88},
    {"origen": "San Francisco", "destino": "La Unión", "distancia_km": 91.7, "tiempo_minutos": 152},
    {"origen": "San Francisco", "destino": "Rionegro", "distancia_km": 61.8, "tiempo_minutos": 101},
    {"origen": "San Francisco", "destino": "San Vicente Ferrer", "distancia_km": 76.7, "tiempo_minutos": 121},
    {"origen": "San Francisco", "destino": "Alejandría", "distancia_km": 117.0, "tiempo_minutos": 189},
    {"origen": "San Francisco", "destino": "Concepción", "distancia_km": 100.0, "tiempo_minutos": 159},
    {"origen": "San Francisco", "destino": "El Peñol", "distancia_km": 70.6, "tiempo_minutos": 116},
    {"origen": "San Francisco", "destino": "Granada", "distancia_km": 53.7, "tiempo_minutos": 92},
    {"origen": "San Francisco", "destino": "Guatapé", "distancia_km": 84.9, "tiempo_minutos": 143},
    {"origen": "San Francisco", "destino": "San Carlos", "distancia_km": 94.4, "tiempo_minutos": 163},
    {"origen": "San Francisco", "destino": "San Rafael", "distancia_km": 112.0, "tiempo_minutos": 185},
    {"origen": "San Francisco", "destino": "Sonsón", "distancia_km": 145.0, "tiempo_minutos": 237},
    {"origen": "San Francisco", "destino": "Nariño", "distancia_km": 179.0, "tiempo_minutos": 292},
    {"origen": "San Francisco", "destino": "Argelia", "distancia_km": 178.0, "tiempo_minutos": 294},
    {"origen": "San Francisco", "destino": "Abejorral", "distancia_km": 123.0, "tiempo_minutos": 214},
    {"origen": "San Francisco", "destino": "Cocorná", "distancia_km": 34.9, "tiempo_minutos": 62},
    {"origen": "San Francisco", "destino": "San Luis", "distancia_km": 49.9, "tiempo_minutos": 90},
    {"origen": "San Luis", "destino": "El Carmen de Viboral", "distancia_km": 89.7, "tiempo_minutos": 140},
    {"origen": "San Luis", "destino": "El Retiro", "distancia_km": 113.0, "tiempo_minutos": 174},
    {"origen": "San Luis", "destino": "Santuario", "distancia_km": 74.2, "tiempo_minutos": 114},
    {"origen": "San Luis", "destino": "Guarne", "distancia_km": 104.0, "tiempo_minutos": 147},
    {"origen": "San Luis", "destino": "La Ceja", "distancia_km": 111.0, "tiempo_minutos": 174},
    {"origen": "San Luis", "destino": "Marinilla", "distancia_km": 85.0, "tiempo_minutos": 129},
    {"origen": "San Luis", "destino": "La Unión", "distancia_km": 123.0, "tiempo_minutos": 191},
    {"origen": "San Luis", "destino": "Rionegro", "distancia_km": 92.8, "tiempo_minutos": 141},
    {"origen": "San Luis", "destino": "San Vicente Ferrer", "distancia_km": 108.0, "tiempo_minutos": 161},
    {"origen": "San Luis", "destino": "Alejandría", "distancia_km": 98.5, "tiempo_minutos": 210},
    {"origen": "San Luis", "destino": "Concepción", "distancia_km": 131.0, "tiempo_minutos": 199},
    {"origen": "San Luis", "destino": "El Peñol", "distancia_km": 65.6, "tiempo_minutos": 152},
    {"origen": "San Luis", "destino": "Granada", "distancia_km": 49.7, "tiempo_minutos": 119},
    {"origen": "San Luis", "destino": "Guatapé", "distancia_km": 58.1, "tiempo_minutos": 143},
    {"origen": "San Luis", "destino": "San Carlos", "distancia_km": 33.4, "tiempo_minutos": 92},
    {"origen": "San Luis", "destino": "San Rafael", "distancia_km": 76.8, "tiempo_minutos": 152},
    {"origen": "San Luis", "destino": "Sonsón", "distancia_km": 176.0, "tiempo_minutos": 275},
    {"origen": "San Luis", "destino": "Nariño", "distancia_km": 210.0, "tiempo_minutos": 331},
    {"origen": "San Luis", "destino": "Argelia", "distancia_km": 209.0, "tiempo_minutos": 332},
    {"origen": "San Luis", "destino": "Abejorral", "distancia_km": 154.0, "tiempo_minutos": 253},
    {"origen": "San Luis", "destino": "Cocorná", "distancia_km": 65.9, "tiempo_minutos": 103},
    {"origen": "San Luis", "destino": "San Francisco", "distancia_km": 49.6, "tiempo_minutos": 93},
]
