"""
Datos de matriz de desplazamientos - Suroeste Antioqueño
Generado automáticamente desde MatrizRutasSuroeste_Homologada.xlsx
"""

MUNICIPIOS = [
    {'nombre': 'Amagá', 'departamento': 'Antioquia'},
    {'nombre': 'Andes', 'departamento': 'Antioquia'},
    {'nombre': 'Angelópolis', 'departamento': 'Antioquia'},
    {'nombre': 'Betania', 'departamento': 'Antioquia'},
    {'nombre': 'Betulia', 'departamento': 'Antioquia'},
    {'nombre': 'Caramanta', 'departamento': 'Antioquia'},
    {'nombre': 'Carmen de Atrato', 'departamento': 'Chocó'},
    {'nombre': 'Ciudad Bolívar', 'departamento': 'Antioquia'},
    {'nombre': 'Concordia', 'departamento': 'Antioquia'},
    {'nombre': 'Fredonia', 'departamento': 'Antioquia'},
    {'nombre': 'Hispania', 'departamento': 'Antioquia'},
    {'nombre': 'Jardín', 'departamento': 'Antioquia'},
    {'nombre': 'Jericó', 'departamento': 'Antioquia'},
    {'nombre': 'La Pintada', 'departamento': 'Antioquia'},
    {'nombre': 'Montebello', 'departamento': 'Antioquia'},
    {'nombre': 'Pueblorrico', 'departamento': 'Antioquia'},
    {'nombre': 'Salgar', 'departamento': 'Antioquia'},
    {'nombre': 'Santa Bárbara', 'departamento': 'Antioquia'},
    {'nombre': 'Tarso', 'departamento': 'Antioquia'},
    {'nombre': 'Titiribí', 'departamento': 'Antioquia'},
    {'nombre': 'Támesis', 'departamento': 'Antioquia'},
    {'nombre': 'Urrao', 'departamento': 'Antioquia'},
    {'nombre': 'Valparaíso', 'departamento': 'Antioquia'},
    {'nombre': 'Venecia', 'departamento': 'Antioquia'},
]

RUTAS = [
    {'origen': 'Amagá', 'destino': 'Angelópolis', 'distancia_km': 18.8, 'tiempo_minutos': 47},
    {'origen': 'Amagá', 'destino': 'Betania', 'distancia_km': 87.2, 'tiempo_minutos': 150},
    {'origen': 'Amagá', 'destino': 'Betulia', 'distancia_km': 90.4, 'tiempo_minutos': 174},
    {'origen': 'Amagá', 'destino': 'Caramanta', 'distancia_km': 95.7, 'tiempo_minutos': 154},
    {'origen': 'Amagá', 'destino': 'Ciudad Bolívar', 'distancia_km': 76.8, 'tiempo_minutos': 134},
    {'origen': 'Amagá', 'destino': 'Concordia', 'distancia_km': 72.2, 'tiempo_minutos': 145},
    {'origen': 'Amagá', 'destino': 'Fredonia', 'distancia_km': 19.6, 'tiempo_minutos': 39},
    {'origen': 'Amagá', 'destino': 'Hispania', 'distancia_km': 69.1, 'tiempo_minutos': 124},
    {'origen': 'Amagá', 'destino': 'Jardín', 'distancia_km': 103.0, 'tiempo_minutos': 169},
    {'origen': 'Amagá', 'destino': 'Jericó', 'distancia_km': 75.9, 'tiempo_minutos': 126},
    {'origen': 'Amagá', 'destino': 'La Pintada', 'distancia_km': 60.6, 'tiempo_minutos': 97},
    {'origen': 'Amagá', 'destino': 'Montebello', 'distancia_km': 43.8, 'tiempo_minutos': 82},
    {'origen': 'Amagá', 'destino': 'Pueblorrico', 'distancia_km': 78.9, 'tiempo_minutos': 134},
    {'origen': 'Amagá', 'destino': 'Salgar', 'distancia_km': 66.0, 'tiempo_minutos': 119},
    {'origen': 'Amagá', 'destino': 'Santa Bárbara', 'distancia_km': 41.1, 'tiempo_minutos': 70},
    {'origen': 'Amagá', 'destino': 'Támesis', 'distancia_km': 68.7, 'tiempo_minutos': 127},
    {'origen': 'Amagá', 'destino': 'Tarso', 'distancia_km': 65.0, 'tiempo_minutos': 105},
    {'origen': 'Amagá', 'destino': 'Titiribí', 'distancia_km': 19.3, 'tiempo_minutos': 36},
    {'origen': 'Amagá', 'destino': 'Urrao', 'distancia_km': 131.0, 'tiempo_minutos': 236},
    {'origen': 'Amagá', 'destino': 'Valparaíso', 'distancia_km': 78.9, 'tiempo_minutos': 123},
    {'origen': 'Amagá', 'destino': 'Venecia', 'distancia_km': 22.6, 'tiempo_minutos': 45},
    {'origen': 'Amagá', 'destino': 'Carmen de Atrato', 'distancia_km': 110.0, 'tiempo_minutos': 191},
    {'origen': 'Andes', 'destino': 'Amagá', 'distancia_km': 88.2, 'tiempo_minutos': 145},
    {'origen': 'Andes', 'destino': 'Angelópolis', 'distancia_km': 104.0, 'tiempo_minutos': 183},
    {'origen': 'Andes', 'destino': 'Betania', 'distancia_km': 30.0, 'tiempo_minutos': 45},
    {'origen': 'Andes', 'destino': 'Betulia', 'distancia_km': 103.0, 'tiempo_minutos': 148},
    {'origen': 'Andes', 'destino': 'Caramanta', 'distancia_km': 118.0, 'tiempo_minutos': 156},
    {'origen': 'Andes', 'destino': 'Ciudad Bolívar', 'distancia_km': 45.0, 'tiempo_minutos': 60},
    {'origen': 'Andes', 'destino': 'Concordia', 'distancia_km': 75.7, 'tiempo_minutos': 116},
    {'origen': 'Andes', 'destino': 'Fredonia', 'distancia_km': 89.9, 'tiempo_minutos': 121},
    {'origen': 'Andes', 'destino': 'Hispania', 'distancia_km': 20.4, 'tiempo_minutos': 30},
    {'origen': 'Andes', 'destino': 'Jardín', 'distancia_km': 16.3, 'tiempo_minutos': 26},
    {'origen': 'Andes', 'destino': 'Jericó', 'distancia_km': 34.2, 'tiempo_minutos': 88},
    {'origen': 'Andes', 'destino': 'La Pintada', 'distancia_km': 83.2, 'tiempo_minutos': 99},
    {'origen': 'Andes', 'destino': 'Montebello', 'distancia_km': 136.0, 'tiempo_minutos': 205},
    {'origen': 'Andes', 'destino': 'Pueblorrico', 'distancia_km': 31.0, 'tiempo_minutos': 69},
    {'origen': 'Andes', 'destino': 'Salgar', 'distancia_km': 48.0, 'tiempo_minutos': 66},
    {'origen': 'Andes', 'destino': 'Santa Bárbara', 'distancia_km': 108.0, 'tiempo_minutos': 149},
    {'origen': 'Andes', 'destino': 'Támesis', 'distancia_km': 91.2, 'tiempo_minutos': 129},
    {'origen': 'Andes', 'destino': 'Tarso', 'distancia_km': 68.8, 'tiempo_minutos': 93},
    {'origen': 'Andes', 'destino': 'Titiribí', 'distancia_km': 80.5, 'tiempo_minutos': 141},
    {'origen': 'Andes', 'destino': 'Urrao', 'distancia_km': 122.0, 'tiempo_minutos': 200},
    {'origen': 'Andes', 'destino': 'Valparaíso', 'distancia_km': 101.0, 'tiempo_minutos': 125},
    {'origen': 'Andes', 'destino': 'Venecia', 'distancia_km': 66.4, 'tiempo_minutos': 103},
    {'origen': 'Andes', 'destino': 'Carmen de Atrato', 'distancia_km': 78.4, 'tiempo_minutos': 122},
    {'origen': 'Angelópolis', 'destino': 'Amagá', 'distancia_km': 17.7, 'tiempo_minutos': 50},
    {'origen': 'Angelópolis', 'destino': 'Andes', 'distancia_km': 104.0, 'tiempo_minutos': 193},
    {'origen': 'Angelópolis', 'destino': 'Betania', 'distancia_km': 103.0, 'tiempo_minutos': 194},
    {'origen': 'Angelópolis', 'destino': 'Betulia', 'distancia_km': 153.0, 'tiempo_minutos': 241},
    {'origen': 'Angelópolis', 'destino': 'Caramanta', 'distancia_km': 111.0, 'tiempo_minutos': 193},
    {'origen': 'Angelópolis', 'destino': 'Ciudad Bolívar', 'distancia_km': 92.2, 'tiempo_minutos': 178},
    {'origen': 'Angelópolis', 'destino': 'Concordia', 'distancia_km': 87.6, 'tiempo_minutos': 189},
    {'origen': 'Angelópolis', 'destino': 'Fredonia', 'distancia_km': 34.9, 'tiempo_minutos': 83},
    {'origen': 'Angelópolis', 'destino': 'Hispania', 'distancia_km': 84.4, 'tiempo_minutos': 168},
    {'origen': 'Angelópolis', 'destino': 'Jardín', 'distancia_km': 118.0, 'tiempo_minutos': 213},
    {'origen': 'Angelópolis', 'destino': 'Jericó', 'distancia_km': 91.2, 'tiempo_minutos': 169},
    {'origen': 'Angelópolis', 'destino': 'La Pintada', 'distancia_km': 71.7, 'tiempo_minutos': 126},
    {'origen': 'Angelópolis', 'destino': 'Montebello', 'distancia_km': 48.5, 'tiempo_minutos': 94},
    {'origen': 'Angelópolis', 'destino': 'Pueblorrico', 'distancia_km': 94.3, 'tiempo_minutos': 175},
    {'origen': 'Angelópolis', 'destino': 'Salgar', 'distancia_km': 81.4, 'tiempo_minutos': 164},
    {'origen': 'Angelópolis', 'destino': 'Santa Bárbara', 'distancia_km': 45.9, 'tiempo_minutos': 83},
    {'origen': 'Angelópolis', 'destino': 'Támesis', 'distancia_km': 84.0, 'tiempo_minutos': 170},
    {'origen': 'Angelópolis', 'destino': 'Tarso', 'distancia_km': 80.3, 'tiempo_minutos': 149},
    {'origen': 'Angelópolis', 'destino': 'Titiribí', 'distancia_km': 36.4, 'tiempo_minutos': 84},
    {'origen': 'Angelópolis', 'destino': 'Urrao', 'distancia_km': 146.0, 'tiempo_minutos': 278},
    {'origen': 'Angelópolis', 'destino': 'Valparaíso', 'distancia_km': 94.4, 'tiempo_minutos': 162},
    {'origen': 'Angelópolis', 'destino': 'Venecia', 'distancia_km': 37.9, 'tiempo_minutos': 90},
    {'origen': 'Angelópolis', 'destino': 'Carmen de Atrato', 'distancia_km': 126.0, 'tiempo_minutos': 236},
    {'origen': 'Betania', 'destino': 'Amagá', 'distancia_km': 86.9, 'tiempo_minutos': 145},
    {'origen': 'Betania', 'destino': 'Andes', 'distancia_km': 30.0, 'tiempo_minutos': 45},
    {'origen': 'Betania', 'destino': 'Angelópolis', 'distancia_km': 103.0, 'tiempo_minutos': 184},
    {'origen': 'Betania', 'destino': 'Betulia', 'distancia_km': 80.1, 'tiempo_minutos': 140},
    {'origen': 'Betania', 'destino': 'Caramanta', 'distancia_km': 117.0, 'tiempo_minutos': 157},
    {'origen': 'Betania', 'destino': 'Ciudad Bolívar', 'distancia_km': 43.8, 'tiempo_minutos': 61},
    {'origen': 'Betania', 'destino': 'Concordia', 'distancia_km': 74.5, 'tiempo_minutos': 117},
    {'origen': 'Betania', 'destino': 'Fredonia', 'distancia_km': 88.7, 'tiempo_minutos': 122},
    {'origen': 'Betania', 'destino': 'Hispania', 'distancia_km': 19.1, 'tiempo_minutos': 30},
    {'origen': 'Betania', 'destino': 'Jardín', 'distancia_km': 44.6, 'tiempo_minutos': 66},
    {'origen': 'Betania', 'destino': 'Jericó', 'distancia_km': 43.5, 'tiempo_minutos': 94},
    {'origen': 'Betania', 'destino': 'La Pintada', 'distancia_km': 82.0, 'tiempo_minutos': 99},
    {'origen': 'Betania', 'destino': 'Montebello', 'distancia_km': 135.0, 'tiempo_minutos': 205},
    {'origen': 'Betania', 'destino': 'Pueblorrico', 'distancia_km': 32.4, 'tiempo_minutos': 74},
    {'origen': 'Betania', 'destino': 'Salgar', 'distancia_km': 46.8, 'tiempo_minutos': 67},
    {'origen': 'Betania', 'destino': 'Santa Bárbara', 'distancia_km': 107.0, 'tiempo_minutos': 151},
    {'origen': 'Betania', 'destino': 'Támesis', 'distancia_km': 89.8, 'tiempo_minutos': 130},
    {'origen': 'Betania', 'destino': 'Tarso', 'distancia_km': 67.6, 'tiempo_minutos': 93},
    {'origen': 'Betania', 'destino': 'Titiribí', 'distancia_km': 79.3, 'tiempo_minutos': 142},
    {'origen': 'Betania', 'destino': 'Urrao', 'distancia_km': 120.0, 'tiempo_minutos': 201},
    {'origen': 'Betania', 'destino': 'Valparaíso', 'distancia_km': 100.0, 'tiempo_minutos': 126},
    {'origen': 'Betania', 'destino': 'Venecia', 'distancia_km': 65.0, 'tiempo_minutos': 104},
    {'origen': 'Betania', 'destino': 'Carmen de Atrato', 'distancia_km': 77.1, 'tiempo_minutos': 123},
    {'origen': 'Betulia', 'destino': 'Amagá', 'distancia_km': 97.1, 'tiempo_minutos': 172},
    {'origen': 'Betulia', 'destino': 'Andes', 'distancia_km': 103.0, 'tiempo_minutos': 151},
    {'origen': 'Betulia', 'destino': 'Angelópolis', 'distancia_km': 106.0, 'tiempo_minutos': 211},
    {'origen': 'Betulia', 'destino': 'Betania', 'distancia_km': 101.0, 'tiempo_minutos': 152},
    {'origen': 'Betulia', 'destino': 'Caramanta', 'distancia_km': 128.0, 'tiempo_minutos': 194},
    {'origen': 'Betulia', 'destino': 'Ciudad Bolívar', 'distancia_km': 91.0, 'tiempo_minutos': 135},
    {'origen': 'Betulia', 'destino': 'Concordia', 'distancia_km': 86.4, 'tiempo_minutos': 147},
    {'origen': 'Betulia', 'destino': 'Fredonia', 'distancia_km': 87.6, 'tiempo_minutos': 159},
    {'origen': 'Betulia', 'destino': 'Hispania', 'distancia_km': 83.3, 'tiempo_minutos': 126},
    {'origen': 'Betulia', 'destino': 'Jardín', 'distancia_km': 117.0, 'tiempo_minutos': 171},
    {'origen': 'Betulia', 'destino': 'Jericó', 'distancia_km': 89.1, 'tiempo_minutos': 150},
    {'origen': 'Betulia', 'destino': 'La Pintada', 'distancia_km': 92.7, 'tiempo_minutos': 136},
    {'origen': 'Betulia', 'destino': 'Montebello', 'distancia_km': 168.0, 'tiempo_minutos': 275},
    {'origen': 'Betulia', 'destino': 'Pueblorrico', 'distancia_km': 92.2, 'tiempo_minutos': 157},
    {'origen': 'Betulia', 'destino': 'Salgar', 'distancia_km': 80.2, 'tiempo_minutos': 121},
    {'origen': 'Betulia', 'destino': 'Santa Bárbara', 'distancia_km': 128.0, 'tiempo_minutos': 175},
    {'origen': 'Betulia', 'destino': 'Támesis', 'distancia_km': 101.0, 'tiempo_minutos': 165},
    {'origen': 'Betulia', 'destino': 'Tarso', 'distancia_km': 78.3, 'tiempo_minutos': 130},
    {'origen': 'Betulia', 'destino': 'Titiribí', 'distancia_km': 89.4, 'tiempo_minutos': 170},
    {'origen': 'Betulia', 'destino': 'Urrao', 'distancia_km': 40.3, 'tiempo_minutos': 62},
    {'origen': 'Betulia', 'destino': 'Valparaíso', 'distancia_km': 120.0, 'tiempo_minutos': 166},
    {'origen': 'Betulia', 'destino': 'Venecia', 'distancia_km': 75.4, 'tiempo_minutos': 132},
    {'origen': 'Betulia', 'destino': 'Carmen de Atrato', 'distancia_km': 103.0, 'tiempo_minutos': 178},
    {'origen': 'Caramanta', 'destino': 'Amagá', 'distancia_km': 99.4, 'tiempo_minutos': 157},
    {'origen': 'Caramanta', 'destino': 'Andes', 'distancia_km': 122.0, 'tiempo_minutos': 159},
    {'origen': 'Caramanta', 'destino': 'Angelópolis', 'distancia_km': 115.0, 'tiempo_minutos': 195},
    {'origen': 'Caramanta', 'destino': 'Betania', 'distancia_km': 121.0, 'tiempo_minutos': 160},
    {'origen': 'Caramanta', 'destino': 'Betulia', 'distancia_km': 140.0, 'tiempo_minutos': 195},
    {'origen': 'Caramanta', 'destino': 'Ciudad Bolívar', 'distancia_km': 110.0, 'tiempo_minutos': 143},
    {'origen': 'Caramanta', 'destino': 'Concordia', 'distancia_km': 113.0, 'tiempo_minutos': 163},
    {'origen': 'Caramanta', 'destino': 'Fredonia', 'distancia_km': 80.0, 'tiempo_minutos': 121},
    {'origen': 'Caramanta', 'destino': 'Hispania', 'distancia_km': 103.0, 'tiempo_minutos': 134},
    {'origen': 'Caramanta', 'destino': 'Jardín', 'distancia_km': 137.0, 'tiempo_minutos': 179},
    {'origen': 'Caramanta', 'destino': 'Jericó', 'distancia_km': 89.5, 'tiempo_minutos': 128},
    {'origen': 'Caramanta', 'destino': 'La Pintada', 'distancia_km': 39.5, 'tiempo_minutos': 68},
    {'origen': 'Caramanta', 'destino': 'Montebello', 'distancia_km': 92.0, 'tiempo_minutos': 175},
    {'origen': 'Caramanta', 'destino': 'Pueblorrico', 'distancia_km': 92.6, 'tiempo_minutos': 137},
    {'origen': 'Caramanta', 'destino': 'Salgar', 'distancia_km': 99.6, 'tiempo_minutos': 129},
    {'origen': 'Caramanta', 'destino': 'Santa Bárbara', 'distancia_km': 64.8, 'tiempo_minutos': 119},
    {'origen': 'Caramanta', 'destino': 'Támesis', 'distancia_km': 43.8, 'tiempo_minutos': 79},
    {'origen': 'Caramanta', 'destino': 'Tarso', 'distancia_km': 78.6, 'tiempo_minutos': 108},
    {'origen': 'Caramanta', 'destino': 'Titiribí', 'distancia_km': 115.0, 'tiempo_minutos': 175},
    {'origen': 'Caramanta', 'destino': 'Urrao', 'distancia_km': 172.0, 'tiempo_minutos': 253},
    {'origen': 'Caramanta', 'destino': 'Valparaíso', 'distancia_km': 17.0, 'tiempo_minutos': 33},
    {'origen': 'Caramanta', 'destino': 'Venecia', 'distancia_km': 92.9, 'tiempo_minutos': 149},
    {'origen': 'Caramanta', 'destino': 'Carmen de Atrato', 'distancia_km': 144.0, 'tiempo_minutos': 202},
    {'origen': 'Ciudad Bolívar', 'destino': 'Amagá', 'distancia_km': 76.5, 'tiempo_minutos': 129},
    {'origen': 'Ciudad Bolívar', 'destino': 'Andes', 'distancia_km': 44.8, 'tiempo_minutos': 60},
    {'origen': 'Ciudad Bolívar', 'destino': 'Angelópolis', 'distancia_km': 92.2, 'tiempo_minutos': 167},
    {'origen': 'Ciudad Bolívar', 'destino': 'Betania', 'distancia_km': 43.7, 'tiempo_minutos': 60},
    {'origen': 'Ciudad Bolívar', 'destino': 'Betulia', 'distancia_km': 91.0, 'tiempo_minutos': 132},
    {'origen': 'Ciudad Bolívar', 'destino': 'Caramanta', 'distancia_km': 106.0, 'tiempo_minutos': 139},
    {'origen': 'Ciudad Bolívar', 'destino': 'Concordia', 'distancia_km': 64.0, 'tiempo_minutos': 100},
    {'origen': 'Ciudad Bolívar', 'destino': 'Fredonia', 'distancia_km': 78.2, 'tiempo_minutos': 105},
    {'origen': 'Ciudad Bolívar', 'destino': 'Hispania', 'distancia_km': 25.6, 'tiempo_minutos': 34},
    {'origen': 'Ciudad Bolívar', 'destino': 'Jardín', 'distancia_km': 59.5, 'tiempo_minutos': 80},
    {'origen': 'Ciudad Bolívar', 'destino': 'Jericó', 'distancia_km': 67.9, 'tiempo_minutos': 97},
    {'origen': 'Ciudad Bolívar', 'destino': 'La Pintada', 'distancia_km': 71.5, 'tiempo_minutos': 82},
    {'origen': 'Ciudad Bolívar', 'destino': 'Montebello', 'distancia_km': 124.0, 'tiempo_minutos': 188},
    {'origen': 'Ciudad Bolívar', 'destino': 'Pueblorrico', 'distancia_km': 47.4, 'tiempo_minutos': 88},
    {'origen': 'Ciudad Bolívar', 'destino': 'Salgar', 'distancia_km': 36.3, 'tiempo_minutos': 50},
    {'origen': 'Ciudad Bolívar', 'destino': 'Santa Bárbara', 'distancia_km': 96.8, 'tiempo_minutos': 133},
    {'origen': 'Ciudad Bolívar', 'destino': 'Támesis', 'distancia_km': 79.5, 'tiempo_minutos': 112},
    {'origen': 'Ciudad Bolívar', 'destino': 'Tarso', 'distancia_km': 57.1, 'tiempo_minutos': 77},
    {'origen': 'Ciudad Bolívar', 'destino': 'Titiribí', 'distancia_km': 68.8, 'tiempo_minutos': 126},
    {'origen': 'Ciudad Bolívar', 'destino': 'Urrao', 'distancia_km': 110.0, 'tiempo_minutos': 183},
    {'origen': 'Ciudad Bolívar', 'destino': 'Valparaíso', 'distancia_km': 89.8, 'tiempo_minutos': 109},
    {'origen': 'Ciudad Bolívar', 'destino': 'Venecia', 'distancia_km': 54.7, 'tiempo_minutos': 88},
    {'origen': 'Ciudad Bolívar', 'destino': 'Carmen de Atrato', 'distancia_km': 33.8, 'tiempo_minutos': 65},
    {'origen': 'Concordia', 'destino': 'Amagá', 'distancia_km': 71.9, 'tiempo_minutos': 141},
    {'origen': 'Concordia', 'destino': 'Andes', 'distancia_km': 75.5, 'tiempo_minutos': 117},
    {'origen': 'Concordia', 'destino': 'Angelópolis', 'distancia_km': 87.5, 'tiempo_minutos': 179},
    {'origen': 'Concordia', 'destino': 'Betania', 'distancia_km': 74.4, 'tiempo_minutos': 117},
    {'origen': 'Concordia', 'destino': 'Betulia', 'distancia_km': 33.2, 'tiempo_minutos': 71},
    {'origen': 'Concordia', 'destino': 'Caramanta', 'distancia_km': 109.0, 'tiempo_minutos': 161},
    {'origen': 'Concordia', 'destino': 'Ciudad Bolívar', 'distancia_km': 64.0, 'tiempo_minutos': 101},
    {'origen': 'Concordia', 'destino': 'Fredonia', 'distancia_km': 81.1, 'tiempo_minutos': 126},
    {'origen': 'Concordia', 'destino': 'Hispania', 'distancia_km': 56.2, 'tiempo_minutos': 91},
    {'origen': 'Concordia', 'destino': 'Jardín', 'distancia_km': 90.1, 'tiempo_minutos': 137},
    {'origen': 'Concordia', 'destino': 'Jericó', 'distancia_km': 63.4, 'tiempo_minutos': 98},
    {'origen': 'Concordia', 'destino': 'La Pintada', 'distancia_km': 74.4, 'tiempo_minutos': 104},
    {'origen': 'Concordia', 'destino': 'Montebello', 'distancia_km': 127.0, 'tiempo_minutos': 210},
    {'origen': 'Concordia', 'destino': 'Pueblorrico', 'distancia_km': 73.9, 'tiempo_minutos': 127},
    {'origen': 'Concordia', 'destino': 'Salgar', 'distancia_km': 53.2, 'tiempo_minutos': 87},
    {'origen': 'Concordia', 'destino': 'Santa Bárbara', 'distancia_km': 99.7, 'tiempo_minutos': 155},
    {'origen': 'Concordia', 'destino': 'Támesis', 'distancia_km': 82.4, 'tiempo_minutos': 134},
    {'origen': 'Concordia', 'destino': 'Tarso', 'distancia_km': 60.0, 'tiempo_minutos': 98},
    {'origen': 'Concordia', 'destino': 'Titiribí', 'distancia_km': 64.3, 'tiempo_minutos': 138},
    {'origen': 'Concordia', 'destino': 'Urrao', 'distancia_km': 73.5, 'tiempo_minutos': 132},
    {'origen': 'Concordia', 'destino': 'Valparaíso', 'distancia_km': 92.7, 'tiempo_minutos': 130},
    {'origen': 'Concordia', 'destino': 'Venecia', 'distancia_km': 42.7, 'tiempo_minutos': 80},
    {'origen': 'Concordia', 'destino': 'Carmen de Atrato', 'distancia_km': 97.4, 'tiempo_minutos': 159},
    {'origen': 'Fredonia', 'destino': 'Amagá', 'distancia_km': 19.3, 'tiempo_minutos': 37},
    {'origen': 'Fredonia', 'destino': 'Andes', 'distancia_km': 88.8, 'tiempo_minutos': 118},
    {'origen': 'Fredonia', 'destino': 'Angelópolis', 'distancia_km': 35.1, 'tiempo_minutos': 76},
    {'origen': 'Fredonia', 'destino': 'Betania', 'distancia_km': 87.7, 'tiempo_minutos': 118},
    {'origen': 'Fredonia', 'destino': 'Betulia', 'distancia_km': 107.0, 'tiempo_minutos': 154},
    {'origen': 'Fredonia', 'destino': 'Caramanta', 'distancia_km': 76.1, 'tiempo_minutos': 116},
    {'origen': 'Fredonia', 'destino': 'Ciudad Bolívar', 'distancia_km': 77.3, 'tiempo_minutos': 101},
    {'origen': 'Fredonia', 'destino': 'Concordia', 'distancia_km': 80.2, 'tiempo_minutos': 122},
    {'origen': 'Fredonia', 'destino': 'Hispania', 'distancia_km': 69.6, 'tiempo_minutos': 92},
    {'origen': 'Fredonia', 'destino': 'Jardín', 'distancia_km': 103.0, 'tiempo_minutos': 137},
    {'origen': 'Fredonia', 'destino': 'Jericó', 'distancia_km': 56.4, 'tiempo_minutos': 86},
    {'origen': 'Fredonia', 'destino': 'La Pintada', 'distancia_km': 41.2, 'tiempo_minutos': 58},
    {'origen': 'Fredonia', 'destino': 'Montebello', 'distancia_km': 60.1, 'tiempo_minutos': 110},
    {'origen': 'Fredonia', 'destino': 'Pueblorrico', 'distancia_km': 59.5, 'tiempo_minutos': 95},
    {'origen': 'Fredonia', 'destino': 'Salgar', 'distancia_km': 66.6, 'tiempo_minutos': 88},
    {'origen': 'Fredonia', 'destino': 'Santa Bárbara', 'distancia_km': 33.3, 'tiempo_minutos': 81},
    {'origen': 'Fredonia', 'destino': 'Támesis', 'distancia_km': 49.2, 'tiempo_minutos': 89},
    {'origen': 'Fredonia', 'destino': 'Tarso', 'distancia_km': 45.6, 'tiempo_minutos': 66},
    {'origen': 'Fredonia', 'destino': 'Titiribí', 'distancia_km': 38.1, 'tiempo_minutos': 71},
    {'origen': 'Fredonia', 'destino': 'Urrao', 'distancia_km': 139.0, 'tiempo_minutos': 213},
    {'origen': 'Fredonia', 'destino': 'Valparaíso', 'distancia_km': 59.4, 'tiempo_minutos': 85},
    {'origen': 'Fredonia', 'destino': 'Venecia', 'distancia_km': 12.9, 'tiempo_minutos': 30},
    {'origen': 'Fredonia', 'destino': 'Carmen de Atrato', 'distancia_km': 111.0, 'tiempo_minutos': 160},
    {'origen': 'Hispania', 'destino': 'Amagá', 'distancia_km': 68.5, 'tiempo_minutos': 119},
    {'origen': 'Hispania', 'destino': 'Andes', 'distancia_km': 20.2, 'tiempo_minutos': 30},
    {'origen': 'Hispania', 'destino': 'Angelópolis', 'distancia_km': 84.2, 'tiempo_minutos': 159},
    {'origen': 'Hispania', 'destino': 'Betania', 'distancia_km': 19.0, 'tiempo_minutos': 30},
    {'origen': 'Hispania', 'destino': 'Betulia', 'distancia_km': 83.0, 'tiempo_minutos': 122},
    {'origen': 'Hispania', 'destino': 'Caramanta', 'distancia_km': 98.5, 'tiempo_minutos': 129},
    {'origen': 'Hispania', 'destino': 'Ciudad Bolívar', 'distancia_km': 25.3, 'tiempo_minutos': 34},
    {'origen': 'Hispania', 'destino': 'Concordia', 'distancia_km': 56.0, 'tiempo_minutos': 90},
    {'origen': 'Hispania', 'destino': 'Fredonia', 'distancia_km': 70.2, 'tiempo_minutos': 94},
    {'origen': 'Hispania', 'destino': 'Jardín', 'distancia_km': 34.8, 'tiempo_minutos': 51},
    {'origen': 'Hispania', 'destino': 'Jericó', 'distancia_km': 60.0, 'tiempo_minutos': 86},
    {'origen': 'Hispania', 'destino': 'La Pintada', 'distancia_km': 63.6, 'tiempo_minutos': 72},
    {'origen': 'Hispania', 'destino': 'Montebello', 'distancia_km': 116.0, 'tiempo_minutos': 178},
    {'origen': 'Hispania', 'destino': 'Pueblorrico', 'distancia_km': 22.8, 'tiempo_minutos': 59},
    {'origen': 'Hispania', 'destino': 'Salgar', 'distancia_km': 28.3, 'tiempo_minutos': 40},
    {'origen': 'Hispania', 'destino': 'Santa Bárbara', 'distancia_km': 88.8, 'tiempo_minutos': 122},
    {'origen': 'Hispania', 'destino': 'Támesis', 'distancia_km': 71.5, 'tiempo_minutos': 102},
    {'origen': 'Hispania', 'destino': 'Tarso', 'distancia_km': 49.1, 'tiempo_minutos': 66},
    {'origen': 'Hispania', 'destino': 'Titiribí', 'distancia_km': 60.4, 'tiempo_minutos': 84},
    {'origen': 'Hispania', 'destino': 'Urrao', 'distancia_km': 102.0, 'tiempo_minutos': 174},
    {'origen': 'Hispania', 'destino': 'Valparaíso', 'distancia_km': 81.8, 'tiempo_minutos': 98},
    {'origen': 'Hispania', 'destino': 'Venecia', 'distancia_km': 46.8, 'tiempo_minutos': 78},
    {'origen': 'Hispania', 'destino': 'Carmen de Atrato', 'distancia_km': 58.8, 'tiempo_minutos': 96},
    {'origen': 'Jardín', 'destino': 'Amagá', 'distancia_km': 103.0, 'tiempo_minutos': 164},
    {'origen': 'Jardín', 'destino': 'Andes', 'distancia_km': 16.1, 'tiempo_minutos': 26},
    {'origen': 'Jardín', 'destino': 'Angelópolis', 'distancia_km': 118.0, 'tiempo_minutos': 202},
    {'origen': 'Jardín', 'destino': 'Betania', 'distancia_km': 44.5, 'tiempo_minutos': 64},
    {'origen': 'Jardín', 'destino': 'Betulia', 'distancia_km': 117.0, 'tiempo_minutos': 167},
    {'origen': 'Jardín', 'destino': 'Caramanta', 'distancia_km': 133.0, 'tiempo_minutos': 176},
    {'origen': 'Jardín', 'destino': 'Ciudad Bolívar', 'distancia_km': 59.5, 'tiempo_minutos': 79},
    {'origen': 'Jardín', 'destino': 'Concordia', 'distancia_km': 90.2, 'tiempo_minutos': 135},
    {'origen': 'Jardín', 'destino': 'Fredonia', 'distancia_km': 104.0, 'tiempo_minutos': 140},
    {'origen': 'Jardín', 'destino': 'Hispania', 'distancia_km': 34.8, 'tiempo_minutos': 49},
    {'origen': 'Jardín', 'destino': 'Jericó', 'distancia_km': 48.7, 'tiempo_minutos': 109},
    {'origen': 'Jardín', 'destino': 'La Pintada', 'distancia_km': 97.7, 'tiempo_minutos': 118},
    {'origen': 'Jardín', 'destino': 'Montebello', 'distancia_km': 150.0, 'tiempo_minutos': 223},
    {'origen': 'Jardín', 'destino': 'Pueblorrico', 'distancia_km': 45.5, 'tiempo_minutos': 89},
    {'origen': 'Jardín', 'destino': 'Salgar', 'distancia_km': 62.5, 'tiempo_minutos': 85},
    {'origen': 'Jardín', 'destino': 'Santa Bárbara', 'distancia_km': 123.0, 'tiempo_minutos': 169},
    {'origen': 'Jardín', 'destino': 'Támesis', 'distancia_km': 106.0, 'tiempo_minutos': 147},
    {'origen': 'Jardín', 'destino': 'Tarso', 'distancia_km': 83.3, 'tiempo_minutos': 112},
    {'origen': 'Jardín', 'destino': 'Titiribí', 'distancia_km': 95.1, 'tiempo_minutos': 161},
    {'origen': 'Jardín', 'destino': 'Urrao', 'distancia_km': 136.0, 'tiempo_minutos': 219},
    {'origen': 'Jardín', 'destino': 'Valparaíso', 'distancia_km': 116.0, 'tiempo_minutos': 145},
    {'origen': 'Jardín', 'destino': 'Venecia', 'distancia_km': 80.9, 'tiempo_minutos': 123},
    {'origen': 'Jardín', 'destino': 'Carmen de Atrato', 'distancia_km': 92.9, 'tiempo_minutos': 141},
    {'origen': 'Jericó', 'destino': 'Amagá', 'distancia_km': 76.3, 'tiempo_minutos': 123},
    {'origen': 'Jericó', 'destino': 'Andes', 'distancia_km': 34.0, 'tiempo_minutos': 87},
    {'origen': 'Jericó', 'destino': 'Angelópolis', 'distancia_km': 91.9, 'tiempo_minutos': 161},
    {'origen': 'Jericó', 'destino': 'Betania', 'distancia_km': 43.8, 'tiempo_minutos': 97},
    {'origen': 'Jericó', 'destino': 'Betulia', 'distancia_km': 98.1, 'tiempo_minutos': 147},
    {'origen': 'Jericó', 'destino': 'Caramanta', 'distancia_km': 85.2, 'tiempo_minutos': 122},
    {'origen': 'Jericó', 'destino': 'Ciudad Bolívar', 'distancia_km': 68.1, 'tiempo_minutos': 94},
    {'origen': 'Jericó', 'destino': 'Concordia', 'distancia_km': 71.0, 'tiempo_minutos': 116},
    {'origen': 'Jericó', 'destino': 'Fredonia', 'distancia_km': 57.0, 'tiempo_minutos': 86},
    {'origen': 'Jericó', 'destino': 'Hispania', 'distancia_km': 60.4, 'tiempo_minutos': 84},
    {'origen': 'Jericó', 'destino': 'Jardín', 'distancia_km': 48.6, 'tiempo_minutos': 108},
    {'origen': 'Jericó', 'destino': 'La Pintada', 'distancia_km': 50.3, 'tiempo_minutos': 64},
    {'origen': 'Jericó', 'destino': 'Montebello', 'distancia_km': 103.0, 'tiempo_minutos': 170},
    {'origen': 'Jericó', 'destino': 'Pueblorrico', 'distancia_km': 11.8, 'tiempo_minutos': 27},
    {'origen': 'Jericó', 'destino': 'Salgar', 'distancia_km': 57.4, 'tiempo_minutos': 80},
    {'origen': 'Jericó', 'destino': 'Santa Bárbara', 'distancia_km': 75.6, 'tiempo_minutos': 114},
    {'origen': 'Jericó', 'destino': 'Támesis', 'distancia_km': 25.1, 'tiempo_minutos': 65},
    {'origen': 'Jericó', 'destino': 'Tarso', 'distancia_km': 24.9, 'tiempo_minutos': 50},
    {'origen': 'Jericó', 'destino': 'Titiribí', 'distancia_km': 72.2, 'tiempo_minutos': 126},
    {'origen': 'Jericó', 'destino': 'Urrao', 'distancia_km': 130.0, 'tiempo_minutos': 207},
    {'origen': 'Jericó', 'destino': 'Valparaíso', 'distancia_km': 68.6, 'tiempo_minutos': 91},
    {'origen': 'Jericó', 'destino': 'Venecia', 'distancia_km': 67.4, 'tiempo_minutos': 101},
    {'origen': 'Jericó', 'destino': 'Carmen de Atrato', 'distancia_km': 101.0, 'tiempo_minutos': 156},
    {'origen': 'La Pintada', 'destino': 'Amagá', 'distancia_km': 61.5, 'tiempo_minutos': 93},
    {'origen': 'La Pintada', 'destino': 'Andes', 'distancia_km': 84.1, 'tiempo_minutos': 95},
    {'origen': 'La Pintada', 'destino': 'Angelópolis', 'distancia_km': 77.1, 'tiempo_minutos': 133},
    {'origen': 'La Pintada', 'destino': 'Betania', 'distancia_km': 80.0, 'tiempo_minutos': 18},
    {'origen': 'La Pintada', 'destino': 'Betulia', 'distancia_km': 103.0, 'tiempo_minutos': 132},
    {'origen': 'La Pintada', 'destino': 'Caramanta', 'distancia_km': 39.3, 'tiempo_minutos': 66},
    {'origen': 'La Pintada', 'destino': 'Ciudad Bolívar', 'distancia_km': 72.6, 'tiempo_minutos': 79},
    {'origen': 'La Pintada', 'destino': 'Concordia', 'distancia_km': 75.5, 'tiempo_minutos': 100},
    {'origen': 'La Pintada', 'destino': 'Fredonia', 'distancia_km': 42.2, 'tiempo_minutos': 57},
    {'origen': 'La Pintada', 'destino': 'Hispania', 'distancia_km': 64.9, 'tiempo_minutos': 70},
    {'origen': 'La Pintada', 'destino': 'Jardín', 'distancia_km': 98.8, 'tiempo_minutos': 115},
    {'origen': 'La Pintada', 'destino': 'Jericó', 'distancia_km': 51.7, 'tiempo_minutos': 65},
    {'origen': 'La Pintada', 'destino': 'Montebello', 'distancia_km': 52.8, 'tiempo_minutos': 109},
    {'origen': 'La Pintada', 'destino': 'Pueblorrico', 'distancia_km': 54.8, 'tiempo_minutos': 73},
    {'origen': 'La Pintada', 'destino': 'Salgar', 'distancia_km': 61.9, 'tiempo_minutos': 66},
    {'origen': 'La Pintada', 'destino': 'Santa Bárbara', 'distancia_km': 25.6, 'tiempo_minutos': 53},
    {'origen': 'La Pintada', 'destino': 'Támesis', 'distancia_km': 31.9, 'tiempo_minutos': 53},
    {'origen': 'La Pintada', 'destino': 'Tarso', 'distancia_km': 40.9, 'tiempo_minutos': 44},
    {'origen': 'La Pintada', 'destino': 'Titiribí', 'distancia_km': 76.7, 'tiempo_minutos': 111},
    {'origen': 'La Pintada', 'destino': 'Urrao', 'distancia_km': 134.0, 'tiempo_minutos': 192},
    {'origen': 'La Pintada', 'destino': 'Valparaíso', 'distancia_km': 22.7, 'tiempo_minutos': 35},
    {'origen': 'La Pintada', 'destino': 'Venecia', 'distancia_km': 55.1, 'tiempo_minutos': 85},
    {'origen': 'La Pintada', 'destino': 'Carmen de Atrato', 'distancia_km': 106.0, 'tiempo_minutos': 141},
    {'origen': 'Montebello', 'destino': 'Amagá', 'distancia_km': 43.2, 'tiempo_minutos': 85},
    {'origen': 'Montebello', 'destino': 'Andes', 'distancia_km': 137.0, 'tiempo_minutos': 189},
    {'origen': 'Montebello', 'destino': 'Angelópolis', 'distancia_km': 49.1, 'tiempo_minutos': 105},
    {'origen': 'Montebello', 'destino': 'Betania', 'distancia_km': 136.0, 'tiempo_minutos': 189},
    {'origen': 'Montebello', 'destino': 'Betulia', 'distancia_km': 155.0, 'tiempo_minutos': 226},
    {'origen': 'Montebello', 'destino': 'Caramanta', 'distancia_km': 91.9, 'tiempo_minutos': 159},
    {'origen': 'Montebello', 'destino': 'Ciudad Bolívar', 'distancia_km': 125.0, 'tiempo_minutos': 173},
    {'origen': 'Montebello', 'destino': 'Concordia', 'distancia_km': 128.0, 'tiempo_minutos': 192},
    {'origen': 'Montebello', 'destino': 'Fredonia', 'distancia_km': 48.0, 'tiempo_minutos': 109},
    {'origen': 'Montebello', 'destino': 'Hispania', 'distancia_km': 117.0, 'tiempo_minutos': 163},
    {'origen': 'Montebello', 'destino': 'Jardín', 'distancia_km': 151.0, 'tiempo_minutos': 209},
    {'origen': 'Montebello', 'destino': 'Jericó', 'distancia_km': 104.0, 'tiempo_minutos': 157},
    {'origen': 'Montebello', 'destino': 'La Pintada', 'distancia_km': 52.7, 'tiempo_minutos': 93},
    {'origen': 'Montebello', 'destino': 'Pueblorrico', 'distancia_km': 107.0, 'tiempo_minutos': 163},
    {'origen': 'Montebello', 'destino': 'Salgar', 'distancia_km': 114.0, 'tiempo_minutos': 159},
    {'origen': 'Montebello', 'destino': 'Santa Bárbara', 'distancia_km': 26.7, 'tiempo_minutos': 51},
    {'origen': 'Montebello', 'destino': 'Támesis', 'distancia_km': 84.4, 'tiempo_minutos': 145},
    {'origen': 'Montebello', 'destino': 'Tarso', 'distancia_km': 93.4, 'tiempo_minutos': 137},
    {'origen': 'Montebello', 'destino': 'Titiribí', 'distancia_km': 62.0, 'tiempo_minutos': 118},
    {'origen': 'Montebello', 'destino': 'Urrao', 'distancia_km': 186.0, 'tiempo_minutos': 281},
    {'origen': 'Montebello', 'destino': 'Valparaíso', 'distancia_km': 75.3, 'tiempo_minutos': 128},
    {'origen': 'Montebello', 'destino': 'Venecia', 'distancia_km': 63.5, 'tiempo_minutos': 125},
    {'origen': 'Montebello', 'destino': 'Carmen de Atrato', 'distancia_km': 159.0, 'tiempo_minutos': 231},
    {'origen': 'Pueblorrico', 'destino': 'Amagá', 'distancia_km': 86.8, 'tiempo_minutos': 141},
    {'origen': 'Pueblorrico', 'destino': 'Andes', 'distancia_km': 30.8, 'tiempo_minutos': 70},
    {'origen': 'Pueblorrico', 'destino': 'Angelópolis', 'distancia_km': 103.0, 'tiempo_minutos': 180},
    {'origen': 'Pueblorrico', 'destino': 'Betania', 'distancia_km': 32.4, 'tiempo_minutos': 72},
    {'origen': 'Pueblorrico', 'destino': 'Betulia', 'distancia_km': 109.0, 'tiempo_minutos': 166},
    {'origen': 'Pueblorrico', 'destino': 'Caramanta', 'distancia_km': 95.8, 'tiempo_minutos': 140},
    {'origen': 'Pueblorrico', 'destino': 'Ciudad Bolívar', 'distancia_km': 48.5, 'tiempo_minutos': 91},
    {'origen': 'Pueblorrico', 'destino': 'Concordia', 'distancia_km': 81.6, 'tiempo_minutos': 134},
    {'origen': 'Pueblorrico', 'destino': 'Fredonia', 'distancia_km': 67.5, 'tiempo_minutos': 105},
    {'origen': 'Pueblorrico', 'destino': 'Hispania', 'distancia_km': 22.7, 'tiempo_minutos': 59},
    {'origen': 'Pueblorrico', 'destino': 'Jardín', 'distancia_km': 45.5, 'tiempo_minutos': 91},
    {'origen': 'Pueblorrico', 'destino': 'Jericó', 'distancia_km': 11.8, 'tiempo_minutos': 25},
    {'origen': 'Pueblorrico', 'destino': 'La Pintada', 'distancia_km': 60.9, 'tiempo_minutos': 83},
    {'origen': 'Pueblorrico', 'destino': 'Montebello', 'distancia_km': 113.0, 'tiempo_minutos': 189},
    {'origen': 'Pueblorrico', 'destino': 'Salgar', 'distancia_km': 50.4, 'tiempo_minutos': 94},
    {'origen': 'Pueblorrico', 'destino': 'Santa Bárbara', 'distancia_km': 86.1, 'tiempo_minutos': 134},
    {'origen': 'Pueblorrico', 'destino': 'Támesis', 'distancia_km': 36.2, 'tiempo_minutos': 88},
    {'origen': 'Pueblorrico', 'destino': 'Tarso', 'distancia_km': 14.1, 'tiempo_minutos': 28},
    {'origen': 'Pueblorrico', 'destino': 'Titiribí', 'distancia_km': 82.8, 'tiempo_minutos': 145},
    {'origen': 'Pueblorrico', 'destino': 'Urrao', 'distancia_km': 140.0, 'tiempo_minutos': 225},
    {'origen': 'Pueblorrico', 'destino': 'Valparaíso', 'distancia_km': 79.1, 'tiempo_minutos': 110},
    {'origen': 'Pueblorrico', 'destino': 'Venecia', 'distancia_km': 78.0, 'tiempo_minutos': 120},
    {'origen': 'Pueblorrico', 'destino': 'Carmen de Atrato', 'distancia_km': 80.7, 'tiempo_minutos': 148},
    {'origen': 'Salgar', 'destino': 'Amagá', 'distancia_km': 65.7, 'tiempo_minutos': 116},
    {'origen': 'Salgar', 'destino': 'Andes', 'distancia_km': 47.8, 'tiempo_minutos': 66},
    {'origen': 'Salgar', 'destino': 'Angelópolis', 'distancia_km': 81.3, 'tiempo_minutos': 154},
    {'origen': 'Salgar', 'destino': 'Betania', 'distancia_km': 46.7, 'tiempo_minutos': 66},
    {'origen': 'Salgar', 'destino': 'Betulia', 'distancia_km': 80.2, 'tiempo_minutos': 118},
    {'origen': 'Salgar', 'destino': 'Caramanta', 'distancia_km': 95.7, 'tiempo_minutos': 126},
    {'origen': 'Salgar', 'destino': 'Ciudad Bolívar', 'distancia_km': 36.3, 'tiempo_minutos': 50},
    {'origen': 'Salgar', 'destino': 'Concordia', 'distancia_km': 53.2, 'tiempo_minutos': 87},
    {'origen': 'Salgar', 'destino': 'Fredonia', 'distancia_km': 67.4, 'tiempo_minutos': 91},
    {'origen': 'Salgar', 'destino': 'Hispania', 'distancia_km': 28.6, 'tiempo_minutos': 40},
    {'origen': 'Salgar', 'destino': 'Jardín', 'distancia_km': 62.5, 'tiempo_minutos': 86},
    {'origen': 'Salgar', 'destino': 'Jericó', 'distancia_km': 57.2, 'tiempo_minutos': 84},
    {'origen': 'Salgar', 'destino': 'La Pintada', 'distancia_km': 60.8, 'tiempo_minutos': 69},
    {'origen': 'Salgar', 'destino': 'Montebello', 'distancia_km': 113.0, 'tiempo_minutos': 175},
    {'origen': 'Salgar', 'destino': 'Pueblorrico', 'distancia_km': 60.3, 'tiempo_minutos': 92},
    {'origen': 'Salgar', 'destino': 'Támesis', 'distancia_km': 68.7, 'tiempo_minutos': 99},
    {'origen': 'Salgar', 'destino': 'Tarso', 'distancia_km': 46.3, 'tiempo_minutos': 63},
    {'origen': 'Salgar', 'destino': 'Titiribí', 'distancia_km': 58.1, 'tiempo_minutos': 112},
    {'origen': 'Salgar', 'destino': 'Urrao', 'distancia_km': 73.6, 'tiempo_minutos': 135},
    {'origen': 'Salgar', 'destino': 'Valparaíso', 'distancia_km': 79.0, 'tiempo_minutos': 96},
    {'origen': 'Salgar', 'destino': 'Venecia', 'distancia_km': 44.0, 'tiempo_minutos': 75},
    {'origen': 'Salgar', 'destino': 'Carmen de Atrato', 'distancia_km': 69.7, 'tiempo_minutos': 112},
    {'origen': 'Santa Bárbara', 'destino': 'Amagá', 'distancia_km': 40.5, 'tiempo_minutos': 79},
    {'origen': 'Santa Bárbara', 'destino': 'Andes', 'distancia_km': 110.0, 'tiempo_minutos': 138},
    {'origen': 'Santa Bárbara', 'destino': 'Angelópolis', 'distancia_km': 46.5, 'tiempo_minutos': 99},
    {'origen': 'Santa Bárbara', 'destino': 'Betania', 'distancia_km': 109.0, 'tiempo_minutos': 138},
    {'origen': 'Santa Bárbara', 'destino': 'Betulia', 'distancia_km': 128.0, 'tiempo_minutos': 175},
    {'origen': 'Santa Bárbara', 'destino': 'Caramanta', 'distancia_km': 65.2, 'tiempo_minutos': 109},
    {'origen': 'Santa Bárbara', 'destino': 'Ciudad Bolívar', 'distancia_km': 98.5, 'tiempo_minutos': 122},
    {'origen': 'Santa Bárbara', 'destino': 'Concordia', 'distancia_km': 101.0, 'tiempo_minutos': 143},
    {'origen': 'Santa Bárbara', 'destino': 'Fredonia', 'distancia_km': 33.3, 'tiempo_minutos': 84},
    {'origen': 'Santa Bárbara', 'destino': 'Hispania', 'distancia_km': 90.8, 'tiempo_minutos': 113},
    {'origen': 'Santa Bárbara', 'destino': 'Jardín', 'distancia_km': 125.0, 'tiempo_minutos': 158},
    {'origen': 'Santa Bárbara', 'destino': 'Jericó', 'distancia_km': 77.6, 'tiempo_minutos': 108},
    {'origen': 'Santa Bárbara', 'destino': 'La Pintada', 'distancia_km': 26.0, 'tiempo_minutos': 43},
    {'origen': 'Santa Bárbara', 'destino': 'Montebello', 'distancia_km': 26.8, 'tiempo_minutos': 56},
    {'origen': 'Santa Bárbara', 'destino': 'Pueblorrico', 'distancia_km': 80.7, 'tiempo_minutos': 115},
    {'origen': 'Santa Bárbara', 'destino': 'Salgar', 'distancia_km': 87.7, 'tiempo_minutos': 109},
    {'origen': 'Santa Bárbara', 'destino': 'Támesis', 'distancia_km': 57.7, 'tiempo_minutos': 96},
    {'origen': 'Santa Bárbara', 'destino': 'Tarso', 'distancia_km': 66.7, 'tiempo_minutos': 86},
    {'origen': 'Santa Bárbara', 'destino': 'Titiribí', 'distancia_km': 59.3, 'tiempo_minutos': 112},
    {'origen': 'Santa Bárbara', 'destino': 'Urrao', 'distancia_km': 160.0, 'tiempo_minutos': 233},
    {'origen': 'Santa Bárbara', 'destino': 'Valparaíso', 'distancia_km': 48.6, 'tiempo_minutos': 79},
    {'origen': 'Santa Bárbara', 'destino': 'Venecia', 'distancia_km': 46.1, 'tiempo_minutos': 111},
    {'origen': 'Santa Bárbara', 'destino': 'Carmen de Atrato', 'distancia_km': 132.0, 'tiempo_minutos': 179},
    {'origen': 'Támesis', 'destino': 'Amagá', 'distancia_km': 68.6, 'tiempo_minutos': 124},
    {'origen': 'Támesis', 'destino': 'Andes', 'distancia_km': 91.2, 'tiempo_minutos': 128},
    {'origen': 'Támesis', 'destino': 'Angelópolis', 'distancia_km': 84.3, 'tiempo_minutos': 163},
    {'origen': 'Támesis', 'destino': 'Betania', 'distancia_km': 90.1, 'tiempo_minutos': 128},
    {'origen': 'Támesis', 'destino': 'Betulia', 'distancia_km': 101.0, 'tiempo_minutos': 163},
    {'origen': 'Támesis', 'destino': 'Caramanta', 'distancia_km': 43.7, 'tiempo_minutos': 77},
    {'origen': 'Támesis', 'destino': 'Ciudad Bolívar', 'distancia_km': 79.7, 'tiempo_minutos': 112},
    {'origen': 'Támesis', 'destino': 'Concordia', 'distancia_km': 82.6, 'tiempo_minutos': 133},
    {'origen': 'Támesis', 'destino': 'Fredonia', 'distancia_km': 49.3, 'tiempo_minutos': 88},
    {'origen': 'Támesis', 'destino': 'Hispania', 'distancia_km': 72.0, 'tiempo_minutos': 103},
    {'origen': 'Támesis', 'destino': 'Jardín', 'distancia_km': 106.0, 'tiempo_minutos': 148},
    {'origen': 'Támesis', 'destino': 'Jericó', 'distancia_km': 25.1, 'tiempo_minutos': 64},
    {'origen': 'Támesis', 'destino': 'La Pintada', 'distancia_km': 31.9, 'tiempo_minutos': 53},
    {'origen': 'Támesis', 'destino': 'Montebello', 'distancia_km': 84.4, 'tiempo_minutos': 159},
    {'origen': 'Támesis', 'destino': 'Pueblorrico', 'distancia_km': 36.0, 'tiempo_minutos': 86},
    {'origen': 'Támesis', 'destino': 'Salgar', 'distancia_km': 69.0, 'tiempo_minutos': 98},
    {'origen': 'Támesis', 'destino': 'Santa Bárbara', 'distancia_km': 57.2, 'tiempo_minutos': 103},
    {'origen': 'Támesis', 'destino': 'Tarso', 'distancia_km': 48.0, 'tiempo_minutos': 76},
    {'origen': 'Támesis', 'destino': 'Titiribí', 'distancia_km': 83.8, 'tiempo_minutos': 143},
    {'origen': 'Támesis', 'destino': 'Urrao', 'distancia_km': 141.0, 'tiempo_minutos': 223},
    {'origen': 'Támesis', 'destino': 'Valparaíso', 'distancia_km': 27.0, 'tiempo_minutos': 46},
    {'origen': 'Támesis', 'destino': 'Venecia', 'distancia_km': 62.2, 'tiempo_minutos': 116},
    {'origen': 'Támesis', 'destino': 'Carmen de Atrato', 'distancia_km': 113.0, 'tiempo_minutos': 169},
    {'origen': 'Tarso', 'destino': 'Amagá', 'distancia_km': 64.1, 'tiempo_minutos': 143},
    {'origen': 'Tarso', 'destino': 'Andes', 'distancia_km': 44.3, 'tiempo_minutos': 98},
    {'origen': 'Tarso', 'destino': 'Angelópolis', 'distancia_km': 79.7, 'tiempo_minutos': 181},
    {'origen': 'Tarso', 'destino': 'Betania', 'distancia_km': 45.9, 'tiempo_minutos': 100},
    {'origen': 'Tarso', 'destino': 'Betulia', 'distancia_km': 78.7, 'tiempo_minutos': 146},
    {'origen': 'Tarso', 'destino': 'Caramanta', 'distancia_km': 87.9, 'tiempo_minutos': 122},
    {'origen': 'Tarso', 'destino': 'Ciudad Bolívar', 'distancia_km': 48.7, 'tiempo_minutos': 93},
    {'origen': 'Tarso', 'destino': 'Concordia', 'distancia_km': 44.2, 'tiempo_minutos': 95},
    {'origen': 'Tarso', 'destino': 'Fredonia', 'distancia_km': 59.7, 'tiempo_minutos': 87},
    {'origen': 'Tarso', 'destino': 'Hispania', 'distancia_km': 41.0, 'tiempo_minutos': 84},
    {'origen': 'Tarso', 'destino': 'Jardín', 'distancia_km': 59.0, 'tiempo_minutos': 118},
    {'origen': 'Tarso', 'destino': 'Jericó', 'distancia_km': 24.1, 'tiempo_minutos': 43},
    {'origen': 'Tarso', 'destino': 'La Pintada', 'distancia_km': 53.0, 'tiempo_minutos': 65},
    {'origen': 'Tarso', 'destino': 'Montebello', 'distancia_km': 106.0, 'tiempo_minutos': 170},
    {'origen': 'Tarso', 'destino': 'Pueblorrico', 'distancia_km': 13.9, 'tiempo_minutos': 29},
    {'origen': 'Tarso', 'destino': 'Salgar', 'distancia_km': 38.0, 'tiempo_minutos': 80},
    {'origen': 'Tarso', 'destino': 'Santa Bárbara', 'distancia_km': 78.3, 'tiempo_minutos': 115},
    {'origen': 'Tarso', 'destino': 'Támesis', 'distancia_km': 48.4, 'tiempo_minutos': 107},
    {'origen': 'Tarso', 'destino': 'Titiribí', 'distancia_km': 56.5, 'tiempo_minutos': 140},
    {'origen': 'Tarso', 'destino': 'Urrao', 'distancia_km': 110.0, 'tiempo_minutos': 206},
    {'origen': 'Tarso', 'destino': 'Valparaíso', 'distancia_km': 71.3, 'tiempo_minutos': 91},
    {'origen': 'Tarso', 'destino': 'Venecia', 'distancia_km': 42.4, 'tiempo_minutos': 102},
    {'origen': 'Tarso', 'destino': 'Carmen de Atrato', 'distancia_km': 82.0, 'tiempo_minutos': 154},
    {'origen': 'Titiribí', 'destino': 'Amagá', 'distancia_km': 19.4, 'tiempo_minutos': 35},
    {'origen': 'Titiribí', 'destino': 'Andes', 'distancia_km': 80.3, 'tiempo_minutos': 140},
    {'origen': 'Titiribí', 'destino': 'Angelópolis', 'distancia_km': 37.7, 'tiempo_minutos': 79},
    {'origen': 'Titiribí', 'destino': 'Betania', 'distancia_km': 79.1, 'tiempo_minutos': 140},
    {'origen': 'Titiribí', 'destino': 'Betulia', 'distancia_km': 89.4, 'tiempo_minutos': 166},
    {'origen': 'Titiribí', 'destino': 'Caramanta', 'distancia_km': 114.0, 'tiempo_minutos': 186},
    {'origen': 'Titiribí', 'destino': 'Ciudad Bolívar', 'distancia_km': 68.7, 'tiempo_minutos': 124},
    {'origen': 'Titiribí', 'destino': 'Concordia', 'distancia_km': 64.2, 'tiempo_minutos': 136},
    {'origen': 'Titiribí', 'destino': 'Fredonia', 'distancia_km': 38.4, 'tiempo_minutos': 71},
    {'origen': 'Titiribí', 'destino': 'Hispania', 'distancia_km': 61.0, 'tiempo_minutos': 115},
    {'origen': 'Titiribí', 'destino': 'Jardín', 'distancia_km': 94.9, 'tiempo_minutos': 160},
    {'origen': 'Titiribí', 'destino': 'Jericó', 'distancia_km': 71.9, 'tiempo_minutos': 126},
    {'origen': 'Titiribí', 'destino': 'La Pintada', 'distancia_km': 79.4, 'tiempo_minutos': 128},
    {'origen': 'Titiribí', 'destino': 'Montebello', 'distancia_km': 62.7, 'tiempo_minutos': 112},
    {'origen': 'Titiribí', 'destino': 'Pueblorrico', 'distancia_km': 75.0, 'tiempo_minutos': 134},
    {'origen': 'Titiribí', 'destino': 'Salgar', 'distancia_km': 58.0, 'tiempo_minutos': 110},
    {'origen': 'Titiribí', 'destino': 'Santa Bárbara', 'distancia_km': 59.9, 'tiempo_minutos': 101},
    {'origen': 'Titiribí', 'destino': 'Támesis', 'distancia_km': 83.4, 'tiempo_minutos': 140},
    {'origen': 'Titiribí', 'destino': 'Tarso', 'distancia_km': 61.1, 'tiempo_minutos': 105},
    {'origen': 'Titiribí', 'destino': 'Urrao', 'distancia_km': 123.0, 'tiempo_minutos': 227},
    {'origen': 'Titiribí', 'destino': 'Valparaíso', 'distancia_km': 97.7, 'tiempo_minutos': 155},
    {'origen': 'Titiribí', 'destino': 'Venecia', 'distancia_km': 41.4, 'tiempo_minutos': 78},
    {'origen': 'Titiribí', 'destino': 'Carmen de Atrato', 'distancia_km': 102.0, 'tiempo_minutos': 181},
    {'origen': 'Urrao', 'destino': 'Amagá', 'distancia_km': 130.0, 'tiempo_minutos': 228},
    {'origen': 'Urrao', 'destino': 'Andes', 'distancia_km': 122.0, 'tiempo_minutos': 196},
    {'origen': 'Urrao', 'destino': 'Angelópolis', 'distancia_km': 146.0, 'tiempo_minutos': 267},
    {'origen': 'Urrao', 'destino': 'Betania', 'distancia_km': 120.0, 'tiempo_minutos': 196},
    {'origen': 'Urrao', 'destino': 'Betulia', 'distancia_km': 38.3, 'tiempo_minutos': 126},
    {'origen': 'Urrao', 'destino': 'Caramanta', 'distancia_km': 168.0, 'tiempo_minutos': 250},
    {'origen': 'Urrao', 'destino': 'Ciudad Bolívar', 'distancia_km': 110.0, 'tiempo_minutos': 180},
    {'origen': 'Urrao', 'destino': 'Concordia', 'distancia_km': 73.5, 'tiempo_minutos': 129},
    {'origen': 'Urrao', 'destino': 'Fredonia', 'distancia_km': 140.0, 'tiempo_minutos': 214},
    {'origen': 'Urrao', 'destino': 'Hispania', 'distancia_km': 102.0, 'tiempo_minutos': 170},
    {'origen': 'Urrao', 'destino': 'Jardín', 'distancia_km': 136.0, 'tiempo_minutos': 216},
    {'origen': 'Urrao', 'destino': 'Jericó', 'distancia_km': 129.0, 'tiempo_minutos': 206},
    {'origen': 'Urrao', 'destino': 'La Pintada', 'distancia_km': 133.0, 'tiempo_minutos': 192},
    {'origen': 'Urrao', 'destino': 'Montebello', 'distancia_km': 185.0, 'tiempo_minutos': 296},
    {'origen': 'Urrao', 'destino': 'Pueblorrico', 'distancia_km': 133.0, 'tiempo_minutos': 212},
    {'origen': 'Urrao', 'destino': 'Salgar', 'distancia_km': 73.7, 'tiempo_minutos': 128},
    {'origen': 'Urrao', 'destino': 'Santa Bárbara', 'distancia_km': 158.0, 'tiempo_minutos': 242},
    {'origen': 'Urrao', 'destino': 'Támesis', 'distancia_km': 141.0, 'tiempo_minutos': 221},
    {'origen': 'Urrao', 'destino': 'Tarso', 'distancia_km': 119.0, 'tiempo_minutos': 185},
    {'origen': 'Urrao', 'destino': 'Titiribí', 'distancia_km': 123.0, 'tiempo_minutos': 227},
    {'origen': 'Urrao', 'destino': 'Valparaíso', 'distancia_km': 151.0, 'tiempo_minutos': 219},
    {'origen': 'Urrao', 'destino': 'Venecia', 'distancia_km': 109.0, 'tiempo_minutos': 188},
    {'origen': 'Urrao', 'destino': 'Carmen de Atrato', 'distancia_km': 143.0, 'tiempo_minutos': 238},
    {'origen': 'Valparaíso', 'destino': 'Amagá', 'distancia_km': 82.7, 'tiempo_minutos': 124},
    {'origen': 'Valparaíso', 'destino': 'Andes', 'distancia_km': 105.0, 'tiempo_minutos': 127},
    {'origen': 'Valparaíso', 'destino': 'Angelópolis', 'distancia_km': 98.4, 'tiempo_minutos': 163},
    {'origen': 'Valparaíso', 'destino': 'Betania', 'distancia_km': 104.0, 'tiempo_minutos': 127},
    {'origen': 'Valparaíso', 'destino': 'Betulia', 'distancia_km': 124.0, 'tiempo_minutos': 163},
    {'origen': 'Valparaíso', 'destino': 'Caramanta', 'distancia_km': 17.0, 'tiempo_minutos': 34},
    {'origen': 'Valparaíso', 'destino': 'Ciudad Bolívar', 'distancia_km': 93.6, 'tiempo_minutos': 111},
    {'origen': 'Valparaíso', 'destino': 'Concordia', 'distancia_km': 96.6, 'tiempo_minutos': 132},
    {'origen': 'Valparaíso', 'destino': 'Fredonia', 'distancia_km': 63.2, 'tiempo_minutos': 88},
    {'origen': 'Valparaíso', 'destino': 'Hispania', 'distancia_km': 85.9, 'tiempo_minutos': 101},
    {'origen': 'Valparaíso', 'destino': 'Jardín', 'distancia_km': 120.0, 'tiempo_minutos': 147},
    {'origen': 'Valparaíso', 'destino': 'Jericó', 'distancia_km': 72.7, 'tiempo_minutos': 96},
    {'origen': 'Valparaíso', 'destino': 'La Pintada', 'distancia_km': 22.8, 'tiempo_minutos': 36},
    {'origen': 'Valparaíso', 'destino': 'Montebello', 'distancia_km': 75.2, 'tiempo_minutos': 141},
    {'origen': 'Valparaíso', 'destino': 'Pueblorrico', 'distancia_km': 75.8, 'tiempo_minutos': 104},
    {'origen': 'Valparaíso', 'destino': 'Salgar', 'distancia_km': 82.9, 'tiempo_minutos': 97},
    {'origen': 'Valparaíso', 'destino': 'Santa Bárbara', 'distancia_km': 48.0, 'tiempo_minutos': 85},
    {'origen': 'Valparaíso', 'destino': 'Támesis', 'distancia_km': 27.0, 'tiempo_minutos': 48},
    {'origen': 'Valparaíso', 'destino': 'Tarso', 'distancia_km': 61.9, 'tiempo_minutos': 75},
    {'origen': 'Valparaíso', 'destino': 'Titiribí', 'distancia_km': 97.9, 'tiempo_minutos': 142},
    {'origen': 'Valparaíso', 'destino': 'Urrao', 'distancia_km': 155.0, 'tiempo_minutos': 222},
    {'origen': 'Valparaíso', 'destino': 'Venecia', 'distancia_km': 76.1, 'tiempo_minutos': 117},
    {'origen': 'Valparaíso', 'destino': 'Carmen de Atrato', 'distancia_km': 127.0, 'tiempo_minutos': 168},
    {'origen': 'Venecia', 'destino': 'Amagá', 'distancia_km': 22.2, 'tiempo_minutos': 43},
    {'origen': 'Venecia', 'destino': 'Andes', 'distancia_km': 66.0, 'tiempo_minutos': 106},
    {'origen': 'Venecia', 'destino': 'Angelópolis', 'distancia_km': 38.0, 'tiempo_minutos': 82},
    {'origen': 'Venecia', 'destino': 'Betania', 'distancia_km': 64.8, 'tiempo_minutos': 106},
    {'origen': 'Venecia', 'destino': 'Betulia', 'distancia_km': 75.0, 'tiempo_minutos': 131},
    {'origen': 'Venecia', 'destino': 'Caramanta', 'distancia_km': 88.7, 'tiempo_minutos': 142},
    {'origen': 'Venecia', 'destino': 'Ciudad Bolívar', 'distancia_km': 54.4, 'tiempo_minutos': 89},
    {'origen': 'Venecia', 'destino': 'Concordia', 'distancia_km': 49.9, 'tiempo_minutos': 102},
    {'origen': 'Venecia', 'destino': 'Fredonia', 'distancia_km': 12.7, 'tiempo_minutos': 29},
    {'origen': 'Venecia', 'destino': 'Hispania', 'distancia_km': 46.7, 'tiempo_minutos': 80},
    {'origen': 'Venecia', 'destino': 'Jardín', 'distancia_km': 80.6, 'tiempo_minutos': 125},
    {'origen': 'Venecia', 'destino': 'Jericó', 'distancia_km': 67.1, 'tiempo_minutos': 103},
    {'origen': 'Venecia', 'destino': 'La Pintada', 'distancia_km': 53.8, 'tiempo_minutos': 85},
    {'origen': 'Venecia', 'destino': 'Montebello', 'distancia_km': 63.0, 'tiempo_minutos': 116},
    {'origen': 'Venecia', 'destino': 'Pueblorrico', 'distancia_km': 70.2, 'tiempo_minutos': 111},
    {'origen': 'Venecia', 'destino': 'Salgar', 'distancia_km': 43.7, 'tiempo_minutos': 76},
    {'origen': 'Venecia', 'destino': 'Santa Bárbara', 'distancia_km': 60.2, 'tiempo_minutos': 104},
    {'origen': 'Venecia', 'destino': 'Támesis', 'distancia_km': 61.8, 'tiempo_minutos': 115},
    {'origen': 'Venecia', 'destino': 'Tarso', 'distancia_km': 56.2, 'tiempo_minutos': 83},
    {'origen': 'Venecia', 'destino': 'Titiribí', 'distancia_km': 40.9, 'tiempo_minutos': 76},
    {'origen': 'Venecia', 'destino': 'Urrao', 'distancia_km': 108.0, 'tiempo_minutos': 193},
    {'origen': 'Venecia', 'destino': 'Valparaíso', 'distancia_km': 72.0, 'tiempo_minutos': 112},
    {'origen': 'Venecia', 'destino': 'Carmen de Atrato', 'distancia_km': 87.7, 'tiempo_minutos': 150},
    {'origen': 'Carmen de Atrato', 'destino': 'Amagá', 'distancia_km': 98.9, 'tiempo_minutos': 153},
    {'origen': 'Carmen de Atrato', 'destino': 'Andes', 'distancia_km': 78.1, 'tiempo_minutos': 118},
    {'origen': 'Carmen de Atrato', 'destino': 'Angelópolis', 'distancia_km': 114.0, 'tiempo_minutos': 189},
    {'origen': 'Carmen de Atrato', 'destino': 'Betania', 'distancia_km': 76.9, 'tiempo_minutos': 118},
    {'origen': 'Carmen de Atrato', 'destino': 'Betulia', 'distancia_km': 103.0, 'tiempo_minutos': 181},
    {'origen': 'Carmen de Atrato', 'destino': 'Caramanta', 'distancia_km': 140.0, 'tiempo_minutos': 199},
    {'origen': 'Carmen de Atrato', 'destino': 'Ciudad Bolívar', 'distancia_km': 33.8, 'tiempo_minutos': 62},
    {'origen': 'Carmen de Atrato', 'destino': 'Concordia', 'distancia_km': 97.2, 'tiempo_minutos': 158},
    {'origen': 'Carmen de Atrato', 'destino': 'Fredonia', 'distancia_km': 112.0, 'tiempo_minutos': 164},
    {'origen': 'Carmen de Atrato', 'destino': 'Hispania', 'distancia_km': 58.9, 'tiempo_minutos': 93},
    {'origen': 'Carmen de Atrato', 'destino': 'Jardín', 'distancia_km': 92.7, 'tiempo_minutos': 138},
    {'origen': 'Carmen de Atrato', 'destino': 'Jericó', 'distancia_km': 101.0, 'tiempo_minutos': 155},
    {'origen': 'Carmen de Atrato', 'destino': 'La Pintada', 'distancia_km': 105.0, 'tiempo_minutos': 141},
    {'origen': 'Carmen de Atrato', 'destino': 'Montebello', 'distancia_km': 139.0, 'tiempo_minutos': 225},
    {'origen': 'Carmen de Atrato', 'destino': 'Pueblorrico', 'distancia_km': 80.7, 'tiempo_minutos': 147},
    {'origen': 'Carmen de Atrato', 'destino': 'Salgar', 'distancia_km': 69.7, 'tiempo_minutos': 109},
    {'origen': 'Carmen de Atrato', 'destino': 'Santa Bárbara', 'distancia_km': 130.0, 'tiempo_minutos': 193},
    {'origen': 'Carmen de Atrato', 'destino': 'Támesis', 'distancia_km': 113.0, 'tiempo_minutos': 170},
    {'origen': 'Carmen de Atrato', 'destino': 'Tarso', 'distancia_km': 90.4, 'tiempo_minutos': 135},
    {'origen': 'Carmen de Atrato', 'destino': 'Titiribí', 'distancia_km': 102.0, 'tiempo_minutos': 168},
    {'origen': 'Carmen de Atrato', 'destino': 'Urrao', 'distancia_km': 143.0, 'tiempo_minutos': 242},
    {'origen': 'Carmen de Atrato', 'destino': 'Valparaíso', 'distancia_km': 123.0, 'tiempo_minutos': 168},
    {'origen': 'Carmen de Atrato', 'destino': 'Venecia', 'distancia_km': 88.0, 'tiempo_minutos': 146},
]
