# Generated by Django 5.0 on 2025-11-11 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FactorPrestacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("comercial", "Comercial"),
                            ("administrativo", "Administrativo"),
                            ("logistico", "Logístico"),
                            ("aprendiz_sena", "Aprendiz SENA"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "salud",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Salud (%)"
                    ),
                ),
                (
                    "pension",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Pensión (%)"
                    ),
                ),
                (
                    "arl",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="ARL (%)"
                    ),
                ),
                (
                    "caja_compensacion",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        verbose_name="Caja Compensación (%)",
                    ),
                ),
                (
                    "icbf",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="ICBF (%)"
                    ),
                ),
                (
                    "sena",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="SENA (%)"
                    ),
                ),
                (
                    "cesantias",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Cesantías (%)"
                    ),
                ),
                (
                    "intereses_cesantias",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        verbose_name="Int. Cesantías (%)",
                    ),
                ),
                (
                    "prima",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Prima (%)"
                    ),
                ),
                (
                    "vacaciones",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Vacaciones (%)"
                    ),
                ),
                (
                    "factor_total",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Factor Total (%)"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Factor Prestacional",
                "verbose_name_plural": "Factores Prestacionales",
                "db_table": "dxv_factor_prestacional",
                "ordering": ["perfil"],
            },
        ),
        migrations.CreateModel(
            name="GastoAdministrativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre/Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arriendo_oficina", "Arriendo de Oficina"),
                            ("servicios_publicos", "Servicios Públicos"),
                            ("internet_telefonia", "Internet y Telefonía"),
                            ("vigilancia", "Vigilancia y Seguridad"),
                            ("aseo_cafeteria", "Aseo y Cafetería"),
                            ("papeleria", "Papelería y Útiles"),
                            ("software_licencias", "Software y Licencias"),
                            ("seguros", "Seguros"),
                            ("impuestos_predial", "Impuestos Prediales"),
                            ("otros", "Otros Gastos Administrativos"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Gasto",
                    ),
                ),
                (
                    "valor_mensual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Mensual"
                    ),
                ),
                (
                    "criterio_prorrateo",
                    models.CharField(
                        choices=[
                            ("ventas", "Por Ventas"),
                            ("headcount", "Por Headcount"),
                            ("equitativo", "Equitativo"),
                        ],
                        default="ventas",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gasto Administrativo",
                "verbose_name_plural": "Gastos Administrativos",
                "db_table": "dxv_gasto_administrativo",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Impuesto"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("iva", "IVA"),
                            ("renta", "Impuesto de Renta"),
                            ("ica", "ICA (Industria y Comercio)"),
                            ("retefuente", "Retención en la Fuente"),
                            ("reteica", "Retención ICA"),
                            ("predial", "Predial"),
                            ("vehiculos", "Impuesto Vehículos"),
                            ("estampillas", "Estampillas"),
                            ("otros", "Otros Impuestos"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "aplicacion",
                    models.CharField(
                        choices=[
                            ("sobre_ventas", "Sobre Ventas"),
                            ("sobre_utilidad", "Sobre Utilidad"),
                            ("fijo", "Valor Fijo"),
                        ],
                        max_length=20,
                        verbose_name="Aplicación",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Para impuestos sobre ventas o utilidad",
                        max_digits=6,
                        null=True,
                        verbose_name="Porcentaje (%)",
                    ),
                ),
                (
                    "valor_fijo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para impuestos de valor fijo",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Fijo",
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        default="mensual",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "db_table": "dxv_impuesto",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID Marca"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "color",
                    models.CharField(
                        default="#1f77b4", max_length=7, verbose_name="Color (hex)"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "dxv_marca",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParametrosMacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField(unique=True, verbose_name="Año")),
                (
                    "ipc",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="IPC (%)"
                    ),
                ),
                (
                    "ipt",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="IPT (%)"
                    ),
                ),
                (
                    "salario_minimo_legal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Salario Mínimo Legal",
                    ),
                ),
                (
                    "subsidio_transporte",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Subsidio de Transporte",
                    ),
                ),
                (
                    "incremento_salarios",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Incremento Salarios (%)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parámetros Macroeconómicos",
                "verbose_name_plural": "Parámetros Macroeconómicos",
                "db_table": "dxv_parametros_macro",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="PersonalAdministrativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre/Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gerente_general", "Gerente General"),
                            ("contador", "Contador"),
                            ("auxiliar_administrativo", "Auxiliar Administrativo"),
                            ("servicios_generales", "Servicios Generales"),
                            ("practicante_sena", "Practicante SENA"),
                            ("asistente_gerencia", "Asistente de Gerencia"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Personal",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[("nomina", "Nómina"), ("honorarios", "Honorarios")],
                        default="nomina",
                        max_length=20,
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salario Base",
                    ),
                ),
                (
                    "perfil_prestacional",
                    models.CharField(
                        default="administrativo", max_length=20, verbose_name="Perfil"
                    ),
                ),
                (
                    "honorarios_mensuales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Honorarios Mensuales",
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[("compartido", "Compartido entre marcas")],
                        default="compartido",
                        max_length=20,
                    ),
                ),
                (
                    "criterio_prorrateo",
                    models.CharField(
                        choices=[
                            ("ventas", "Por Ventas"),
                            ("headcount", "Por Headcount"),
                            ("equitativo", "Equitativo"),
                        ],
                        default="equitativo",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Administrativo",
                "verbose_name_plural": "Personal Administrativo",
                "db_table": "dxv_personal_administrativo",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="GastoLogistico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre/Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mantenimiento_vehiculos", "Mantenimiento de Vehículos"),
                            ("seguros_carga", "Seguros de Carga"),
                            ("peajes", "Peajes y Parqueaderos"),
                            ("equipos_carga", "Equipos de Carga (Estibas, Carretas)"),
                            ("combustible_adicional", "Combustible Adicional"),
                            ("neumaticos", "Neumáticos y Repuestos"),
                            ("bodegaje", "Bodegaje Externo"),
                            ("equipos_bodega", "Equipos de Bodega"),
                            ("embalaje", "Material de Embalaje"),
                            ("otros", "Otros Gastos Logísticos"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Gasto",
                    ),
                ),
                (
                    "valor_mensual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Mensual"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos_logisticos",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Logístico",
                "verbose_name_plural": "Gastos Logísticos",
                "db_table": "dxv_gasto_logistico",
                "ordering": ["marca", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="GastoComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre/Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comisiones", "Comisiones de Ventas"),
                            ("merchandising", "Materiales de Merchandising"),
                            ("capacitacion", "Capacitación y Entrenamiento"),
                            ("eventos", "Eventos Comerciales"),
                            (
                                "herramientas_digitales",
                                "Herramientas Digitales (CRM, Apps)",
                            ),
                            ("transporte_vendedores", "Transporte de Vendedores"),
                            ("viaticos", "Viáticos"),
                            ("publicidad", "Publicidad y Marketing"),
                            ("muestras", "Muestras y Degustaciones"),
                            ("otros", "Otros Gastos Comerciales"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Gasto",
                    ),
                ),
                (
                    "valor_mensual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Mensual"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos_comerciales",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Comercial",
                "verbose_name_plural": "Gastos Comerciales",
                "db_table": "dxv_gasto_comercial",
                "ordering": ["marca", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="PersonalComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vendedor_geografico", "Vendedor Geográfico"),
                            ("vendedor_senior", "Vendedor Senior"),
                            ("vendedor_minimercado", "Vendedor Minimercado"),
                            ("supervisor", "Supervisor"),
                            ("coordinador_comercial", "Coordinador Comercial"),
                            ("auxiliar_informacion", "Auxiliar de Información"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Personal",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salario Base"
                    ),
                ),
                (
                    "perfil_prestacional",
                    models.CharField(
                        choices=[
                            ("comercial", "Comercial"),
                            ("administrativo", "Administrativo"),
                        ],
                        default="comercial",
                        max_length=20,
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("compartido", "Compartido"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "auxilio_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Auxilio Adicional",
                    ),
                ),
                (
                    "porcentaje_dedicacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solo para asignación compartida (0.0 - 1.0)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "criterio_prorrateo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ventas", "Por Ventas"),
                            ("volumen", "Por Volumen"),
                            ("headcount", "Por Headcount"),
                            ("equitativo", "Equitativo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_comercial",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Comercial",
                "verbose_name_plural": "Personal Comercial",
                "db_table": "dxv_personal_comercial",
                "ordering": ["marca", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="PersonalLogistico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conductor", "Conductor"),
                            ("auxiliar_entrega", "Auxiliar de Entrega"),
                            ("coordinador_logistica", "Coordinador Logística"),
                            ("supervisor_bodega", "Supervisor de Bodega"),
                            ("operario_bodega", "Operario de Bodega"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Personal",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salario Base"
                    ),
                ),
                (
                    "perfil_prestacional",
                    models.CharField(
                        choices=[
                            ("logistico", "Logístico"),
                            ("administrativo", "Administrativo"),
                        ],
                        default="logistico",
                        max_length=20,
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("compartido", "Compartido"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_dedicacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "criterio_prorrateo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ventas", "Por Ventas"),
                            ("volumen", "Por Volumen"),
                            ("headcount", "Por Headcount"),
                            ("equitativo", "Equitativo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_logistico",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Logístico",
                "verbose_name_plural": "Personal Logístico",
                "db_table": "dxv_personal_logistico",
                "ordering": ["marca", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("bicicleta_electrica", "Bicicleta Eléctrica"),
                            ("motocarro", "Motocarro"),
                            ("minitruck", "Minitruck"),
                            ("pickup", "Pickup"),
                            ("nhr", "NHR"),
                            ("nkr", "NKR"),
                            ("npr", "NPR"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Vehículo",
                    ),
                ),
                (
                    "esquema",
                    models.CharField(
                        choices=[
                            ("renting", "Renting"),
                            ("tradicional", "Tradicional (Propio)"),
                        ],
                        max_length=20,
                        verbose_name="Esquema",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "asignacion",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("compartido", "Compartido"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "kilometraje_promedio_mensual",
                    models.IntegerField(
                        default=3000, verbose_name="Km Promedio Mensual"
                    ),
                ),
                (
                    "porcentaje_uso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "criterio_prorrateo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("volumen", "Por Volumen"),
                            ("ventas", "Por Ventas"),
                            ("uso_real", "Por Uso Real"),
                        ],
                        default="volumen",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "dxv_vehiculo",
                "ordering": ["marca", "tipo_vehiculo"],
            },
        ),
        migrations.CreateModel(
            name="VolumenOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pallets_mensuales",
                    models.IntegerField(default=0, verbose_name="Pallets Mensuales"),
                ),
                (
                    "metros_cubicos_mensuales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="M³ Mensuales",
                    ),
                ),
                (
                    "toneladas_mensuales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Toneladas Mensuales",
                    ),
                ),
                (
                    "entregas_mensuales",
                    models.IntegerField(default=0, verbose_name="Entregas Mensuales"),
                ),
                (
                    "rutas_activas",
                    models.IntegerField(default=0, verbose_name="Rutas Activas"),
                ),
                (
                    "zonas_cobertura",
                    models.IntegerField(default=0, verbose_name="Zonas de Cobertura"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumen_operacion",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volumen de Operación",
                "verbose_name_plural": "Volúmenes de Operación",
                "db_table": "dxv_volumen_operacion",
            },
        ),
        migrations.CreateModel(
            name="ProyeccionVentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("enero", "Enero"),
                            ("febrero", "Febrero"),
                            ("marzo", "Marzo"),
                            ("abril", "Abril"),
                            ("mayo", "Mayo"),
                            ("junio", "Junio"),
                            ("julio", "Julio"),
                            ("agosto", "Agosto"),
                            ("septiembre", "Septiembre"),
                            ("octubre", "Octubre"),
                            ("noviembre", "Noviembre"),
                            ("diciembre", "Diciembre"),
                        ],
                        max_length=20,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "ventas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Ventas Proyectadas",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyecciones_ventas",
                        to="core.marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyección de Ventas",
                "verbose_name_plural": "Proyecciones de Ventas",
                "db_table": "dxv_proyeccion_ventas",
                "ordering": ["marca", "anio", "mes"],
                "unique_together": {("marca", "anio", "mes")},
            },
        ),
    ]
