# Generated by Django 5.0 on 2025-11-21 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionDescuentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_rebate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de rebate sobre ventas netas (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rebate (%)",
                    ),
                ),
                (
                    "aplica_descuento_financiero",
                    models.BooleanField(
                        default=False, verbose_name="¿Aplica Descuento Financiero?"
                    ),
                ),
                (
                    "porcentaje_descuento_financiero",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de descuento por pronto pago (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Descuento Financiero (%)",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_descuentos",
                        to="core.marca",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Descuentos",
                "verbose_name_plural": "Configuraciones de Descuentos",
                "db_table": "dxv_configuracion_descuentos",
                "ordering": ["marca"],
            },
        ),
        migrations.CreateModel(
            name="TramoDescuentoFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Orden del tramo (1, 2, 3...)", verbose_name="Orden"
                    ),
                ),
                (
                    "porcentaje_ventas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje del total de ventas (ej: 50%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% de Ventas",
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de descuento aplicado (ej: 19%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% de Descuento",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "configuracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramos",
                        to="core.configuraciondescuentos",
                        verbose_name="Configuración",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tramo de Descuento",
                "verbose_name_plural": "Tramos de Descuento",
                "db_table": "dxv_tramo_descuento_factura",
                "ordering": ["configuracion", "orden"],
                "unique_together": {("configuracion", "orden")},
            },
        ),
    ]
