# Generated by Django 4.2.26 on 2025-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_initial_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaRecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True, verbose_name='Año')),
                ('valor_dotacion_completa', models.DecimalField(decimal_places=2, help_text='Costo unitario de una dotación completa', max_digits=12, verbose_name='Valor Dotación Completa')),
                ('frecuencia_dotacion_anual', models.IntegerField(default=3, help_text='Cuántas veces al año se entrega dotación', verbose_name='Frecuencia Anual')),
                ('tope_smlv_dotacion', models.DecimalField(decimal_places=2, default=2.0, help_text='Se entrega dotación a quienes ganen menos de X salarios mínimos', max_digits=4, verbose_name='Tope SMLV para Dotación')),
                ('valor_epp_anual_comercial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor EPP Anual (Comercial)')),
                ('frecuencia_epp_anual', models.IntegerField(default=1, verbose_name='Frecuencia EPP Anual')),
                ('costo_examen_ingreso_comercial', models.DecimalField(decimal_places=2, default=0, help_text='Para vendedores, supervisores, etc.', max_digits=12, verbose_name='Costo Examen Ingreso (Comercial)')),
                ('costo_examen_ingreso_operativo', models.DecimalField(decimal_places=2, default=0, help_text='Para administrativos, logísticos, etc.', max_digits=12, verbose_name='Costo Examen Ingreso (Otros)')),
                ('costo_examen_periodico_comercial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Examen Periódico (Comercial)')),
                ('costo_examen_periodico_operativo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Examen Periódico (Otros)')),
                ('tasa_rotacion_anual', models.DecimalField(decimal_places=2, help_text='Porcentaje de rotación estimado (para calcular exámenes de ingreso)', max_digits=5, verbose_name='Tasa de Rotación Anual (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de RRHH',
                'verbose_name_plural': 'Políticas de RRHH',
                'db_table': 'dxv_politica_rrhh',
                'ordering': ['-anio'],
            },
        ),
        migrations.AlterField(
            model_name='gastoadministrativo',
            name='tipo',
            field=models.CharField(choices=[('arriendo_oficina', 'Arriendo de Oficina'), ('servicios_publicos', 'Servicios Públicos'), ('internet_telefonia', 'Internet y Telefonía'), ('vigilancia', 'Vigilancia y Seguridad'), ('aseo_cafeteria', 'Aseo y Cafetería'), ('papeleria', 'Papelería y Útiles'), ('software_licencias', 'Software y Licencias'), ('facturacion_electronica', 'Facturación Electrónica'), ('seguros', 'Seguros'), ('servicios_legales', 'Servicios Jurídicos y Legales'), ('mantenimiento_locativo', 'Mantenimiento Locativo'), ('gastos_financieros', 'Gastos Bancarios y Financieros'), ('bienestar', 'Bienestar y Clima Laboral'), ('dotacion', 'Dotación y EPP'), ('examenes', 'Exámenes Médicos'), ('telefonia_celular', 'Telefonía Celular y Datos'), ('otros', 'Otros Gastos Administrativos')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
        migrations.AlterField(
            model_name='gastocomercial',
            name='tipo',
            field=models.CharField(choices=[('comisiones', 'Comisiones de Ventas'), ('merchandising', 'Materiales de Merchandising'), ('capacitacion', 'Capacitación y Entrenamiento'), ('eventos', 'Eventos Comerciales'), ('herramientas_digitales', 'Herramientas Digitales (CRM, Apps)'), ('transporte_vendedores', 'Transporte de Vendedores'), ('viaticos', 'Viáticos'), ('publicidad', 'Publicidad y Marketing'), ('muestras', 'Muestras y Degustaciones'), ('dotacion', 'Dotación y EPP'), ('epp', 'EPP (Solo Comercial)'), ('examenes', 'Exámenes Médicos'), ('telefonia_celular', 'Telefonía Celular y Datos'), ('otros', 'Otros Gastos Comerciales')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
        migrations.AlterField(
            model_name='gastologistico',
            name='tipo',
            field=models.CharField(choices=[('mantenimiento_vehiculos', 'Mantenimiento de Vehículos'), ('seguros_carga', 'Seguros de Carga'), ('peajes', 'Peajes y Parqueaderos'), ('equipos_carga', 'Equipos de Carga (Estibas, Carretas)'), ('combustible_adicional', 'Combustible Adicional'), ('neumaticos', 'Neumáticos y Repuestos'), ('bodegaje', 'Bodegaje Externo'), ('equipos_bodega', 'Equipos de Bodega'), ('embalaje', 'Material de Embalaje'), ('arriendo_bodega', 'Arriendo Bodega y CEDI'), ('servicios_publicos_bodega', 'Servicios Públicos Bodega'), ('internet_bodega', 'Internet y Conectividad Bodega'), ('dotacion', 'Dotación y EPP'), ('examenes', 'Exámenes Médicos'), ('telefonia_celular', 'Telefonía Celular y Datos'), ('otros', 'Otros Gastos Logísticos')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='perfil_prestacional',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('aprendiz_sena', 'Aprendiz SENA')], default='administrativo', max_length=20, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='tipo',
            field=models.CharField(choices=[('gerente_general', 'Gerente General'), ('contador', 'Contador'), ('revisor_fiscal', 'Revisor Fiscal'), ('sgsst', 'Seguridad y Salud en el Trabajo (SGSST)'), ('pesv', 'Plan Estratégico de Seguridad Vial (PESV)'), ('auxiliar_administrativo', 'Auxiliar Administrativo'), ('servicios_generales', 'Servicios Generales'), ('practicante_sena', 'Practicante SENA'), ('asistente_gerencia', 'Asistente de Gerencia'), ('desarrollador_talento', 'Desarrollador de Talento')], max_length=50, verbose_name='Tipo de Personal'),
        ),
    ]
