# Generated by Django 4.2.26 on 2025-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_politicarecursoshumanos_gastocomercial_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='costo_lavado_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lavado Mensual'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_mantenimiento_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mantenimiento Mensual'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_monitoreo_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monitoreo Satelital (GPS)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_parqueadero_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Parqueadero Mensual'),
        ),
        migrations.AlterField(
            model_name='gastologistico',
            name='tipo',
            field=models.CharField(choices=[('mantenimiento_vehiculos', 'Mantenimiento de Vehículos'), ('seguros_carga', 'Seguros de Carga'), ('peajes', 'Peajes y Parqueaderos'), ('equipos_carga', 'Equipos de Carga (Estibas, Carretas)'), ('equipos_carga', 'Equipos de Carga (Estibas, Carretas)'), ('combustible', 'Combustible'), ('neumaticos', 'Neumáticos y Repuestos'), ('flete_tercero', 'Flete Transporte (Tercero)'), ('canon_renting', 'Canon Renting'), ('depreciacion_vehiculo', 'Depreciación Vehículos'), ('lavado_vehiculos', 'Aseo y Limpieza Vehículos'), ('parqueadero_vehiculos', 'Parqueaderos'), ('monitoreo_satelital', 'Monitoreo Satelital (GPS)'), ('bodegaje', 'Bodegaje Externo'), ('equipos_bodega', 'Equipos de Bodega'), ('embalaje', 'Material de Embalaje'), ('arriendo_bodega', 'Arriendo Bodega y CEDI'), ('servicios_publicos_bodega', 'Servicios Públicos Bodega'), ('internet_bodega', 'Internet y Conectividad Bodega'), ('dotacion', 'Dotación y EPP'), ('examenes', 'Exámenes Médicos'), ('telefonia_celular', 'Telefonía Celular y Datos'), ('otros', 'Otros Gastos Logísticos')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
    ]
