# Generated by Django 4.2.26 on 2025-11-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vehiculo_costo_lavado_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomercial',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text="Ej: 'Vendedor Zona Norte', 'Supervisor Equipo A'", max_length=200, verbose_name='Nombre/Descripción'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text="Ej: 'Conductor Ruta Principal', 'Auxiliar Bodega CEDI'", max_length=200, verbose_name='Nombre/Descripción'),
        ),
    ]
