# Generated by Django 4.2.26 on 2025-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_nombre_to_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='costo_seguro_mercancia_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Seguro de carga transportada', max_digits=12, verbose_name='Seguro de Mercancía'),
        ),
    ]
