# Generated by Django 4.2.26 on 2025-11-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_seguro_mercancia_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(help_text='Código DANE del municipio', max_length=10, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'dxv_municipio',
                'ordering': ['departamento', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='parametrosmacro',
            name='precio_galon_combustible',
        ),
        migrations.AddField(
            model_name='parametrosmacro',
            name='precio_galon_acpm',
            field=models.DecimalField(decimal_places=2, default=14000, help_text='Precio promedio galón de ACPM/diesel', max_digits=10, verbose_name='Precio Galón ACPM (Diesel)'),
        ),
        migrations.AddField(
            model_name='parametrosmacro',
            name='precio_galon_gasolina',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Precio promedio galón de gasolina', max_digits=10, verbose_name='Precio Galón Gasolina'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('acpm', 'ACPM (Diesel)')], default='acpm', help_text='Tipo de combustible que usa el vehículo', max_length=10, verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='gastologistico',
            name='tipo',
            field=models.CharField(choices=[('mantenimiento_vehiculos', 'Mantenimiento de Vehículos'), ('seguros_carga', 'Seguros de Carga'), ('peajes', 'Peajes y Parqueaderos'), ('equipos_carga', 'Equipos de Carga (Estibas, Carretas)'), ('combustible', 'Combustible'), ('neumaticos', 'Neumáticos y Repuestos'), ('canon_renting', 'Canon Renting'), ('depreciacion_vehiculo', 'Depreciación Vehículos'), ('lavado_vehiculos', 'Aseo y Limpieza Vehículos'), ('parqueadero_vehiculos', 'Parqueaderos'), ('monitoreo_satelital', 'Monitoreo Satelital (GPS)'), ('bodegaje', 'Bodegaje Externo'), ('equipos_bodega', 'Equipos de Bodega'), ('embalaje', 'Material de Embalaje'), ('arriendo_bodega', 'Arriendo Bodega y CEDI'), ('servicios_publicos_bodega', 'Servicios Públicos Bodega'), ('internet_bodega', 'Internet y Conectividad Bodega'), ('seguro_bodega', 'Seguro Todo Riesgo Bodega'), ('control_plagas', 'Control de Plagas y Fumigación'), ('dotacion', 'Dotación y EPP'), ('examenes', 'Exámenes Médicos'), ('telefonia_celular', 'Telefonía Celular y Datos'), ('otros', 'Otros Gastos Logísticos')], max_length=50, verbose_name='Tipo de Gasto'),
        ),
        migrations.AlterField(
            model_name='personalcomercial',
            name='tipo',
            field=models.CharField(choices=[('vendedor_geografico', 'Vendedor Geográfico'), ('vendedor_senior', 'Vendedor Senior'), ('vendedor_minimercado', 'Vendedor Minimercado'), ('vendedor_supernumerario', 'Vendedor Supernumerario'), ('coordinador_comercial', 'Coordinador Comercial'), ('auxiliar_informacion', 'Auxiliar de Información')], max_length=50, verbose_name='Tipo de Personal'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_vehiculo_comercial', models.CharField(choices=[('MOTO', 'Moto'), ('AUTOMOVIL', 'Automóvil')], default='MOTO', max_length=20, verbose_name='Tipo Vehículo Comercial')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal (4 periodos/mes)'), ('QUINCENAL', 'Quincenal (2 periodos/mes)'), ('MENSUAL', 'Mensual (1 periodo/mes)')], default='MENSUAL', max_length=20, verbose_name='Frecuencia de Visitas')),
                ('requiere_pernocta', models.BooleanField(default=False, help_text='Si la ruta requiere pasar la noche fuera', verbose_name='¿Requiere Pernocta?')),
                ('noches_pernocta', models.IntegerField(default=0, help_text='Cantidad de noches por periodo', verbose_name='Noches de Pernocta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escenario', verbose_name='Escenario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca', verbose_name='Marca')),
                ('municipio_base_vendedor', models.ForeignKey(help_text='Desde dónde parte el vendedor (su residencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_base', to='core.municipio', verbose_name='Municipio Base Vendedor')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personalcomercial', verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'dxv_zona',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionLejania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_lejania_logistica_km', models.IntegerField(default=60, help_text='Aplicar lejania logística desde X km', verbose_name='Umbral Logística (km)')),
                ('umbral_lejania_comercial_km', models.IntegerField(default=10, help_text='Aplicar lejania comercial desde X km', verbose_name='Umbral Comercial (km)')),
                ('consumo_galon_km_moto', models.DecimalField(decimal_places=2, default=40, help_text='Rendimiento moto: típicamente 40 km/galón', max_digits=5, verbose_name='Consumo Moto (km/galón)')),
                ('consumo_galon_km_automovil', models.DecimalField(decimal_places=2, default=12, help_text='Rendimiento automóvil: típicamente 12 km/galón', max_digits=5, verbose_name='Consumo Automóvil (km/galón)')),
                ('desayuno_logistica', models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Desayuno Logística')),
                ('almuerzo_logistica', models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Almuerzo Logística')),
                ('cena_logistica', models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Cena Logística')),
                ('alojamiento_logistica', models.DecimalField(decimal_places=2, default=80000, max_digits=10, verbose_name='Alojamiento Logística')),
                ('parqueadero_logistica', models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Parqueadero Logística')),
                ('es_constitutiva_salario_logistica', models.BooleanField(default=False, help_text='Si marca Sí, se incluye en prestaciones sociales', verbose_name='¿Constitutiva Salario? (Logística)')),
                ('desayuno_comercial', models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Desayuno Comercial')),
                ('almuerzo_comercial', models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Almuerzo Comercial')),
                ('cena_comercial', models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Cena Comercial')),
                ('alojamiento_comercial', models.DecimalField(decimal_places=2, default=80000, max_digits=10, verbose_name='Alojamiento Comercial')),
                ('es_constitutiva_salario_comercial', models.BooleanField(default=False, help_text='Si marca Sí, se incluye en prestaciones sociales', verbose_name='¿Constitutiva Salario? (Comercial)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_lejania', to='core.escenario', verbose_name='Escenario')),
                ('municipio_bodega', models.ForeignKey(help_text='Centro de distribución principal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.municipio', verbose_name='Municipio Bodega')),
            ],
            options={
                'verbose_name': 'Configuración de Lejanías',
                'verbose_name_plural': 'Configuraciones de Lejanías',
                'db_table': 'dxv_configuracion_lejania',
            },
        ),
        migrations.CreateModel(
            name='ZonaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas_por_periodo', models.IntegerField(default=1, help_text='Ej: Si la zona es semanal, cuántas visitas por semana', verbose_name='Visitas Comerciales por Periodo')),
                ('entregas_por_periodo', models.IntegerField(default=1, help_text='Ej: Si la zona es semanal, cuántas entregas por semana', verbose_name='Entregas Logísticas por Periodo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Zona-Municipio',
                'verbose_name_plural': 'Zonas-Municipios',
                'db_table': 'dxv_zona_municipio',
                'ordering': ['zona', 'municipio__nombre'],
                'unique_together': {('zona', 'municipio')},
            },
        ),
        migrations.CreateModel(
            name='MatrizDesplazamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distancia (km)')),
                ('tiempo_minutos', models.IntegerField(verbose_name='Tiempo (minutos)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_hacia', to='core.municipio', verbose_name='Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_desde', to='core.municipio', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Matriz de Desplazamiento',
                'verbose_name_plural': 'Matrices de Desplazamiento',
                'db_table': 'dxv_matriz_desplazamiento',
                'ordering': ['origen__nombre', 'destino__nombre'],
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
