# Generated by Django 4.2.26 on 2025-11-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrizdesplazamiento',
            name='peaje_ida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de peajes en el trayecto de ida', max_digits=10, verbose_name='Peaje Ida'),
        ),
        migrations.AddField(
            model_name='matrizdesplazamiento',
            name='peaje_vuelta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de peajes en el trayecto de vuelta (puede ser diferente o 0)', max_digits=10, verbose_name='Peaje Vuelta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.CharField(blank=True, help_text='Nombre del conductor habitual', max_length=200, verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, help_text='Placa del vehículo', max_length=20, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(blank=True, help_text='Nombre completo del propietario (para terceros)', max_length=200, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería')], max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='zonamunicipio',
            name='flete_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor base del flete para este municipio (antes de lejanías)', max_digits=12, verbose_name='Flete Base'),
        ),
        migrations.AddField(
            model_name='zonamunicipio',
            name='vehiculo_logistica',
            field=models.ForeignKey(blank=True, help_text='Vehículo asignado para entregas logísticas en este municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to='core.vehiculo', verbose_name='Vehículo Logística'),
        ),
    ]
