# Generated by Django 4.2.26 on 2025-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vehiculo_banco_alter_vehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.CharField(blank=True, default='', help_text='Nombre del conductor habitual', max_length=200, null=True, verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, default='', help_text='Placa del vehículo', max_length=20, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del propietario (para terceros)', max_length=200, null=True, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], default='', max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería')], default='', max_length=10, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
