# Generated by Django 4.2.26 on 2025-11-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_vehiculo_banco_alter_vehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_cuenta',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_documento',
        ),
    ]
