# Generated by Django 4.2.26 on 2025-11-26 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fix_vehiculo_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal (4.33 periodos/mes)'), ('QUINCENAL', 'Quincenal (2 periodos/mes)'), ('MENSUAL', 'Mensual (1 periodo/mes)')], default='SEMANAL', max_length=20, verbose_name='Frecuencia de Entregas')),
                ('requiere_pernocta', models.BooleanField(default=False, help_text='Si la ruta requiere que el conductor pase la noche fuera', verbose_name='¿Requiere Pernocta?')),
                ('noches_pernocta', models.IntegerField(default=0, help_text='Cantidad de noches por viaje', verbose_name='Noches de Pernocta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_logisticas', to='core.escenario', verbose_name='Escenario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_logisticas', to='core.marca', verbose_name='Marca')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo (propio, renting o tercero) que realiza esta ruta', on_delete=django.db.models.deletion.CASCADE, related_name='rutas_logisticas', to='core.vehiculo', verbose_name='Vehículo Asignado')),
            ],
            options={
                'verbose_name': 'Ruta Logística',
                'verbose_name_plural': 'Rutas Logísticas',
                'db_table': 'dxv_ruta_logistica',
                'ordering': ['marca', 'vehiculo', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='zonamunicipio',
            name='entregas_por_periodo',
        ),
        migrations.RemoveField(
            model_name='zonamunicipio',
            name='flete_base',
        ),
        migrations.RemoveField(
            model_name='zonamunicipio',
            name='vehiculo_logistica',
        ),
        migrations.AlterField(
            model_name='zonamunicipio',
            name='visitas_por_periodo',
            field=models.IntegerField(default=1, help_text='Ej: Si la zona es semanal, cuántas visitas por semana', verbose_name='Visitas por Periodo'),
        ),
        migrations.AlterField(
            model_name='zonamunicipio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.zona', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='RutaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregas_por_periodo', models.IntegerField(default=1, help_text='Ej: Si la ruta es semanal, cuántas entregas por semana a este municipio', verbose_name='Entregas por Periodo')),
                ('flete_base', models.DecimalField(decimal_places=2, default=0, help_text='Valor base del flete para este municipio (aplica para vehículos terceros)', max_digits=12, verbose_name='Flete Base')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.rutalogistica', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Ruta-Municipio',
                'verbose_name_plural': 'Rutas-Municipios',
                'db_table': 'dxv_ruta_municipio',
                'ordering': ['ruta', 'municipio__nombre'],
                'unique_together': {('ruta', 'municipio')},
            },
        ),
    ]
