# Generated by Django 4.2.26 on 2025-11-27 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_refactor_lejanias_logisticas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['marca', 'nombre'], 'verbose_name': 'Zona Comercial', 'verbose_name_plural': 'Zonas Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='zonamunicipio',
            options={'ordering': ['zona', 'municipio__nombre'], 'verbose_name': 'Municipio de Zona Comercial', 'verbose_name_plural': 'Municipios de Zonas Comerciales'},
        ),
        migrations.RemoveField(
            model_name='zona',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='zona',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_asignadas', to='core.personalcomercial', verbose_name='Vendedor Asignado'),
        ),
    ]
