# Generated by Django 4.2.26 on 2025-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_zona_codigo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutalogistica',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='rutalogistica',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='viajes_por_periodo',
            field=models.IntegerField(default=1, help_text='Cantidad de viajes completos (ida+vuelta) por periodo. Ej: Si pernocta, puede ser 2 viajes/semana en lugar de 4', verbose_name='Viajes por Periodo'),
        ),
    ]
