# Generated by Django 4.2.26 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_rutalogistica_add_viajes_remove_codigo'),
    ]

    operations = [
        # Add pernocta fields to RutaMunicipio
        migrations.AddField(
            model_name='rutamunicipio',
            name='requiere_pernocta',
            field=models.BooleanField(default=False, help_text='Si la entrega a este municipio requiere que el conductor pase la noche', verbose_name='¿Requiere Pernocta?'),
        ),
        migrations.AddField(
            model_name='rutamunicipio',
            name='noches_pernocta',
            field=models.IntegerField(default=0, help_text='Cantidad de noches por viaje a este municipio', verbose_name='Noches de Pernocta'),
        ),
        # Remove pernocta fields from RutaLogistica
        migrations.RemoveField(
            model_name='rutalogistica',
            name='requiere_pernocta',
        ),
        migrations.RemoveField(
            model_name='rutalogistica',
            name='noches_pernocta',
        ),
    ]
