# Generated by Django 4.2.26 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_move_pernocta_to_rutamunicipio'),
    ]

    operations = [
        # Add orden_visita to RutaMunicipio
        migrations.AddField(
            model_name='rutamunicipio',
            name='orden_visita',
            field=models.IntegerField(default=1, help_text='Secuencia en el recorrido: 1=primer municipio, 2=segundo, etc.', verbose_name='Orden de Visita'),
        ),
        # Remove pernocta fields from RutaMunicipio (they go back to RutaLogistica)
        migrations.RemoveField(
            model_name='rutamunicipio',
            name='requiere_pernocta',
        ),
        migrations.RemoveField(
            model_name='rutamunicipio',
            name='noches_pernocta',
        ),
        # Add pernocta fields to RutaLogistica
        migrations.AddField(
            model_name='rutalogistica',
            name='requiere_pernocta',
            field=models.BooleanField(default=False, help_text='Si el recorrido requiere que el conductor pase la noche fuera', verbose_name='¿Requiere Pernocta?'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='noches_pernocta',
            field=models.IntegerField(default=0, help_text='Cantidad de noches por recorrido completo', verbose_name='Noches de Pernocta'),
        ),
        # Update ordering for RutaMunicipio
        migrations.AlterModelOptions(
            name='rutamunicipio',
            options={'ordering': ['ruta', 'orden_visita'], 'verbose_name': 'Municipio del Recorrido', 'verbose_name_plural': 'Municipios del Recorrido'},
        ),
        # Update verbose names for RutaLogistica
        migrations.AlterModelOptions(
            name='rutalogistica',
            options={'ordering': ['marca', 'vehiculo', 'nombre'], 'verbose_name': 'Recorrido Logístico', 'verbose_name_plural': 'Recorridos Logísticos'},
        ),
    ]
