# Generated by Django 4.2.26 on 2025-11-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_refactor_recorridos_logisticos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje_promedio_mensual',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='valor_flete_mensual',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text="Identificador único del vehículo. Ej: 'Turbo 01', 'NKR Zona Norte'", max_length=100, verbose_name='Nombre/Identificador'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='escenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='core.escenario', verbose_name='Escenario'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='frecuencia',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (4.33 periodos/mes)'), ('QUINCENAL', 'Quincenal (2 periodos/mes)'), ('MENSUAL', 'Mensual (1 periodo/mes)')], default='SEMANAL', max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='core.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Recorrido'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo (propio, renting o tercero) que realiza este recorrido', on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='core.vehiculo', verbose_name='Vehículo Asignado'),
        ),
        migrations.AlterField(
            model_name='rutalogistica',
            name='viajes_por_periodo',
            field=models.IntegerField(default=1, help_text='Cuántas veces se hace este recorrido por periodo. Ej: 2 veces/semana', verbose_name='Veces por Periodo'),
        ),
        migrations.AlterField(
            model_name='rutamunicipio',
            name='entregas_por_periodo',
            field=models.IntegerField(default=1, help_text='Cuántas entregas a este municipio cada vez que se hace el recorrido', verbose_name='Entregas por Periodo'),
        ),
        migrations.AlterField(
            model_name='rutamunicipio',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.rutalogistica', verbose_name='Recorrido'),
        ),
    ]
