# Generated by Django 4.2.26 on 2025-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_vehicle_promedio_fields_add_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlejania',
            name='precio_galon_acpm',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Precio promedio galón de ACPM/Diesel (para vehículos logísticos)', max_digits=10, verbose_name='Precio Galón ACPM'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='precio_galon_gasolina',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Precio promedio galón de gasolina (para comerciales y vehículos gasolina)', max_digits=10, verbose_name='Precio Galón Gasolina'),
        ),
    ]
