# Generated by Django 4.2.26 on 2025-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_fuel_prices_to_configuracion_lejania'),
    ]

    operations = [
        # Paso 1: Renombrar campos existentes de _logistica a _conductor
        # Esto preserva los datos existentes
        migrations.RenameField(
            model_name='configuracionlejania',
            old_name='desayuno_logistica',
            new_name='desayuno_conductor',
        ),
        migrations.RenameField(
            model_name='configuracionlejania',
            old_name='almuerzo_logistica',
            new_name='almuerzo_conductor',
        ),
        migrations.RenameField(
            model_name='configuracionlejania',
            old_name='cena_logistica',
            new_name='cena_conductor',
        ),
        migrations.RenameField(
            model_name='configuracionlejania',
            old_name='alojamiento_logistica',
            new_name='alojamiento_conductor',
        ),

        # Paso 2: Agregar nuevos campos para auxiliar (con defaults)
        migrations.AddField(
            model_name='configuracionlejania',
            name='desayuno_auxiliar',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Desayuno Auxiliar'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='almuerzo_auxiliar',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Almuerzo Auxiliar'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='cena_auxiliar',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Cena Auxiliar'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='alojamiento_auxiliar',
            field=models.DecimalField(decimal_places=2, default=80000, max_digits=10, verbose_name='Alojamiento Auxiliar'),
        ),
    ]
