# Generated by Django 5.0 on 2025-11-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_pernocta_logistica_to_conductor_add_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionlejania',
            name='almuerzo_conductor',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Almuerzo Conductor'),
        ),
        migrations.AlterField(
            model_name='configuracionlejania',
            name='alojamiento_conductor',
            field=models.DecimalField(decimal_places=2, default=80000, max_digits=10, verbose_name='Alojamiento Conductor'),
        ),
        migrations.AlterField(
            model_name='configuracionlejania',
            name='cena_conductor',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Cena Conductor'),
        ),
        migrations.AlterField(
            model_name='configuracionlejania',
            name='desayuno_conductor',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Desayuno Conductor'),
        ),
    ]
