# Generated by Django 4.2.26 on 2025-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_configuracionlejania_almuerzo_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrizdesplazamiento',
            name='peaje_vuelta',
        ),
        migrations.AlterField(
            model_name='matrizdesplazamiento',
            name='peaje_ida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de peajes en este tramo (cada tramo es unidireccional)', max_digits=10, verbose_name='Peaje'),
        ),
    ]
