# Generated by Django 4.2.26 on 2025-11-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_peaje_vuelta_from_matriz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutamunicipio',
            name='entregas_por_periodo',
        ),
    ]
