# Generated by Django 4.2.26 on 2025-11-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_entregas_por_periodo_from_rutamunicipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolumenOperacion',
        ),
    ]
