# Generated by Django 4.2.26 on 2025-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_proyeccion_ventas_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyeccionVentas',
        ),
    ]
