# Generated by Django 4.2.26 on 2025-11-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_proyeccionventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escenario',
            name='aprobado',
        ),
    ]
