# Generated by Django 4.2.26 on 2025-11-28 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_escenario_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_arriendos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usualmente igual al IPC (ej: 9.5 para 9.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incremento Arriendos (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_combustible',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Índice de incremento de combustibles (ej: 5.0 para 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incremento Combustible (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_personalizado_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Índice Personalizado 1 (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_personalizado_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Índice Personalizado 2 (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_salario_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Incremento específico del salario mínimo (ej: 12.0 para 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incremento Salario Mínimo (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='incremento_salarios',
            field=models.DecimalField(decimal_places=2, help_text='Incremento general de salarios (ej: 10.0 para 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incremento Salarios (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='ipc',
            field=models.DecimalField(decimal_places=2, help_text='Índice de Precios al Consumidor (ej: 9.5 para 9.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IPC (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosmacro',
            name='ipt',
            field=models.DecimalField(decimal_places=2, help_text='Índice de Precios al Transportador (ej: 8.0 para 8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IPT (%)'),
        ),
    ]
