# Generated by Django 4.2.26 on 2025-11-28 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_estandarizar_porcentajes_macro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorprestacional',
            name='arl',
            field=models.DecimalField(decimal_places=2, help_text='Según nivel de riesgo (ej: 0.522 para riesgo I)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ARL (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='caja_compensacion',
            field=models.DecimalField(decimal_places=2, help_text='Aporte a caja de compensación (ej: 4.0 para 4%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Caja Compensación (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='cesantias',
            field=models.DecimalField(decimal_places=2, help_text='Provisión cesantías (ej: 8.33 para 8.33%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cesantías (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='icbf',
            field=models.DecimalField(decimal_places=2, help_text='Aporte ICBF (ej: 3.0 para 3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ICBF (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='intereses_cesantias',
            field=models.DecimalField(decimal_places=2, help_text='Intereses sobre cesantías (ej: 1.0 para 1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Int. Cesantías (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='pension',
            field=models.DecimalField(decimal_places=2, help_text='Aporte patronal a pensión (ej: 12.0 para 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pensión (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='prima',
            field=models.DecimalField(decimal_places=2, help_text='Provisión prima de servicios (ej: 8.33 para 8.33%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prima (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='salud',
            field=models.DecimalField(decimal_places=2, help_text='Aporte patronal a salud (ej: 8.5 para 8.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Salud (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='sena',
            field=models.DecimalField(decimal_places=2, help_text='Aporte SENA (ej: 2.0 para 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SENA (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='vacaciones',
            field=models.DecimalField(decimal_places=2, help_text='Provisión vacaciones (ej: 4.17 para 4.17%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Vacaciones (%)'),
        ),
    ]
