# Generated by Django 4.2.26 on 2025-11-28 19:08

from django.db import migrations


def crear_perfiles_predefinidos(apps, schema_editor):
    """
    Crea los perfiles prestacionales predefinidos con valores correctos.

    Valores basados en normativa colombiana 2025:
    - Exoneración Ley 1607/2012: Salud=0%, ICBF=0%, SENA=0% para < 10 SMLV
    - Pensión: 12% (siempre)
    - Caja: 4% (siempre)
    - Cesantías: 8.33%, Int. Cesantías: 1.0%, Prima: 8.33%
    - Vacaciones: 0% (supernumerarios se modelan aparte)

    ARL por clase de riesgo:
    - I: 0.522% (oficina)
    - II: 1.044% (vendedores)
    - III: 2.436% (bodega)
    - IV: 4.350% (conductores)
    - V: 6.960% (raro en distribución)
    """
    FactorPrestacional = apps.get_model('core', 'FactorPrestacional')

    # Valores comunes (con exoneración Ley 1607)
    valores_comunes_exonerado = {
        'salud': 0,        # Exonerado Ley 1607
        'pension': 12.0,
        'caja_compensacion': 4.0,
        'icbf': 0,         # Exonerado Ley 1607
        'sena': 0,         # Exonerado Ley 1607
        'cesantias': 8.33,
        'intereses_cesantias': 1.0,
        'prima': 8.33,
        'vacaciones': 0,   # Supernumerarios aparte
    }

    perfiles = [
        {
            'perfil': 'administrativo',
            'arl': 0.522,  # Clase I - Oficina
            **valores_comunes_exonerado
        },
        {
            'perfil': 'comercial',
            'arl': 1.044,  # Clase II - Vendedores
            **valores_comunes_exonerado
        },
        {
            'perfil': 'logistico_bodega',
            'arl': 2.436,  # Clase III - Operaciones
            **valores_comunes_exonerado
        },
        {
            'perfil': 'logistico_calle',
            'arl': 4.350,  # Clase IV - Conductores
            **valores_comunes_exonerado
        },
        {
            'perfil': 'aprendiz_sena',
            'arl': 0.522,  # Clase I (típico para aprendices)
            # Aprendices: tienen prestaciones completas desde Ley 2466/2025
            'salud': 0,        # Exonerado
            'pension': 12.0,
            'caja_compensacion': 4.0,
            'icbf': 0,         # Exonerado
            'sena': 0,         # Exonerado
            'cesantias': 8.33,
            'intereses_cesantias': 1.0,
            'prima': 8.33,
            'vacaciones': 0,
        },
    ]

    for datos in perfiles:
        # update_or_create para evitar duplicados
        FactorPrestacional.objects.update_or_create(
            perfil=datos['perfil'],
            defaults={k: v for k, v in datos.items() if k != 'perfil'}
        )


def eliminar_perfil_logistico_legacy(apps, schema_editor):
    """Elimina el perfil 'logistico' genérico si existe (ahora es bodega o calle)"""
    FactorPrestacional = apps.get_model('core', 'FactorPrestacional')
    FactorPrestacional.objects.filter(perfil='logistico').delete()


def reverse_migration(apps, schema_editor):
    """Reverse: No hacemos nada, los perfiles se quedan"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_estandarizar_porcentajes_factor_prestacional'),
    ]

    operations = [
        migrations.RunPython(crear_perfiles_predefinidos, reverse_migration),
        migrations.RunPython(eliminar_perfil_logistico_legacy, reverse_migration),
    ]
