# Generated by Django 4.2.26 on 2025-11-28 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_actualizar_perfil_choices_arl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorprestacional',
            name='arl',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Clases: I=0.522 (oficina), II=1.044 (vendedores), III=2.436 (bodega), IV=4.350 (conductores), V=6.960', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ARL (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='caja_compensacion',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Siempre 4% (NO está exonerado)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Caja Compensación (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='cesantias',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario + subsidio. Provisión: 8.33% (equivale a 1 mes de salario al año)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cesantías (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='icbf',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Normal: 3%. EXONERADO (0%) por Ley 1607 para empleados < 10 SMLV', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ICBF (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='intereses_cesantias',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario + subsidio. Provisión: 1.0% (es el 12% anual sobre cesantías, dividido 12)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Int. Cesantías (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='pension',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Siempre 12% (NO está exonerado)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pensión (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='perfil',
            field=models.CharField(choices=[('administrativo', 'Administrativo (Riesgo I - Oficina)'), ('comercial', 'Comercial (Riesgo II - Vendedores)'), ('logistico_bodega', 'Logístico Bodega (Riesgo III - Operaciones)'), ('logistico_calle', 'Logístico Calle (Riesgo IV - Conductores)'), ('aprendiz_sena', 'Aprendiz SENA (Etapa Productiva)')], max_length=50, unique=True, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='prima',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario + subsidio. Provisión: 8.33% (equivale a 1 mes de salario al año)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prima (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='salud',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Normal: 8.5%. EXONERADO (0%) por Ley 1607 para empleados < 10 SMLV', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Salud (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='sena',
            field=models.DecimalField(decimal_places=2, help_text='Base: salario. Normal: 2%. EXONERADO (0%) por Ley 1607 para empleados < 10 SMLV', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SENA (%)'),
        ),
        migrations.AlterField(
            model_name='factorprestacional',
            name='vacaciones',
            field=models.DecimalField(decimal_places=2, help_text='Base: SOLO salario. Usar 0% si supernumerarios se modelan aparte (recomendado). Usar 4.17% solo para provisión contable.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Vacaciones (%)'),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='perfil_prestacional',
            field=models.CharField(choices=[('administrativo', 'Administrativo (Riesgo I - Oficina)'), ('aprendiz_sena', 'Aprendiz SENA (Etapa Productiva)')], default='administrativo', max_length=20, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='personalcomercial',
            name='perfil_prestacional',
            field=models.CharField(choices=[('comercial', 'Comercial (Riesgo II - Vendedores)'), ('administrativo', 'Administrativo (Riesgo I - Coordinadores)')], default='comercial', max_length=20),
        ),
        migrations.AlterField(
            model_name='personallogistico',
            name='perfil_prestacional',
            field=models.CharField(choices=[('logistico_bodega', 'Logístico Bodega (Riesgo III - Operarios)'), ('logistico_calle', 'Logístico Calle (Riesgo IV - Conductores)'), ('administrativo', 'Administrativo (Riesgo I - Coordinadores)')], default='logistico_calle', max_length=20),
        ),
    ]
