# Generated by Django 4.2.26 on 2025-11-28 19:09

from django.db import migrations


def migrar_perfil_logistico(apps, schema_editor):
    """
    Migra registros con perfil 'logistico' a 'logistico_calle'.

    El perfil 'logistico' genérico ya no existe. Se asume que la mayoría
    del personal logístico son conductores/auxiliares de entrega (Riesgo IV).

    Si hay personal de bodega, se puede cambiar manualmente a 'logistico_bodega'.
    """
    PersonalLogistico = apps.get_model('core', 'PersonalLogistico')

    # Migrar todos los registros con perfil 'logistico' a 'logistico_calle'
    cantidad_actualizada = PersonalLogistico.objects.filter(
        perfil_prestacional='logistico'
    ).update(perfil_prestacional='logistico_calle')

    if cantidad_actualizada:
        print(f"  Migrados {cantidad_actualizada} registros de 'logistico' a 'logistico_calle'")


def reverse_migration(apps, schema_editor):
    """Reverse: cambiar logistico_calle de vuelta a logistico"""
    PersonalLogistico = apps.get_model('core', 'PersonalLogistico')
    PersonalLogistico.objects.filter(
        perfil_prestacional='logistico_calle'
    ).update(perfil_prestacional='logistico')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cambiar_default_perfil_logistico'),
    ]

    operations = [
        migrations.RunPython(migrar_perfil_logistico, reverse_migration),
    ]
