# Generated by Django 4.2.26 on 2025-11-28 19:21

import django.core.validators
from django.db import migrations, models


def convertir_porcentajes_a_0_100(apps, schema_editor):
    """
    Convierte porcentajes de formato decimal (0.0041) a formato 0-100 (0.41).
    Solo aplica si hay valores menores a 1 (lo que indica formato decimal).
    """
    Impuesto = apps.get_model('core', 'Impuesto')

    for impuesto in Impuesto.objects.filter(porcentaje__isnull=False, porcentaje__lt=1):
        # Convertir de decimal a porcentaje (0.0041 -> 0.41)
        impuesto.porcentaje = impuesto.porcentaje * 100
        impuesto.save()
        print(f"  Convertido {impuesto.nombre}: {impuesto.porcentaje}%")


def reverse_conversion(apps, schema_editor):
    """Reverse: convertir de 0-100 a decimal"""
    Impuesto = apps.get_model('core', 'Impuesto')

    for impuesto in Impuesto.objects.filter(porcentaje__isnull=False):
        impuesto.porcentaje = impuesto.porcentaje / 100
        impuesto.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_migrar_logistico_a_logistico_calle'),
    ]

    operations = [
        # Primero convertir datos existentes
        migrations.RunPython(convertir_porcentajes_a_0_100, reverse_conversion),
        # Luego cambiar el campo
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Ingrese en formato 0-100 (ej: 33 para 33%, 0.41 para 0.41%)',
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Porcentaje (%)'
            ),
        ),
    ]
