# Generated by Django 4.2.26 on 2025-11-28 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_estandarizar_porcentaje_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicarecursoshumanos',
            name='tasa_rotacion_anual',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de rotación estimado 0-100 (ej: 25 para 25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa de Rotación Anual (%)'),
        ),
    ]
