# Generated by Django 4.2.26 on 2025-11-28 20:24

import django.core.validators
from django.db import migrations, models


def convertir_frecuencia_anual_a_meses(apps, schema_editor):
    """
    Convierte frecuencia anual a meses:
    - frecuencia_dotacion_anual=3 (3 veces/año) → frecuencia_dotacion_meses=4 (cada 4 meses)
    - frecuencia_epp_anual=1 (1 vez/año) → frecuencia_epp_meses=12 (cada 12 meses)
    """
    PoliticaRecursosHumanos = apps.get_model('core', 'PoliticaRecursosHumanos')
    for politica in PoliticaRecursosHumanos.objects.all():
        # Convertir dotación: meses = 12 / frecuencia_anual
        if politica.frecuencia_dotacion_anual and politica.frecuencia_dotacion_anual > 0:
            politica.frecuencia_dotacion_meses = max(1, int(12 / politica.frecuencia_dotacion_anual))
        else:
            politica.frecuencia_dotacion_meses = 4  # default: cada 4 meses

        # Convertir EPP: meses = 12 / frecuencia_anual
        if politica.frecuencia_epp_anual and politica.frecuencia_epp_anual > 0:
            politica.frecuencia_epp_meses = max(1, int(12 / politica.frecuencia_epp_anual))
        else:
            politica.frecuencia_epp_meses = 12  # default: cada año

        politica.save()


def revertir_frecuencia_meses_a_anual(apps, schema_editor):
    """Reversa: convierte meses a frecuencia anual"""
    PoliticaRecursosHumanos = apps.get_model('core', 'PoliticaRecursosHumanos')
    for politica in PoliticaRecursosHumanos.objects.all():
        # Revertir: frecuencia_anual = 12 / meses
        politica.frecuencia_dotacion_anual = max(1, int(12 / politica.frecuencia_dotacion_meses))
        politica.frecuencia_epp_anual = max(1, int(12 / politica.frecuencia_epp_meses))
        politica.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_agregar_validador_tasa_rotacion'),
    ]

    operations = [
        # 1. Agregar nuevos campos con defaults
        migrations.AddField(
            model_name='politicarecursoshumanos',
            name='frecuencia_dotacion_meses',
            field=models.IntegerField(
                default=4,
                help_text='Cada cuántos meses se entrega dotación (ej: 4 = cada 4 meses = 3 veces al año)',
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)],
                verbose_name='Frecuencia Dotación (meses)'
            ),
        ),
        migrations.AddField(
            model_name='politicarecursoshumanos',
            name='frecuencia_epp_meses',
            field=models.IntegerField(
                default=12,
                help_text='Cada cuántos meses se entrega EPP (ej: 24 = cada 2 años, 12 = cada año)',
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)],
                verbose_name='Frecuencia EPP (meses)'
            ),
        ),
        migrations.AddField(
            model_name='politicarecursoshumanos',
            name='indice_incremento',
            field=models.CharField(
                choices=[
                    ('salarios', 'Incremento Salarios General'),
                    ('salario_minimo', 'Incremento Salario Mínimo'),
                    ('ipc', 'IPC (Índice de Precios al Consumidor)'),
                    ('ipt', 'IPT (Índice de Precios al Transportador)'),
                    ('combustible', 'Incremento Combustible'),
                    ('arriendos', 'Incremento Arriendos'),
                    ('personalizado_1', 'Índice Personalizado 1'),
                    ('personalizado_2', 'Índice Personalizado 2'),
                    ('fijo', 'Sin Incremento (Valor Fijo)')
                ],
                default='ipc',
                help_text='Índice a usar para proyectar valores monetarios al siguiente año',
                max_length=20,
                verbose_name='Índice de Incremento'
            ),
        ),

        # 2. Migrar datos existentes
        migrations.RunPython(convertir_frecuencia_anual_a_meses, revertir_frecuencia_meses_a_anual),

        # 3. Eliminar campos antiguos
        migrations.RemoveField(
            model_name='politicarecursoshumanos',
            name='frecuencia_dotacion_anual',
        ),
        migrations.RemoveField(
            model_name='politicarecursoshumanos',
            name='frecuencia_epp_anual',
        ),
    ]
