# Generated by Django 4.2.26 on 2025-11-28 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rrhh_indice_incremento_frecuencia_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccioncrecimiento',
            name='factor_crecimiento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de crecimiento esperado (ej: 10 para 10%, -5 para decrecimiento)', max_digits=6, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(500)], verbose_name='Factor de Crecimiento %'),
        ),
        migrations.AlterField(
            model_name='proyeccionpenetracion',
            name='penetracion_final',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje del mercado que se espera capturar al final del año (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Penetración Final %'),
        ),
        migrations.AlterField(
            model_name='proyeccionpenetracion',
            name='penetracion_inicial',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje del mercado que se espera capturar al inicio del año (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Penetración Inicial %'),
        ),
    ]
