# Generated by Django 4.2.26 on 2025-11-28 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_proyecciones_validadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillaestacional',
            name='abril',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Abril %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='agosto',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Agosto %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, default=8.37, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Diciembre %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='enero',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Enero %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='febrero',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Febrero %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='julio',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Julio %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='junio',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Junio %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='marzo',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Marzo %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='mayo',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mayo %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='noviembre',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Noviembre %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='octubre',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Octubre %'),
        ),
        migrations.AlterField(
            model_name='plantillaestacional',
            name='septiembre',
            field=models.DecimalField(decimal_places=2, default=8.33, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Septiembre %'),
        ),
    ]
