# Generated by Django 4.2.26 on 2025-11-28 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_plantilla_estacional_validadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoadministrativo',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='compartido', help_text='Cómo se asigna este gasto a las zonas. Gastos admin se distribuyen equitativamente.', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='gastocomercial',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='directo', help_text='Cómo se asigna este gasto a las zonas', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='gastocomercial',
            name='zona',
            field=models.ForeignKey(blank=True, help_text="Zona asignada (solo si asignación es 'Directo a Zona')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_comerciales', to='core.zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='gastologistico',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='proporcional', help_text='Cómo se asigna este gasto a las zonas. Gastos logísticos se distribuyen proporcional a ventas.', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='gastologistico',
            name='zona',
            field=models.ForeignKey(blank=True, help_text="Zona asignada (solo si asignación es 'Directo a Zona')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_logisticos', to='core.zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='personaladministrativo',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='compartido', help_text='Cómo se asigna este costo a las zonas. Personal admin se distribuye equitativamente.', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='personalcomercial',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='directo', help_text='Cómo se asigna este costo a las zonas', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='personalcomercial',
            name='zona',
            field=models.ForeignKey(blank=True, help_text="Zona asignada (solo si asignación es 'Directo a Zona')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_comercial', to='core.zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='tipo_asignacion_geo',
            field=models.CharField(choices=[('directo', 'Directo a Zona'), ('proporcional', 'Proporcional a Ventas'), ('compartido', 'Compartido Equitativo')], default='proporcional', help_text='Cómo se asigna este costo a las zonas. Personal logístico típicamente se distribuye proporcional a ventas.', max_length=20, verbose_name='Asignación Geográfica'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='zona',
            field=models.ForeignKey(blank=True, help_text="Zona asignada (solo si asignación es 'Directo a Zona')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_logistico', to='core.zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='cantidad_auxiliares',
            field=models.IntegerField(default=1, help_text='Auxiliares de entrega que van en este recorrido (0, 1 o 2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Cantidad de Auxiliares'),
        ),
        migrations.AddField(
            model_name='zona',
            name='participacion_ventas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de las ventas totales de la marca que hace esta zona (debe sumar 100% entre todas las zonas)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación Ventas %'),
        ),
        migrations.AddField(
            model_name='zonamunicipio',
            name='participacion_ventas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de las ventas de la zona que hace este municipio (debe sumar 100% entre municipios de la zona)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación Ventas %'),
        ),
    ]
