# Generated by Django 4.2.26 on 2025-11-28 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_asignacion_geografica_pyg'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='venta_proyectada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de venta proyectada para esta zona (en pesos)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Venta Proyectada'),
        ),
        migrations.AddField(
            model_name='zonamunicipio',
            name='venta_proyectada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de venta proyectada para este municipio (en pesos)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Venta Proyectada'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='participacion_ventas',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculado automáticamente: (venta_zona / venta_total_marca) × 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación Ventas %'),
        ),
        migrations.AlterField(
            model_name='zonamunicipio',
            name='participacion_ventas',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculado automáticamente: (venta_municipio / venta_zona) × 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación Ventas %'),
        ),
    ]
