# Generated by Django 4.2.26 on 2025-11-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_venta_proyectada_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('marca', 'escenario', 'nombre')},
        ),
    ]
