# Generated by Django 4.2.26 on 2025-11-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_zona_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlejania',
            name='frecuencia_comite',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (4 veces/mes)'), ('QUINCENAL', 'Quincenal (2 veces/mes)'), ('MENSUAL', 'Mensual (1 vez/mes)')], default='SEMANAL', max_length=20, verbose_name='Frecuencia del Comité'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='municipio_comite',
            field=models.ForeignKey(blank=True, help_text='Dónde se realiza el comité comercial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_comerciales', to='core.municipio', verbose_name='Municipio del Comité'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='tiene_comite_comercial',
            field=models.BooleanField(default=False, help_text='Si hay reunión periódica de vendedores en un municipio fijo', verbose_name='¿Tiene Comité Comercial?'),
        ),
    ]
