# Generated by Django 4.2.26 on 2025-11-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_comite_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionlejania',
            name='frecuencia_comite',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (4 veces/mes)'), ('TRISEMANAL', '3 veces al mes'), ('QUINCENAL', 'Quincenal (2 veces/mes)'), ('MENSUAL', 'Mensual (1 vez/mes)')], default='SEMANAL', max_length=20, verbose_name='Frecuencia del Comité'),
        ),
    ]
