# Generated by Django 4.2.26 on 2025-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_frecuencia_trisemanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='frecuencia',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (4 periodos/mes)'), ('QUINCENAL', 'Quincenal (2 periodos/mes)'), ('MENSUAL', 'Mensual (1 periodo/mes)')], default='SEMANAL', max_length=20, verbose_name='Frecuencia de Visitas'),
        ),
    ]
