# Generated by Django 4.2.26 on 2025-11-29 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_zona_frecuencia_default_semanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_proyectada', models.DecimalField(decimal_places=2, default=0, help_text='Valor de venta proyectada para este municipio (en pesos)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Venta Proyectada')),
                ('participacion_ventas', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculado automáticamente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación %')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_municipio', to='core.escenario', verbose_name='Escenario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_municipio', to='core.marca', verbose_name='Marca')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Venta por Municipio',
                'verbose_name_plural': 'Ventas por Municipio',
                'db_table': 'dxv_venta_municipio',
                'ordering': ['municipio__departamento', 'municipio__nombre'],
                'unique_together': {('marca', 'escenario', 'municipio')},
            },
        ),
    ]
