# Generated by Django 4.2.26 on 2025-11-29 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_venta_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutalogistica',
            name='cantidad_auxiliares',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cantidad_auxiliares',
            field=models.IntegerField(default=1, help_text='Cantidad de auxiliares de entrega fijos asignados a este vehículo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Auxiliares por Vehículo'),
        ),
    ]
