# Generated by Django 4.2.26 on 2025-11-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auxiliares_en_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlejania',
            name='km_minimo_visita_local',
            field=models.IntegerField(default=10, help_text='Km a sumar cuando el vendedor visita su propio municipio (desplazamientos internos)', verbose_name='Km mínimo visita local'),
        ),
    ]
