# Generated by Django 4.2.26 on 2025-11-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_km_minimo_visita_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionlejania',
            name='km_minimo_visita_local',
        ),
    ]
