# Generated by Django 4.2.26 on 2025-11-30 01:51

from django.db import migrations


def remove_flete_transporte_tercero(apps, schema_editor):
    """Eliminar registros legacy de 'Flete Transporte (Tercero)' que ya no se usan."""
    GastoLogistico = apps.get_model('core', 'GastoLogistico')
    deleted_count, _ = GastoLogistico.objects.filter(
        nombre='Flete Transporte (Tercero)'
    ).delete()
    if deleted_count > 0:
        print(f"  Eliminados {deleted_count} registros legacy de 'Flete Transporte (Tercero)'")


def reverse_noop(apps, schema_editor):
    """No se puede revertir - los datos ya no existen."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_km_minimo_visita_local'),
    ]

    operations = [
        migrations.RunPython(remove_flete_transporte_tercero, reverse_noop),
    ]
