# Generated by Django 4.2.26 on 2025-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_flete_transporte_tercero_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondescuentos',
            name='aplica_cesantia_comercial',
            field=models.BooleanField(default=False, help_text='Provisión mensual de 1/12 de los ingresos del agente (Margen Bruto + Otros Ingresos)', verbose_name='¿Aplica Cesantía Comercial?'),
        ),
    ]
