# Generated by Django 4.2.26 on 2025-12-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_agregar_cesantia_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaladministrativo',
            name='auxilio_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonos o auxilios que NO generan prestaciones (rodamiento, alimentación, etc.)', max_digits=12, verbose_name='Auxilio Adicional'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='auxilio_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonos o auxilios que NO generan prestaciones (rodamiento, alimentación, etc.)', max_digits=12, verbose_name='Auxilio Adicional'),
        ),
    ]
