# Generated by Django 4.2.26 on 2025-12-08 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_auxilios_no_prestacionales_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoadministrativo',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], default='equitativo', help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='gastoadministrativo',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='compartido', help_text='Cómo se asigna este gasto entre operaciones. Gastos admin típicamente compartidos.', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='gastocomercial',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='gastocomercial',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este gasto entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='gastologistico',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='gastologistico',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este gasto entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='personaladministrativo',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], default='equitativo', help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='personaladministrativo',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='compartido', help_text='Cómo se asigna este costo entre operaciones. Personal admin típicamente compartido.', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='personalcomercial',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='personalcomercial',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este costo entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este costo entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este vehículo entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text="Código corto. Ej: 'ORI', 'SUR'", max_length=20, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color (hex)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='core.escenario', verbose_name='Escenario')),
                ('municipio_base', models.ForeignKey(blank=True, help_text='Ubicación de la bodega/CEDI principal de esta operación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_base', to='core.municipio', verbose_name='Municipio Base (CEDI)')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'dxv_operacion',
                'ordering': ['escenario', 'nombre'],
                'unique_together': {('escenario', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='gastoadministrativo',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_administrativos', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='gastocomercial',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_comerciales', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='gastologistico',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_logisticos', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='personaladministrativo',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_administrativo', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='personalcomercial',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_comercial', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='personallogistico',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_logistico', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='zona',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text='Operación/Centro de Costos al que pertenece esta zona', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.CreateModel(
            name='MarcaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion_ventas', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculado: (venta_marca_operacion / venta_total_operacion) * 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Participación Ventas %')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_asociadas', to='core.marca', verbose_name='Marca')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_asociadas', to='core.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Marca por Operación',
                'verbose_name_plural': 'Marcas por Operación',
                'db_table': 'dxv_marca_operacion',
                'ordering': ['operacion', 'marca'],
                'unique_together': {('marca', 'operacion')},
            },
        ),
    ]
