# Generated by Django 4.2.26 on 2025-12-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_operacion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='tasa_ica',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tasa de ICA en decimal. Ej: 0.007 para 0.7%', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tasa ICA'),
        ),
    ]
