# Generated by Django 4.2.26 on 2025-12-08 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_tasa_ica_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tasa_ica',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingrese en formato 0-100 (ej: 33 para 33%, 0.41 para 0.41%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa ICA (%)'),
        ),
    ]
