# Generated by Django 4.2.26 on 2025-12-08 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_change_tasa_ica_to_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaoperacion',
            name='venta_proyectada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Venta mensual proyectada de esta marca en esta operación', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Venta Proyectada Mensual'),
        ),
    ]
