# Generated by Django 4.2.26 on 2025-12-08

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    """
    Invierte la editabilidad de participacion_ventas y venta_proyectada:

    ANTES:
    - venta_proyectada: editable (usuario ingresa valor)
    - participacion_ventas: readonly (calculado)

    DESPUÉS:
    - participacion_ventas: editable (usuario ingresa %)
    - venta_proyectada: readonly (calculado automáticamente)

    Esto simplifica el flujo de configuración:
    1. ProyeccionVentasConfig → venta total de la marca
    2. MarcaOperacion.participacion_ventas → % por operación
    3. Zona.participacion_ventas → % dentro de la operación
    4. ZonaMunicipio.participacion_ventas → % dentro de la zona

    Las ventas se calculan automáticamente en cascada.
    """

    dependencies = [
        ('core', '0061_add_venta_proyectada_to_marcaoperacion'),
    ]

    operations = [
        # MarcaOperacion: participacion_ventas ahora editable
        migrations.AlterField(
            model_name='marcaoperacion',
            name='participacion_ventas',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='% de las ventas totales de la marca que corresponden a esta operación',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Participación %'
            ),
        ),
        # MarcaOperacion: venta_proyectada ahora readonly (editable=False en modelo)
        migrations.AlterField(
            model_name='marcaoperacion',
            name='venta_proyectada',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text='Calculado automáticamente: venta_total_marca × participación%',
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Venta Proyectada Mensual'
            ),
        ),
        # Zona: participacion_ventas ahora editable
        migrations.AlterField(
            model_name='zona',
            name='participacion_ventas',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='% de las ventas de la operación que corresponden a esta zona',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Participación %'
            ),
        ),
        # Zona: venta_proyectada ahora readonly
        migrations.AlterField(
            model_name='zona',
            name='venta_proyectada',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text='Calculado automáticamente: venta_operación × participación%',
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Venta Proyectada'
            ),
        ),
        # ZonaMunicipio: participacion_ventas ahora editable
        migrations.AlterField(
            model_name='zonamunicipio',
            name='participacion_ventas',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='% de las ventas de la zona que corresponden a este municipio',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Participación %'
            ),
        ),
        # ZonaMunicipio: venta_proyectada ahora readonly
        migrations.AlterField(
            model_name='zonamunicipio',
            name='venta_proyectada',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text='Calculado automáticamente: venta_zona × participación%',
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Venta Proyectada'
            ),
        ),
    ]
