# Generated by Django 4.2.26 on 2025-12-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_invert_participacion_venta_editability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentaMunicipio',
        ),
    ]
