# Generated by Django 4.2.26 on 2025-12-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_venta_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escenario',
            options={'ordering': ['-anio', 'tipo'], 'verbose_name': 'Escenario', 'verbose_name_plural': 'Escenarios'},
        ),
        migrations.RemoveField(
            model_name='escenario',
            name='periodo_numero',
        ),
        migrations.RemoveField(
            model_name='escenario',
            name='periodo_tipo',
        ),
    ]
