# Generated by Django 4.2.26 on 2025-12-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_periodo_fields_escenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutalogistica',
            name='criterio_prorrateo_operacion',
            field=models.CharField(blank=True, choices=[('ventas', 'Por Ventas'), ('zonas', 'Por Cantidad de Zonas'), ('equitativo', 'Equitativo')], help_text="Solo aplica si tipo_asignacion_operacion es 'compartido'", max_length=20, null=True, verbose_name='Criterio Prorrateo Operación'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='operacion',
            field=models.ForeignKey(blank=True, help_text="Operación asignada (si tipo_asignacion_operacion es 'individual')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_logisticas', to='core.operacion', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='tipo_asignacion_operacion',
            field=models.CharField(choices=[('individual', 'Individual a Operación'), ('compartido', 'Compartido entre Operaciones')], default='individual', help_text='Cómo se asigna este recorrido entre operaciones', max_length=20, verbose_name='Asignación Operación'),
        ),
        migrations.AlterField(
            model_name='gastoadministrativo',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual (asignado a una marca)'), ('compartido', 'Compartido entre marcas')], default='compartido', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='gastocomercial',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual (asignado a una marca)'), ('compartido', 'Compartido entre marcas')], default='individual', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='gastologistico',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual (asignado a una marca)'), ('compartido', 'Compartido entre marcas')], default='individual', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual (asignado a una marca)'), ('compartido', 'Compartido entre marcas')], default='compartido', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='personalcomercial',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual'), ('compartido', 'Compartido')], default='individual', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='personallogistico',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual'), ('compartido', 'Compartido')], default='individual', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual'), ('compartido', 'Compartido')], default='individual', max_length=20, verbose_name='Asignación Marca'),
        ),
    ]
