# Generated by Django 4.2.26 on 2025-12-10 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_operacion_en_ruta_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutalogistica',
            name='asignacion',
            field=models.CharField(choices=[('individual', 'Individual'), ('compartido', 'Compartido')], default='individual', help_text='Individual = 100% a esta marca. Compartido = se distribuye entre marcas.', max_length=20, verbose_name='Asignación Marca'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='criterio_prorrateo',
            field=models.CharField(blank=True, choices=[('volumen', 'Por Volumen'), ('ventas', 'Por Ventas'), ('uso_real', 'Por Uso Real')], default='volumen', help_text='Criterio para distribuir entre marcas. Solo aplica si es compartido.', max_length=20, null=True, verbose_name='Criterio Prorrateo'),
        ),
        migrations.AddField(
            model_name='rutalogistica',
            name='porcentaje_uso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de uso para esta marca (0-1). Solo aplica si es compartido.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Porcentaje Uso'),
        ),
    ]
