# Generated by Django 4.2.26 on 2025-12-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_asignacion_marca_ruta_logistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionlejania',
            name='consumo_galon_km_automovil',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Rendimiento automóvil: típicamente 35-50 km/galón', max_digits=5, verbose_name='Consumo Automóvil (km/galón)'),
        ),
        migrations.AlterField(
            model_name='configuracionlejania',
            name='consumo_galon_km_moto',
            field=models.DecimalField(decimal_places=2, default=90, help_text='Rendimiento moto: típicamente 80-100 km/galón', max_digits=5, verbose_name='Consumo Moto (km/galón)'),
        ),
    ]
