# Generated by Django 4.2.26 on 2025-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_update_consumo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlejania',
            name='costo_adicional_km_automovil',
            field=models.DecimalField(decimal_places=2, default=120, help_text='Mantenimiento (~$50/km) + Depreciación (~$50/km) + Llantas (~$20/km). Ref: SICE-TAC', max_digits=8, verbose_name='Costo Adicional Automóvil ($/km)'),
        ),
        migrations.AddField(
            model_name='configuracionlejania',
            name='costo_adicional_km_moto',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Mantenimiento (~$30/km) + Depreciación (~$20/km) + Llantas (~$10/km). Ref: SICE-TAC', max_digits=8, verbose_name='Costo Adicional Moto ($/km)'),
        ),
    ]
