# Generated by Django 4.2.26 on 2025-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_migrar_tipo_proyeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillaestacional',
            name='marca',
        ),
        migrations.AlterUniqueTogether(
            name='proyeccioncanal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proyeccioncanal',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='proyeccioncanal',
            name='config',
        ),
        migrations.RemoveField(
            model_name='proyeccioncrecimiento',
            name='config',
        ),
        migrations.RemoveField(
            model_name='proyeccionpenetracion',
            name='config',
        ),
        migrations.RemoveField(
            model_name='proyeccionpenetracion',
            name='mercado',
        ),
        migrations.RemoveField(
            model_name='proyeccionproducto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proyeccionproducto',
            name='config',
        ),
        migrations.RemoveField(
            model_name='proyeccionproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='proyeccionventasconfig',
            name='plantilla_estacional',
        ),
        migrations.DeleteModel(
            name='DefinicionMercado',
        ),
        migrations.DeleteModel(
            name='PlantillaEstacional',
        ),
        migrations.DeleteModel(
            name='ProyeccionCanal',
        ),
        migrations.DeleteModel(
            name='ProyeccionCrecimiento',
        ),
        migrations.DeleteModel(
            name='ProyeccionPenetracion',
        ),
        migrations.DeleteModel(
            name='ProyeccionProducto',
        ),
    ]
