# Generated by Django 4.2.26 on 2025-12-15 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_eliminar_modelos_proyeccion_obsoletos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaProyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tiendas, Minimercados, Consumo Local', max_length=100, verbose_name='Tipología')),
                ('numero_clientes', models.PositiveIntegerField(default=0, verbose_name='# Clientes')),
                ('visitas_mes', models.PositiveIntegerField(default=1, help_text='Visitas por cliente al mes', verbose_name='Visitas/Mes')),
                ('efectividad', models.DecimalField(decimal_places=2, default=100, help_text='% de visitas que convierten en venta', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Efectividad %')),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, help_text='$ promedio por venta', max_digits=12, verbose_name='Ticket Promedio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipología de Cliente',
                'verbose_name_plural': 'Tipologías de Cliente',
                'db_table': 'dxv_tipologia_proyeccion',
                'ordering': ['config', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='proyecciondemandaproducto',
            name='lista_precio',
        ),
        migrations.AlterModelOptions(
            name='proyeccionventasconfig',
            options={'ordering': ['marca', 'escenario', 'anio'], 'verbose_name': 'Proyección de Ventas', 'verbose_name_plural': 'Proyecciones de Ventas'},
        ),
        migrations.RemoveField(
            model_name='proyeccionventasconfig',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='ListaPreciosProducto',
        ),
        migrations.DeleteModel(
            name='ProyeccionDemandaProducto',
        ),
        migrations.AddField(
            model_name='tipologiaproyeccion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipologias', to='core.proyeccionventasconfig', verbose_name='Configuración'),
        ),
    ]
