# Generated by Django 4.2.26 on 2025-12-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_simplificar_proyeccion_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologiaproyeccion',
            name='crecimiento_clientes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% crecimiento mensual en clientes', max_digits=5, verbose_name='Crec. Clientes %'),
        ),
        migrations.AddField(
            model_name='tipologiaproyeccion',
            name='crecimiento_efectividad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% crecimiento mensual en efectividad', max_digits=5, verbose_name='Crec. Efectividad %'),
        ),
        migrations.AddField(
            model_name='tipologiaproyeccion',
            name='crecimiento_ticket',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% crecimiento mensual en ticket', max_digits=5, verbose_name='Crec. Ticket %'),
        ),
    ]
