# Generated by Django 4.2.26 on 2025-12-18 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_crecimiento_tipologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLogisticoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_logistico_asignaciones', to='core.marca')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.personallogistico')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Personal Logístico)',
                'verbose_name_plural': 'Asignaciones de Marca (Personal Logístico)',
                'db_table': 'dxv_personal_logistico_marca',
                'unique_together': {('personal', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='PersonalComercialMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_comercial_asignaciones', to='core.marca')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.personalcomercial')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Personal Comercial)',
                'verbose_name_plural': 'Asignaciones de Marca (Personal Comercial)',
                'db_table': 'dxv_personal_comercial_marca',
                'unique_together': {('personal', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='PersonalAdministrativoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_administrativo_asignaciones', to='core.marca')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.personaladministrativo')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Personal Administrativo)',
                'verbose_name_plural': 'Asignaciones de Marca (Personal Administrativo)',
                'db_table': 'dxv_personal_administrativo_marca',
                'unique_together': {('personal', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='GastoLogisticoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.gastologistico')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_logistico_asignaciones', to='core.marca')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Gasto Logístico)',
                'verbose_name_plural': 'Asignaciones de Marca (Gasto Logístico)',
                'db_table': 'dxv_gasto_logistico_marca',
                'unique_together': {('gasto', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='GastoComercialMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.gastocomercial')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_comercial_asignaciones', to='core.marca')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Gasto Comercial)',
                'verbose_name_plural': 'Asignaciones de Marca (Gasto Comercial)',
                'db_table': 'dxv_gasto_comercial_marca',
                'unique_together': {('gasto', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='GastoAdministrativoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.gastoadministrativo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_administrativo_asignaciones', to='core.marca')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Gasto Administrativo)',
                'verbose_name_plural': 'Asignaciones de Marca (Gasto Administrativo)',
                'db_table': 'dxv_gasto_administrativo_marca',
                'unique_together': {('gasto', 'marca')},
            },
        ),
    ]
