# Generated by Django 4.2.26 on 2025-12-19 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_poblar_asignaciones_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre'], 'verbose_name': 'Zona Comercial', 'verbose_name_plural': 'Zonas Comerciales'},
        ),
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('escenario', 'nombre')},
        ),
        migrations.AlterField(
            model_name='zona',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='DEPRECADO - Usar asignaciones_marca en su lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca', verbose_name='Marca (Legacy)'),
        ),
        migrations.CreateModel(
            name='ZonaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado a esta marca (0-100). Debe sumar 100% entre todas las marcas.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_asignaciones', to='core.marca')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_marca', to='core.zona')),
            ],
            options={
                'verbose_name': 'Asignación de Marca (Zona)',
                'verbose_name_plural': 'Asignaciones de Marca (Zona)',
                'db_table': 'dxv_zona_marca',
                'unique_together': {('zona', 'marca')},
            },
        ),
    ]
